Fix #82 - added return of the original error during retry function calls
tarantool/cartridge-java pull request #100
Opened 2021-05-18 16:58 UTC by ArtDu

Also added a test catching these errors

2021-05-20 08:59 UTC, vrogach2020 requested changes

2021-05-20 08:59 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java
> +                            ex = new TimeoutException("Operation timeout value exceeded after " + timeElapsed + " ms");
As we discussed let's add new timeout exception type (for example TarantoolTimeoutException) with informative cause() method that contains last error.

2021-05-20 08:59 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/RetryingTarantoolTupleClientIT.java
> +    void testErrorsAfterPolicyTimeout() throws Exception {
Let's add a same test  for AttemptRetryPolicy

2021-05-21 07:50 UTC, vrogach2020 requested changes

2021-05-21 07:50 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java
> +            this.limit = attempts;
I don't see any sense in storing this parameter. Starting number of attemtps is known to the client of this API.

PS and of course this field should be final - it's never changed.

2021-05-21 08:36 UTC, akudiyar requested changes

2021-05-21 08:36 UTC, akudiyar commented on src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java
> +                                "Operation timeout value exceeded after " + timeElapsed + " ms",
Our custom exception can encapsulate the message and have a suitable constructor for just passing the necessary parameters. Let's move the message building into a constructor

2021-05-21 08:36 UTC, akudiyar commented on src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java
> +                                "Attempts limit reached: " + limit,
Let's move the message building into a constructor here too

2021-05-21 08:36 UTC, akudiyar commented on src/test/java/io/tarantool/driver/retry/RequestRetryPolicyTest.java
> +            assertEquals("Attempts limit reached: 4", e.getCause().getMessage());
The previous code checked the internal exception. Let's leave this check too

2021-05-24 10:28 UTC, ArtDu commented on src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java
> +            this.limit = attempts;
I think this is necessary for verbose error information

2021-05-24 13:34 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java
> +            this.limit = attempts;
Not critical, keep it as you wish

2021-05-24 13:41 UTC, vrogach2020 approved these changes

2021-06-25 15:33 UTC, akudiyar approved these changes

2021-06-25 15:33 UTC, merged