Fix flaky tests
tarantool/cartridge-java pull request #101
Opened 2021-05-25 10:05 UTC by ArtDu

* index out of bound error in test
* increase timeouts

2021-06-09 17:25 UTC, akudiyar requested changes

2021-06-09 17:25 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/TarantoolConnectionImpl.java
> +                logger.info("Request {} sent, status Success", request.getHeader().getSync());
Change info to debug

2021-06-22 14:06 UTC, akudiyar requested changes

2021-06-22 14:06 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ClusterConnectionIT.java
> +                    logger.debug("Retrying exception", e);
Debug logging

2021-06-22 14:06 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ClusterConnectionIT.java
> +                    logger.debug("Retrying exception ", e);
Debug logging

2021-06-22 14:06 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ClusterConnectionIT.java
> +        Thread.sleep(5000);
Can we wait for a line in logs here?

2021-06-23 14:54 UTC, ArtDu commented on src/main/java/io/tarantool/driver/AbstractTarantoolClient.java
> +                , resultContainerSupplier, valueConverter);
move the comma to the line above? how is done here? https://github.com/tarantool/cartridge-java/blob/1496c1425f834c997422864c055cfb9d7533d478/src/main/java/io/tarantool/driver/AbstractTarantoolClient.java#L411-L412

2021-06-25 10:22 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ClusterConnectionIT.java
> +        Thread.sleep(5000);
By agreement, expectations were implemented through cartridge.is_healthy

2021-06-25 10:24 UTC, akudiyar commented on src/main/java/io/tarantool/driver/AbstractTarantoolClient.java
> +                , resultContainerSupplier, valueConverter);
Yes, commas shouldn't start the line

2021-06-25 10:28 UTC, ArtDu commented on src/main/java/io/tarantool/driver/AbstractTarantoolClient.java
> +                , resultContainerSupplier, valueConverter);
Then I will close the conversion since I have already fixed it

2021-06-25 10:29 UTC, akudiyar approved these changes

2021-06-25 10:30 UTC, merged