Network default exception checker
tarantool/cartridge-java pull request #102
Opened 2021-06-21 08:10 UTC by ArtDu

Closes #89

2021-06-28 11:08 UTC, akudiyar requested changes

2021-07-12 10:50 UTC, akudiyar requested changes

2021-07-12 10:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerInternalException.java
> + * Represents exceptions
Make a more verbose description, what types of exceptions may be included

2021-07-12 10:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerInternalNetworkException.java
> + * Represents exceptions
Make a more verbose description

2021-07-12 10:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxError.java
> +        this.code = error.get(CODE).toString();
Some  validation is necessary, since the format may be wrong

2021-07-12 10:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxError.java
> +        String message = error.get(MESSAGE).toString();
Such calls may generate NPEs

2021-07-12 10:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolError.java
> +public interface TarantoolError {
Looks like it is a factory

2021-07-12 10:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxError.java
> +public class TarantoolBoxError implements TarantoolError {
It looks like a factory, let it has the corresponding name

2021-07-12 10:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsError.java
> +public class TarantoolErrorsError implements TarantoolError {
It is a factory too

2021-07-12 10:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsError.java
> +        String errorMessage = error.get(ERROR_MESSAGE).toString();
The same notice about validation

2021-07-12 10:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +    public static TarantoolException parse(Value error) {
Seems that the validation and error message building may be moved inside this factory

2021-07-13 16:13 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerInternalException.java
> + * Represents exceptions
Fixed

2021-07-13 16:13 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerInternalNetworkException.java
> + * Represents exceptions
Fixed

2021-07-13 16:15 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxError.java
> +        this.code = error.get(CODE).toString();
Get is called, without checking for contains because this check was above in the code

2021-07-13 16:18 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxError.java
> +        String message = error.get(MESSAGE).toString();
The same as in https://github.com/tarantool/cartridge-java/pull/102#discussion_r668916319 , if only toString can throw an error

2021-07-13 16:26 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolError.java
> +public interface TarantoolError {
Was changed to `TarantoolErrorHandler`, since the Chain of Responsibility pattern is applied, the word factory seems redundant together with Handler

2021-07-13 16:27 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxError.java
> +public class TarantoolBoxError implements TarantoolError {
The same as in https://github.com/tarantool/cartridge-java/pull/102#discussion_r668925092 ,`TarantoolBoxErrorHandler`

2021-07-13 16:28 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsError.java
> +public class TarantoolErrorsError implements TarantoolError {
The same as in https://github.com/tarantool/cartridge-java/pull/102#discussion_r668925092 ,`TarantoolErrorsErrorHandler`

2021-07-13 16:28 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +    public static TarantoolException parse(Value error) {
Fixed

2021-07-13 16:29 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsError.java
> +        String errorMessage = error.get(ERROR_MESSAGE).toString();
The same as in https://github.com/tarantool/cartridge-java/pull/102#discussion_r668916319 , if only toString can throw an error

2021-07-13 17:32 UTC, akudiyar requested changes

2021-07-13 17:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxErrorHandler.java
> +     * The error is parsing, the fields are retrieved if this container.
`Parse the serialized error object and if it matches any of the familiar formats, produce and return a corresponding exception, or an empty {@link Optional} otherwise.`

2021-07-13 17:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxErrorHandler.java
> +     * The error is parsing, the fields are retrieved if this container.
Put this description into the interface

2021-07-13 17:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorHandler.java
> + * A handler that accepts an error and returns a Tarantool Exception
```suggestion
 * A handler that accepts an error and returns a {@link TarantoolException}
```

2021-07-13 17:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsErrorHandler.java
> + * Error that came in format require('errors').new_class("NewError"),
```suggestion
 * Produces {@link TarantoolServerInternalException} subclasses from the serialized representation in the format of <code>require('errors').new_class("NewError")</code>,
```

2021-07-13 17:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsErrorHandler.java
> + * A factory that return a {@link TarantoolException} interface impementaion,
```suggestion
```

2021-07-13 17:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsErrorHandler.java
> + * The fields are generated in a message that is passed to {@link TarantoolServerInternalException}
```suggestion
```

2021-07-13 17:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsErrorHandler.java
> +    private String exceptionMessage;
Unnecessary mutability. Instantiate this variable in the constructor

2021-07-13 17:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +        } catch (Exception e) {
Global exception silencer

2021-07-14 10:01 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerException.java
> + * iProto return not ok.
Fixed

2021-07-14 10:02 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerException.java
>   * Basic exception returned by Tarantool server for unsuccessful operations.
Fixed

2021-07-14 10:02 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolFunctionCallException.java
> + * If result does not match the expected format
Fixed

2021-07-14 10:02 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolFunctionCallException.java
> + * Represents exceptions returned on call operations to Cartridge API
Fixed

2021-07-14 10:02 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerInternalException.java
> + * Represents exceptions returned on call operations to Cartridge API (functions return <code>nil, err</code> on error)
Fixed

2021-07-14 10:02 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerInternalException.java
> + * The error occurs inside tarantool and is interpreted as an internal exception
Fixed

2021-07-14 10:02 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerInternalNetworkException.java
> +public class TarantoolServerInternalNetworkException extends TarantoolException {
Fixed

2021-07-14 10:02 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerInternalNetworkException.java
> + * Represents exceptions returned on call operations to Cartridge API (functions return <code>nil, err</code> on error)
Fixed

2021-07-14 10:02 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerInternalNetworkException.java
> + * The error occurs inside tarantool and is interpreted as an internal exception
Fixed

2021-07-14 10:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolServerInternalNetworkException.java
> + * An error that symbolizes that there was an error related to the network (Connection timeout, No connection, etc.)
Fixed

2021-07-14 10:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxErrorHandler.java
> + * Error that came in format box.error:unpack,
Fixed

2021-07-14 10:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxErrorHandler.java
> + * A factory that return a {@link TarantoolException} interface implementation,
Fixed

2021-07-14 10:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxErrorHandler.java
> + * if the error was a network error, then {@link TarantoolServerInternalNetworkException},
Fixed

2021-07-14 10:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxErrorHandler.java
> + * otherwise {@link TarantoolServerInternalException}
Fixed

2021-07-14 10:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolBoxErrorHandler.java
> +     * The error is parsing, the fields are retrieved if this container.
Fixed

2021-07-14 10:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorHandler.java
> + * A handler that accepts an error and returns a Tarantool Exception
Fixed

2021-07-14 10:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsErrorHandler.java
> + * Error that came in format require('errors').new_class("NewError"),
Fixed

2021-07-14 10:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsErrorHandler.java
> + * A factory that return a {@link TarantoolException} interface impementaion,
Fixed

2021-07-14 10:04 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsErrorHandler.java
> + * The fields are generated in a message that is passed to {@link TarantoolServerInternalException}
Fixed

2021-07-14 10:04 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +        } catch (Exception e) {
fixed, `throw new RuntimeException(e);`

2021-07-14 16:24 UTC, akudiyar requested changes

2021-07-14 16:24 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/TarantoolErrorsIT.java
> +            assertTrue(e.getCause() instanceof TarantoolServerInternalException);
I think you need to check also `!(e.getCause() instanceof TarantoolServerInternalNetworkException)` here

2021-07-14 16:24 UTC, akudiyar commented on src/test/resources/cartridge/app/roles/api_router.lua
> +    return nil, box.error.new(box.error.NO_CONNECTION):unpack()
What's the difference with the above function? Do we have a copy-paste here?

2021-07-14 16:24 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrors.java
> +        public Boolean isErrorsError(String errorMessage) {
Seems that this function should not be public, and can be inlined

2021-07-14 16:26 UTC, akudiyar requested changes

2021-07-14 16:26 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +            throw new RuntimeException(e);
Why is a global exception handler here? We need to catch only the certain types of errors

2021-07-14 16:49 UTC, ArtDu commented on src/test/resources/cartridge/app/roles/api_router.lua
> +    return nil, box.error.new(box.error.NO_CONNECTION):unpack()
errors () was not starting templates for errors like tarantool/errors, I will remove this function

2021-07-14 16:50 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsErrorHandler.java
> +    private String exceptionMessage;
fixed

2021-07-14 17:04 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/TarantoolErrorsIT.java
> +            assertTrue(e.getCause() instanceof TarantoolServerInternalException);
added

2021-07-14 17:05 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrors.java
> +        public Boolean isErrorsError(String errorMessage) {
private added, left function for code consistency with boxError class

2021-07-14 17:05 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +            throw new RuntimeException(e);
catch MessagePackException exception, throw TarantoolClientException

2021-07-14 17:55 UTC, akudiyar requested changes

2021-07-14 17:55 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorFactory.java
> +     * @return an {@link Optional}, If the format is appropriate, then Optional will not be null
`@param` missing for `error`

2021-07-14 17:55 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +    public static TarantoolException parse(Value error) {
Javadoc is missing

2021-07-15 15:25 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +    public static TarantoolException parse(Value error) {
fixed

2021-07-15 15:27 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorFactory.java
> +     * @return an {@link Optional}, If the format is appropriate, then Optional will not be null
fixed

2021-07-15 16:29 UTC, akudiyar requested changes

2021-07-15 16:29 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrors.java
> +            return err != null && err.matches("[\\s\\S]*" +
Use static compiled regex:
```
Pattern p = Pattern.compile(...);
```
and `Pattern.DOTALL` for matching newlines into `.*`

2021-07-15 16:29 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +            return exception.get();
It's better to use here
```
private static tarantoolUnrecognizedErrorFactory = new TarantoolErrors.TarantoolUnrecognizedErrorFactory();
...
return Optional.of(tarantoolUnrecognizedErrorFactory.create(error));
```
rather than confusing the reader with potentially empty `Optional` and forcing the convention that the `TarantoolUnrecognizedErrorFactory` instance should be always present as the last value in the list of error factories.

In this case, we may write `return exception.get()` instead of `break` in the loop.

2021-07-15 17:32 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +            return exception.get();
added return a default factory that will work if the loop does not return

2021-07-15 17:34 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrors.java
> +            return err != null && err.matches("[\\s\\S]*" +
changed API from `String.matches` to `pattern.matcher.find()` with `Pattern.DOTALL`

2021-07-16 10:03 UTC, akudiyar commented
3 things more to do:
1) Merge TarantoolServerException and TarantoolInternalServerException, they have the same meaning, maybe rename to TarantoolInternalException. Rename TarantoolServerInternalNetworkException to TarantoolInternalNetworkException.
2) Add `retryNone`, `retryNetworkErrors` using `retryNone` and rename `withNetworkErrors` to `withRetryingNetworkErrors`
3) Add an example of using retry functions to README

2021-07-17 15:50 UTC, akudiyar approved these changes

2021-07-17 16:00 UTC, merged