Make TarantoolCursor implement Iterator
tarantool/cartridge-java pull request #103
Opened 2021-06-24 13:26 UTC by akudiyar

These changes are necessary for correct Spark connector implementation and so on

2021-06-24 13:45 UTC, vrogach2020 requested changes

2021-06-24 13:45 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/api/cursor/TarantoolCursorBase.java
>              throw new TarantoolSpaceOperationException(
Iterators throw NoSuchElementException when no data avalilable

2021-06-24 13:45 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/api/cursor/TarantoolCursorBase.java
> +    public boolean hasNext() throws TarantoolClientException {
Logic of this method must be changed - hasNext() must not change the state of iterator (see advanceIterator()).

2021-06-24 13:45 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/api/cursor/TarantoolCursor.java
> +public interface TarantoolCursor<T extends Packable> extends Iterator<T> {
Cursors were implemented looking at jdbc cursor. Iterators have different behavior and this implemetation will need significant changes. Maybe it's better to wrap this class [ResultSetIterator](http://commons.apache.org/proper/commons-dbutils/apidocs/org/apache/commons/dbutils/ResultSetIterator.html)  for example.

2021-07-09 18:20 UTC, akudiyar commented
Closing the PR considering the above comments. Implementing java's Iterator is not necessary for the Spark connector.

2021-07-09 18:20 UTC, closed without merging