Implement truncate() method #93
tarantool/cartridge-java pull request #120
Opened 2021-08-31 14:57 UTC by iDneprov

The method calls crud.truncate of box.space.<space_obj>:truncate() for cluster and standalone client implementations.

I think that I should also add tests with truncate on different spaces and for a non-existent space.
Also I should return boolean not in array in TarantoolResultLmpl.java:58.

2021-09-01 10:02 UTC, wey1and commented
Please add "Closes #[issueNumber]" in description of PR.

2021-09-01 10:11 UTC, wey1and commented
Please squash your commits in one commit with informative commit message.

2021-09-01 13:01 UTC, wey1and commented on src/main/java/io/tarantool/driver/api/TarantoolResultImpl.java
> +        } else if (value.isBooleanValue()) {
It is redundant, because we need change return type of `truncate()` to CompletableFuture<Boolean> or CompletableFuture<Void>
Pls try with these return types

2021-09-01 13:36 UTC, vrogach2020 requested changes

2021-09-01 13:36 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/api/space/TarantoolSpace.java
> +            TarantoolCallRequest request = new TarantoolCallRequest.Builder()
This does not correspond to driver design. TarantoolXXXRequest reflects IPROTO native requests [see.](https://www.tarantool.io/ru/doc/latest/dev_guide/internals/box_protocol/) 
I think this is an acceptable solution.

2021-09-01 13:36 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/api/space/TarantoolSpaceOperations.java
> +     * @return an empty future
or void ?
See original box.space_object:truncate() method - it return nil

2021-09-01 13:36 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/SharedCartridgeContainer.java
> +                    "Dockerfile",
Why do we need this ?

2021-09-01 14:07 UTC, iDneprov commented on src/main/java/io/tarantool/driver/api/space/TarantoolSpaceOperations.java
> +     * @return an empty future
This comment is outdated I'll change it.
We call through the call function in tarantool which, if the operation succeeds, returns true and returns false if it succeeds.

2021-09-01 15:30 UTC, iDneprov commented on src/main/java/io/tarantool/driver/api/TarantoolResultImpl.java
> +        } else if (value.isBooleanValue()) {
I don't understand what do you recommend?  Do we leave it as is, or change return type of truncate()?

2021-09-07 19:51 UTC, iDneprov commented on src/main/java/io/tarantool/driver/api/space/ProxyTarantoolSpace.java
> +    public CompletableFuture<Void> truncate() throws TarantoolClientException {
@vrogach2020, you said we should return CompletableFuture<Boolean> it  truncate method. But me and @wey1and wrote truncate that returns CompletableFuture<Void>. 
This design seems more logical to me. But if you're sure that truncate should return CompletableFuture<Boolean>, I'll rewrite this method.

2021-09-08 12:14 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/Utils.java
> +    static void checkSpaceIsEmpty(TarantoolSpaceOperations<TarantoolTuple,
Add description for this method

2021-09-08 12:14 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/Utils.java
> +    static void checkSpaceIsEmpty(TarantoolSpaceOperations<TarantoolTuple,
Can be refactored like this:
```java
assertEquals(0, testSpace.select(Conditions.any()).thenApply(List::size).join());
```

2021-09-08 12:14 UTC, wey1and commented on src/test/java/io/tarantool/driver/proxy/ProxyOperationBuildersTest.java
> +            .withSingleValueResultConverter(v -> null, TarantoolVoidResult.class);
Please use TarantoolVoidResult

2021-09-08 18:43 UTC, iDneprov commented on src/main/java/io/tarantool/driver/proxy/TruncateProxyOperation.java
> +    public static final class Builder<T> {
I think that adding javadoc for all methods is redundant because method names reflect the point of what's going on inside the methods.
If you are sure pleas send me an example of javadoc for one nemthod.

2021-09-08 19:18 UTC, wey1and commented on src/main/java/io/tarantool/driver/proxy/TruncateProxyOperation.java
> +    public static final class Builder<T> {
See TarantoolClientConfig for example
Javadocs is necessary for all public methods, which be used by users.

2021-09-08 19:40 UTC, iDneprov commented on src/main/java/io/tarantool/driver/proxy/TruncateProxyOperation.java
> +    public static final class Builder<T> {
Thank you for example and explanation, I'll add Javadocs for all public methods in all *ProxyOperation classes.

2021-09-08 21:18 UTC, iDneprov commented on src/main/java/io/tarantool/driver/proxy/TruncateProxyOperation.java
> +    public static final class Builder<T> {
I'v added Javadocs for all public methods in TruncateProxyOperation call and is internal class.
I decided to request a review of this Javadocs before  I'll add Javadocs for all public methods in all *ProxyOperation classes and is internal classes because they will mostly look the same.

2021-09-09 08:35 UTC, wey1and commented on src/main/java/io/tarantool/driver/proxy/TruncateProxyOperation.java
> +         * @return builder
return TruncateProxyOperation instance

2021-09-09 08:35 UTC, wey1and commented on src/main/java/io/tarantool/driver/api/TarantoolResultImpl.java
> +import io.tarantool.driver.api.tuple.TarantoolTupleImpl;
Unused imports?

2021-09-09 13:02 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/proxy/TruncateProxyOperation.java
> +public final class TruncateProxyOperation<T>  extends AbstractProxyOperation<T> {
Return value for truncate does not make sense. Remove generic and just extend AbstractProxyOperation<Void>

2021-09-09 13:13 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/api/TarantoolVoidResult.java
> +public interface TarantoolVoidResult extends SingleValueCallResult<Void> {
Void is and absence of result. I think it's not correct to subclass SingleValueCallResult.

2021-09-09 13:39 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ClusterTruncateIT.java
> +    public void singleNodeTruncate100TimesOneSpaceTest() throws Exception {
Why 100 ? I think 2 times is enough.

2021-09-09 13:40 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ClusterTruncateIT.java
> +            for (int i = 0; i < 20; i++) {
1 insert is enough.

2021-09-09 13:41 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ClusterTruncateIT.java
> +        testSpace.truncate().get();
If you are testing the trunctation of empty space not causing an error you must call truncate() twice.

2021-09-09 13:44 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ProxyTruncateIT.java
> +    public void clusterTruncate100TimesOneSpaceTest() throws ExecutionException, InterruptedException {
same comments as for clusterIT

2021-09-14 10:25 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ClusterTruncateIT.java
> +    public void test_truncate2TimesOneSpace_shouldNotThrowExceptionsAndSpaceShouldBeEmptyAfterItchCall()
AfterItchCall?

2021-09-14 10:25 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ClusterTruncateIT.java
> +public class ClusterTruncateIT {
Please add comments "given, when, then" in the tests methods and separate with spaces associated logic with that.

2021-09-14 10:25 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ProxyTruncateIT.java
> +        /*try {
Remove redundant

2021-09-14 10:25 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ProxyTruncateIT.java
> +    public void test_truncate2TimesOneSpace_shouldNotThrowExceptionsAndSpaceShouldBeEmptyAfterItchCall()
I think this test can be refactored like that:
```java
@Test
    public void test_truncate2TimesOneSpace_shouldNotThrowExceptionsAndSpaceShouldBeEmptyAfterItchCall() {
        TarantoolSpaceOperations<TarantoolTuple, TarantoolResult<TarantoolTuple>> testSpace =
                client.space(TEST_SPACE_NAME);

        checkSpaceIsEmpty(testSpace);

        for (int i = 0; i < 2; i++) {
            TarantoolTuple tarantoolTuple = tupleFactory.create(1_000_000, null, "FIO", 50, 100);
            testSpace.insert(tarantoolTuple).join();

            TarantoolResult<TarantoolTuple> selectResult = testSpace.select(Conditions.any()).join();
            assertEquals(1, selectResult.size());

            testSpace.truncate().join();
            checkSpaceIsEmpty(testSpace);
        }
    }
```

2021-09-14 10:25 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ProxyTruncateIT.java
> +        testSpace.truncate().get();
I think we can use `join` instead `get`, because we don't need catching checked exception

2021-09-14 10:25 UTC, wey1and commented on src/test/java/io/tarantool/driver/proxy/ProxyOperationBuildersTest.java
> +    /*CallResultMapper<Void, SingleValueCallResult<Void>> voidResultMapper = mapperFactoryFactory
Remove pls redundant comments

2021-09-14 13:35 UTC, wey1and approved these changes

2021-09-14 15:14 UTC, vrogach2020 approved these changes

2021-09-14 15:14 UTC, merged