WIP
tarantool/cartridge-java pull request #125
Opened 2021-09-06 15:11 UTC by wey1and

2021-09-09 14:35 UTC, ArtDu reviewed
Thanks for the patchset!
I just reviewed only the Builders commit.
See my comments inline and I have general comments regarding the whole patchset. I know that is the only WIP, but please add a description or explanation of changes to a commit message. This will make it easier to review.

2021-09-09 14:35 UTC, ArtDu commented on src/main/java/io/tarantool/driver/clientbuilder/TarantoolProxyClientBuilder.java
> +                TarantoolClient<TarantoolTuple, TarantoolResult<TarantoolTuple>>> {
Maybe that's more readable? (for all big generics)
```suggestion
<ProxyTarantoolTupleClient,
 TarantoolProxyClientBuilder,
 TarantoolClient<TarantoolTuple, TarantoolResult<TarantoolTuple>>> {
```

2021-09-09 14:35 UTC, ArtDu commented on src/main/java/io/tarantool/driver/clientbuilder/TarantoolProxyClientBuilderImpl.java
> +}
In all implementations, we have the same code, maybe there is an opportunity to take him higher to deduplicate

2021-09-10 11:49 UTC, akudiyar requested changes

2021-09-10 11:49 UTC, akudiyar commented on src/main/java/io/tarantool/driver/clientbuilder/TarantoolRetryingClientBuilderImpl.java
> +    }
I also do not get this pattern. And seems that it is very bad: we modify some global state (a singleton instance in a class) with some concrete implementation with its own internal state. It breaks several design principles at once.

Consider using normal class instances created at their point of usage (in the Tarantool Client Factory).

2021-09-10 11:49 UTC, akudiyar commented on src/main/java/io/tarantool/driver/clientfactory/AbstractTarantoolClientBuilderDecorator.java
> +public abstract class AbstractTarantoolClientBuilderDecorator<T, B extends TarantoolClientBuilder<T, B>>
What's the meaning of this class, what problem does it solve?

2021-09-10 11:49 UTC, akudiyar commented on src/main/java/io/tarantool/driver/clientfactory/TarantoolClientBuilders.java
> +public interface TarantoolClientBuilders {
Some leftover?

2021-09-10 11:49 UTC, akudiyar commented on src/main/java/io/tarantool/driver/clientfactory/TarantoolClientFactory.java
> +    TarantoolClientFactory INSTANCE = new TarantoolClientFactoryImpl();
Singleton factory instances are needed if they keep some state. In the other cases, static factory methods are enough.

2021-09-10 11:49 UTC, akudiyar commented on src/main/java/io/tarantool/driver/clientfactory/TarantoolRetyingClientBuilderDecoratorImpl.java
> +package io.tarantool.driver.clientfactory;
Why the factory and builder classes are not in the `api` package or in the root one, where the `TarantoolClient` resides?

The current driver structure implies the separation of classes into packages by domain, not by patterns they implement.

2021-09-14 18:27 UTC, closed without merging