Changed connection logic
tarantool/cartridge-java pull request #156
Opened 2021-11-26 08:28 UTC by wey1and

Fixes https://github.com/tarantool/cartridge-java/issues/149

2021-11-26 10:00 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
> +                    this.connectionManagerHolder.compareAndSet(null,
We do not need atomic reference here since there is double checked lock.

2021-11-26 10:08 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
> +                    this.connectionManagerHolder.compareAndSet(null,
UPD think about making connectionManagerHolder volatile

2021-11-26 10:11 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +                    //todo:
Write a comment of what you are planing TO DO here please

2021-11-26 11:23 UTC, vrogach2020 requested changes

2021-11-26 11:23 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +            connectionRegistry.set(registry);
Why is registry reset on every execution ?

2021-11-26 11:23 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
>      private final AtomicReference<Map<TarantoolServerAddress, List<TarantoolConnection>>> connectionRegistry =
Do we really need atomics here for registry and strategy ? And why ?

2021-11-26 11:23 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +    public void connect() {
This code has a very bad readabilty.

We have methods:
getConnection()
getConnectionInternal()
initConnections()
initReconnectService()
connect()
establishConnections()
getConnections()
establishConnectionsToEndPoint()


All these method names look similar. 
The methods are doing lots of  things - creating objects, locking semaphores. etc. and it is not clear from their names at all.

I think this code needs a heavy refactoring:
 - there should be more descriptive method names and comments
 - try to follow the single responsibilty principle

2021-11-29 22:27 UTC, akudiyar commented
Add a description or a link to an issue with RFC to this task.

2021-11-29 23:13 UTC, akudiyar requested changes
Let's discuss the changes verbally in the near time.
The most important things that are missing here:
1. Description of every change (a detailed RFC). It is not a simple piece of logic, and every reviewer must get the idea first, for not doing reverse engineering and in-head-compiling each time.
2. Separation of fixes from the reconnection policy implementation. It definitely needs an RFC, since it's also not a simple change.
3. Tests for the scenarios to be fixed and new tests for the new behavior. Ideally, some load test suite, that will be added along with this PR and be run periodically forever.

2021-11-29 23:13 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +    public void connect() {
Why is this method needed? It will require each relying library to create and maintain connections by itself. This method is not compatible with lazy init and context manager patterns (try-with-resources).

2021-11-29 23:13 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +        if (connectionRegistry.isEmpty()) {
isEmpty() is not concurrent safe, as the HashMap itself. You will get multiple initConnections() calls. Either use some other Map implementation, or the double-checked locking pattern one more time.

2021-11-29 23:13 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +            result = CompletableFuture.supplyAsync(() -> getConnections().parallelStream()
Always use a specific executor and not the built-in one in such places. parallelStream() invokes a common executor for every such call, so the driver code may compete for resources with some other code.

2021-12-23 15:13 UTC, closed without merging