Fixed connection manager logic
tarantool/cartridge-java pull request #158
Opened 2021-12-02 12:19 UTC by wey1and

Fixed concurrent access to the creation of a connection manager and its internal logic for establishing connections in the event of a partial or complete failure.

2021-12-05 23:01 UTC, akudiyar requested changes

2021-12-05 23:01 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +
Extra newline

2021-12-05 23:01 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/ConnectionMode.java
> +    IN_PROGRESS;
Documentation is required

2021-12-05 23:01 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +
Extra newline

2021-12-05 23:01 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +                            logger.info("Closing connection to {}, connections size greater than {}",
is greater

2021-12-05 23:10 UTC, akudiyar commented
I'd like to add the more detailed description of what's changed:

Previously, when a connection to a host is being failed for some time under constant load, several of the request threads which tried to acquire a connection may turn on the connection mode simultaneously (how many -- depends on the request rate and the timeout to wait until a connection fails). This was happening because there were only two connection states -- "ON" (represented by FULL/PARTIAL) and "OFF", and this led to a situation when one thread finished connecting, a second is waiting until the connection process finishes, and a third starts connecting immediately as it catches the NoAvailableConnectionsException and sees the connection state as "OFF".

In this patch, a new connection state is added -- IN_PROGRESS, and such race condition is not more possible since only one thread actually can set the state to IN_PROGRESS, and only it can switch it back when the connection process is finished (succeed or failed).

2021-12-23 13:59 UTC, vrogach2020 approved these changes

2021-12-24 05:35 UTC, akudiyar requested changes

2021-12-24 05:35 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +        List<TarantoolConnection> connections = connectionRegistry.get(serverAddress);
I didn't get the reason of this change. Some debugging leftovers maybe? Let's change it back.

2021-12-24 08:03 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +        List<TarantoolConnection> connections = connectionRegistry.get(serverAddress);
+1 the previous version looks cuter

2021-12-24 13:00 UTC, akudiyar approved these changes

2021-12-24 13:07 UTC, vrogach2020 approved these changes

2021-12-24 13:10 UTC, merged