Add method for reconnection
tarantool/cartridge-java pull request #160
Opened 2022-01-10 15:20 UTC by wey1and

2022-01-11 11:52 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +    public static String USER_NAME;
why static ? and public ?

2022-01-11 12:41 UTC, vrogach2020 requested changes

2022-01-11 12:41 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +        assertEquals(client.eval("return box.info().uuid").join().get(0),
Flacky check. You can create a client with a connection to a single (switched off router) to check that it is down. Something like
```
bool isDown(int port) {

  try { 
    TarantoolClientFactory.createClient()
                        .withAddresses(
                                new TarantoolServerAddress(container.getRouterHost(), container.getMappedPort(port)),
                        )
                        .withCredentials(USER_NAME, PASSWORD)
                        .build();
   client.getVersion().get();
   return true;
  } catch( TarantoolConnectionException ex ) {
    ...
  }
  return false;
}
```

2022-01-11 12:41 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +        assertEquals(routerUuids.size(), uuidsAfterReconnect.size());
I think the more robust check is to use
```
localhost:3301> box.stat.net().CONNECTIONS
---
- current: 3
  rps: 0
  total: 4
...
```

2022-01-11 12:41 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +    private Set<String> getInstancesUuids(TarantoolClient<TarantoolTuple, TarantoolResult<TarantoolTuple>> client) {
Looks like a flacky check too.
I think the good scenario is:
0) set number of connections to 10
1) start 3 routers. Check that each of three clients has 10 connections via box.stat.net()
2) shut down 2 routers. Check that they are down
3) restart 2 routers. Wait. Check that only first router has 10 connections and others have 0.
4) execute establishLackingConnections()
5) check that all routers have 10 connections each.

2022-01-12 12:52 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +    public static String USER_NAME;
Made it private
Static is needed for convenience

2022-01-12 12:52 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +        assertEquals(client.eval("return box.info().uuid").join().get(0),
There will be no flacking because if we have one and the same uuid instance returning in a row, then this is a signal that there is only one router left

2022-01-12 12:52 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +        assertEquals(routerUuids.size(), uuidsAfterReconnect.size());
box.stat.net (). CONNECTIONS is not a very accurate indicator of connections, since connections between tarantool instances are also counted there

2022-01-12 12:52 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +    private Set<String> getInstancesUuids(TarantoolClient<TarantoolTuple, TarantoolResult<TarantoolTuple>> client) {
This method works correctly when using the round robin connection selection strategy. In addition, it is universal and works on any number of routers and connections.

2022-01-12 15:40 UTC, vrogach2020 approved these changes

2022-01-12 15:56 UTC, merged