Added test for reproduce "Procedure 'crud.*' is not defined" problem
tarantool/cartridge-java pull request #162
Opened 2022-01-21 15:26 UTC by wey1and

2022-01-27 17:23 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/ErrorCode.java
> + * Error codes used to classify errors
Please describe here where these codes come from, you can link to the code in the documentation or github

2022-01-27 17:31 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrors.java
>      public static class TarantoolBoxErrorFactory implements TarantoolErrorFactory {
We need to think about renaming BoxError. Because we have the logic that lua error() and tarantool box.error() generate IPROTO_NOT_OK. Those the principle of their work is the same, box.error can be caught in the same way with pcall(). And if we generate lua error() it is perceived by the connector as box.error

2022-01-31 10:22 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrors.java
>      public static class TarantoolBoxErrorFactory implements TarantoolErrorFactory {
This is an incorrect assumption about lua's excellent `error()` structure. Please leave a correct link to the doc, where it says that lua `error()` is wrapped in box.error with code 32. Now a link to a specific method, but you need to the whole box.error - https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_error/

2022-02-03 21:18 UTC, vrogach2020 requested changes

2022-02-03 21:18 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +    private boolean crudProcedureIsNotDefined;
This can be a local variable in  test_should_reconnect_ifReconnectIsInvoked()

2022-02-03 21:18 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +        Thread.sleep(500);
Looks like flaky condition - you have retry with 5 attempts and delay 100ms.   Maybe decrease this sleep to 300 ?

2022-02-03 21:18 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +    public void test_should_reconnect_ifReconnectIsInvoked() throws InterruptedException {
In what line of this tescase the 'reconnect is invoked' ?

2022-02-03 22:25 UTC, wey1and commented on src/main/java/io/tarantool/driver/exceptions/errors/BoxErrorKey.java
> +    CODE("code", ValueFactory.newString("code")),
This is necessary in order not to create a msgPack string every time, since enum values are static, which will lead to better performance.

2022-02-03 22:28 UTC, wey1and commented on src/main/java/io/tarantool/driver/exceptions/errors/ErrorsErrorKey.java
> +    ERROR_MESSAGE("str", ValueFactory.newString("str")),
These values were taken from the constants in the refactored code without changes

2022-02-03 22:29 UTC, wey1and commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +            return errorsFactories.stream()
Maybe you are right. I suggested a more compact alternative.

2022-02-03 22:45 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +    private boolean crudProcedureIsNotDefined;
You cannot assign effectively final variables inside lambda expressions. But we can make it atomic boolean.

2022-02-03 22:51 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +        Thread.sleep(500);
We discussed it and talked about a few milliseconds. How many times I ran it - nothing flacked. But i will increase just to your sure.

2022-02-04 07:14 UTC, akudiyar requested changes
Mostly LGTM, but IT tests need more consideration.

2022-02-04 07:14 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/BoxErrorKey.java
> +    CODE("code", ValueFactory.newString("code")),
I agree with Oleg, this way it seems better.

2022-02-04 07:14 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
> +            return errorsFactories.stream()
Use first() + orElse() here, since you don't really need a list.

2022-02-04 07:14 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +        Thread.sleep(500);
This test seems unreliable, because we don't force the conditions on the server side. It may always pass in the test env by that.

2022-02-04 11:26 UTC, wey1and commented on src/main/java/io/tarantool/driver/exceptions/errors/BoxErrorKey.java
> + * Errors keys for error message in box error
Discussed verbally with Vladimir. We decided not to add it yet, since this was not originally, and the current changes are only refactoring.

2022-02-04 11:26 UTC, wey1and commented on src/main/java/io/tarantool/driver/exceptions/errors/ErrorsErrorKey.java
> + * Errors keys for error message from tarantool/errors library
Discussed verbally with Vladimir. We decided not to add it yet, since this was not originally, and the current changes are only refactoring.

2022-02-07 14:54 UTC, vrogach2020 approved these changes

2022-02-07 14:55 UTC, vrogach2020 commented
@wey1and please do not forget to include backwards compatibility changes into changelog

2022-02-08 07:17 UTC, ArtDu commented
@wey1and Please squash commits and make one commit message with list of what has changed

2022-02-08 07:58 UTC, akudiyar requested changes

2022-02-08 07:58 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +    public static Predicate<Throwable> retryTarantoolNoSuchProcedureErrors() {
There should be also a `withRetryingNoSuchProcedureErrors` compartment for this function, otherwise the user will not be able to extend this built-in checker with custom error checkers.

2022-02-08 07:58 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
> +        return connectionManager().establishLackingConnections();
Please rename the function in a separate PR before making a release. We shouldn't show any implementation details in API (corresponds to the Open-Closed principle in SOLID).

2022-02-08 07:58 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/TarantoolNoSuchProcedureException.java
> + * An exception occurs when the procedure has not (yet) been defined.
```suggestion
 * Corresponds to an exception that occurs when the procedure has not (yet) been defined in the Tarantool instance.
```

2022-02-08 07:58 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/TarantoolNoSuchProcedureException.java
> + * For example: this exception can be raised when a role is not up yet or being reloaded at the moment.
```suggestion
 * For example: this exception can be raised when a Cartridge role is not up yet or is being reloaded at the moment.
```

2022-02-08 07:58 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/TarantoolNoSuchProcedureException.java
> + * You can use this exception as a sign that it's worth trying a few more times until the role is up.
```suggestion
 * You can use this exception when you are sure that it's worth trying a few more times until the role is up.
```

2022-02-08 07:58 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrors.java
> +        private static final int ERROR_INDICATOR_OFFSET = 32768;
Is omitting "L" here safe? Did you test it?

2022-02-08 12:33 UTC, wey1and commented on src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
> +        return connectionManager().establishLackingConnections();
Yes, thank you, we remember this.

2022-02-08 13:46 UTC, wey1and commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +    public static Predicate<Throwable> retryTarantoolNoSuchProcedureErrors() {
Discussed with Alexey in correspondence. We decided that the comment is not relevant, since the Predicate interface provides the necessary API.

2022-02-08 16:22 UTC, ArtDu commented
nit: 

The PR title does not reveal what is in the PR. It seems better not to use the word refactoring, because there was not only a refactoring, but also changes in API of the `exceptions.errors` package. And since the external behavior of the code will change, then you can not use this word, it seems better to use a `CHANGE` or something like that. 

Just this will be a generalized version of what is happening in PR. And in the description, you can just write that a refactoring has taken place, the API has changed and a new exception has been added and why it was added. And I expect to see this also in the final squashed commit message.

2022-02-08 20:47 UTC, ArtDu submitted a review, later dismissed
LGTM

2022-02-08 21:33 UTC, akudiyar requested changes

2022-02-08 21:33 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +        client = new RetryingTarantoolTupleClient(new ProxyTarantoolTupleClient(clusterClient),
nit: Why do we still use an old approach here and not the new shiny Builder?

2022-02-08 21:33 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +        Thread.sleep(500);
Do not get why we need the second sleep. I'd rather write this test in another way: 
1) Set the crud to nil and loop with small sleeps until a target error occurs
2) Set the crud back and loop with small sleeps until the call passes without errors or fail the test after a timeout.

2022-02-10 06:47 UTC, vrogach2020 approved these changes

2022-02-10 08:41 UTC, akudiyar approved these changes
LGTM.

BTW there is a `truncate_space()` test failing on 1.10 -- we need to fix it.

2022-02-10 08:45 UTC, ArtDu approved these changes

2022-02-10 08:46 UTC, vrogach2020 commented
@akudiyar  Created an issue on truncate
#164

2022-02-10 08:48 UTC, merged