Prevent multiple call of TarantoolClusterDiscoveryConfig.Builder().withEndpoint()
tarantool/cartridge-java pull request #192
Opened 2022-03-30 14:21 UTC by dkasimovskiy

Throw exception if TarantoolClusterDiscoveryConfig.Builder().withEndpoint() called multiple times
Closes #173

2022-03-31 15:09 UTC, wey1and requested changes

2022-03-31 15:09 UTC, wey1and commented on src/test/java/io/tarantool/driver/cluster/TarantoolClusterDiscoveryConfigTest.java
> +    private static class FakeTarantoolClusterDiscoveryEndpoint implements TarantoolClusterDiscoveryEndpoint {
You can use empty class `new TarantoolClusterDiscoveryEndpoint(){}`, `BinaryClusterDiscoveryEndpoint` or `HTTPClusterDiscoveryEndpoint` instead.

2022-03-31 15:20 UTC, dkasimovskiy commented on src/test/java/io/tarantool/driver/cluster/TarantoolClusterDiscoveryConfigTest.java
> +    private static class FakeTarantoolClusterDiscoveryEndpoint implements TarantoolClusterDiscoveryEndpoint {
Done

2022-03-31 15:29 UTC, wey1and approved these changes

2022-03-31 15:29 UTC, wey1and commented on src/test/java/io/tarantool/driver/cluster/TarantoolClusterDiscoveryConfigTest.java
> +    private static class FakeTarantoolClusterDiscoveryEndpoint implements TarantoolClusterDiscoveryEndpoint {
You can use empty class `new TarantoolClusterDiscoveryEndpoint(){}`, `BinaryClusterDiscoveryEndpoint` or `HTTPClusterDiscoveryEndpoint` instead.

2022-04-05 08:36 UTC, wey1and approved these changes

2022-04-05 10:41 UTC, vrogach2020 approved these changes

2022-04-05 10:41 UTC, merged