Fix NPE in AbstractTarantoolConnectionManager
tarantool/cartridge-java pull request #196
Opened 2022-04-05 13:53 UTC by dkasimovskiy

Return IllegalArgumentException with description instead of NPE
Return empty list by default in TarantoolClusterConnectionManager.addressProvider
Closes #87

2022-04-05 16:09 UTC, vrogach2020 requested changes

2022-04-06 07:42 UTC, dkasimovskiy commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +            throw new IllegalArgumentException("TarantoolServerAddress collection couldn't be null");
Done

2022-04-06 07:42 UTC, dkasimovskiy commented on src/main/java/io/tarantool/driver/core/connection/TarantoolClusterConnectionManager.java
> +        return Optional.ofNullable(addressProvider.getAddresses()).orElse(new ArrayList<>());
Done

2022-04-06 09:01 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +            logger.warn("The list of server addresses is not defined");
Логать тут можно, но только в debug.
Если возникнет такая ситуация под нагрузкой то warn забьёт всё место на сервере

2022-04-06 09:01 UTC, wey1and requested changes

2022-04-06 09:01 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ConnectionIT.java
> +        assertThrows(TarantoolClientException.class, () -> {
This assert doesn't check NPE

2022-04-06 09:03 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +
Why ? This method works correctly with empty lists. So we just cast null to empty list here

2022-04-06 09:07 UTC, wey1and commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +
I consider this the responsibility of the concrete implementation, not the abstract class.

2022-04-06 09:17 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +
@dkasimovskiy discussed with @wey1and  - the decision is up to you :)  - keep the check here or move to concrete class - it doesn't matter. We are going to refactor this code a bit later.

2022-04-06 09:35 UTC, dkasimovskiy commented on src/test/java/io/tarantool/driver/integration/ConnectionIT.java
> +        assertThrows(TarantoolClientException.class, () -> {
Why do we need to check NPE if we are fix it?

2022-04-06 09:38 UTC, wey1and commented on src/test/java/io/tarantool/driver/integration/ConnectionIT.java
> +        assertThrows(TarantoolClientException.class, () -> {
We need to check that we don't have NPE anymore

2022-04-06 10:13 UTC, dkasimovskiy commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +
Let's keep it in the current place

2022-04-06 10:22 UTC, wey1and requested changes

2022-04-06 10:22 UTC, wey1and commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +            throws IllegalArgumentException {
IllegalArgumentException is redundant here

2022-04-06 10:54 UTC, dkasimovskiy commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +            throws IllegalArgumentException {
Removed

2022-04-06 11:00 UTC, wey1and approved these changes

2022-04-06 11:53 UTC, vrogach2020 approved these changes

2022-04-06 11:53 UTC, merged