WIP: Added support SSL/TLS
tarantool/cartridge-java pull request #202
Opened 2022-04-13 09:02 UTC by wey1and

2022-04-13 09:51 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/SslClientIT.java
> +@Testcontainers
Это не нужно, у нас тестконтейнер статический шареный - им не надо управлять извне

2022-04-13 09:57 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolSSLException.java
> +public class TarantoolSSLException extends TarantoolException {
Where is this excepion used? I haven't found any mentions

2022-04-13 10:11 UTC, wey1and commented on src/main/java/io/tarantool/driver/exceptions/TarantoolSSLException.java
> +public class TarantoolSSLException extends TarantoolException {
This is for the future

2022-04-15 17:15 UTC, ArtDu commented
Maybe can you make tests based on `jmh`, as I did for mine PR? 
https://github.com/tarantool/cartridge-java/pull/204

We will find out how much slower  ssl is compared to regular iproto

2022-04-16 19:22 UTC, akudiyar commented
Please add a brief description of the changes -- what was changed, why this change is needed.

2022-04-16 19:57 UTC, akudiyar requested changes
Please add examples of using the new options and methods in the README and javadocs.

2022-04-16 19:57 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/TarantoolClientConfig.java
> +            Assert.notNull(sslContext, "Specified in client config SslContext must not be null");
Nit: "SslContext must not be null" is enough.

2022-04-16 19:57 UTC, akudiyar commented on src/main/java/io/tarantool/driver/exceptions/TarantoolSSLException.java
> +public class TarantoolSSLException extends TarantoolException {
Please don't add any not used code.

2022-04-16 19:57 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/SslClientIT.java
> +        assertThrows(TarantoolClientException.class, clientWithSsl::getVersion);
It would be nice to check the exception message here as well.

2022-04-16 19:57 UTC, akudiyar commented on src/test/resources/org/testcontainers/containers/ssl/ssl_server.lua
> +box.cfg { listen = {
This server script doesn't seem to be used anywhere. Isn't there a mistake in the tests?

2022-04-16 19:57 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/TarantoolClientConfig.java
> +        public Builder withSslContext(SslContext sslContext) {
I would suggest the following:
Add a method that adds a "secure" flag like this: https://github.com/beyondglow/spring-sourcecode/blob/8c983b1d818739ed62677cabbda79c827339afe7/spring-web/src/main/java/org/springframework/http/client/Netty4ClientHttpRequestFactory.java#L198. This will allow users to have an SSL config with disabling the SSL connection on demand in some code places without ugly setting the context to `null`.
Also, it may be useful to add an ability to set up a default SSL context if this `secure` flag is set but the context is not set up. This will ease the life of users and they won't have to learn the Netty docs for just testing the SSL connection.

2022-04-18 08:29 UTC, ArtDu commented on src/main/java/io/tarantool/driver/exceptions/TarantoolSSLException.java
> +public class TarantoolSSLException extends TarantoolException {
I thought that "future" exception will be used in this PR. @wey1and correct me if i'm wrong

2022-05-19 10:23 UTC, wey1and commented on src/main/java/io/tarantool/driver/api/TarantoolClientConfig.java
> +        public Builder withSslContext(SslContext sslContext) {
Thanks for your suggestion! We will add this in next PR's.

2022-05-19 10:41 UTC, vrogach2020 approved these changes

2022-05-19 10:43 UTC, vrogach2020 commented
@wey1and please create issues on follow-ups from @akudiyar and @ArtDu

2022-05-19 10:51 UTC, merged

2022-05-19 12:18 UTC, wey1and commented on src/main/java/io/tarantool/driver/api/TarantoolClientConfig.java
> +        public Builder withSslContext(SslContext sslContext) {
https://github.com/tarantool/cartridge-java/issues/220