WIP: Remove converters' find with reflection
tarantool/cartridge-java pull request #204
Opened 2022-04-14 14:26 UTC by ArtDu

Closes #178

2022-04-14 15:22 UTC, vrogach2020 commented
It would be nice to see some perf tests results here on simple and complex types

2022-04-16 18:52 UTC, akudiyar commented
@ArtDu please add a brief description of the changes -- what was changed, why this change is needed.

2022-04-16 19:19 UTC, akudiyar requested changes

2022-04-16 19:19 UTC, akudiyar commented on pom.xml
> +            <version>1.35</version>
This needs to be in the test scope

2022-04-16 19:19 UTC, akudiyar commented on pom.xml
> +            <version>1.35</version>
Test scope as above

2022-04-16 19:19 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/MessagePackMapperBuilder.java
> +                                                                     ValueConverter<?, O> converter);
This is a bad change actually. Why do we need it? I think we need a more precise generic definition, like `? extends V`, for example.

2022-04-16 19:19 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/AbstractResultMapper.java
> +                                                            ValueConverter<?, ? extends O> converter) {
Same as above, wrong generic definition

2022-04-16 19:19 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/DefaultExtensionValueToUUIDConverter.java
> +package io.tarantool.driver.mappers;
Don't get why this file appears as new. Would you mind describing these changes?

2022-04-16 19:19 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/DefaultBigIntegerValueToFloatConverter.java
> +    private static final long serialVersionUID = 5249538902877730493L;
Is this an original version ID? We used to put dates as serial version IDs.

2022-04-19 16:10 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/AbstractResultMapper.java
> +                                                            ValueConverter<?, ? extends O> converter) {
Changed to
```java
public <V extends Value, O> void registerValueConverter(Class<V> valueClass,
                                                      Class<? extends O> objectClass,
                                                      ValueConverter<V, ? extends O> converter) {


```

2022-04-19 16:11 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/MessagePackMapperBuilder.java
> +                                                                     ValueConverter<?, O> converter);
Changed to
```java
<V extends Value, O> MessagePackMapperBuilder withValueConverter(Class<? extends V> valueClass, Class<O> objectClass,
                                                                     ValueConverter<V, O> converter);


```

2022-04-19 16:12 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/DefaultExtensionValueToUUIDConverter.java
> +package io.tarantool.driver.mappers;
In short, the converters containing the implementing and ValueConverter and ObjectConveter are divided into separate classes for ease of use and in order to be able to register a `valueConverter` of this type `ImmutableStringValueImpl -> String`, and an `objectConverter` of this type `String -> StringValue`

2022-04-19 17:15 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/DefaultBigIntegerValueToFloatConverter.java
> +    private static final long serialVersionUID = 5249538902877730493L;
Fixed

2022-04-20 10:46 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/MessagePackMapperBuilder.java
> +import io.tarantool.driver.mappers.converters.ValueConverter;
I don't mind leaving converters in the same folders to avoid breakin changes, but it seems better to separate converters and mappers, given that there are more than 50 files in one package

2022-04-22 11:10 UTC, vrogach2020 approved these changes

2022-04-26 16:30 UTC, ArtDu commented
Should test perf of converting with TarantoolTuple and getting with targetType

```java
TarantoolTuple tuple = ...
tuple.getObject("fieldName", Integer.class)
```

2022-04-28 08:43 UTC, akudiyar approved these changes
LGTM.
However I **highly** recommend to do at least local testing of the new changes with SpringData before merging. 

P.S. The new converters should go in a follow-up PR. The GH review interface is already completely broken at this number of changes +_+

2022-04-28 09:00 UTC, ArtDu commented
> LGTM. However I **highly** recommend to do at least local testing of the new changes with SpringData before merging.
> 
> P.S. The new converters should go in a follow-up PR. The GH review interface is already completely broken at this number of changes +_+

Yeah, I tested snapshot with cartridge-springdata, we have to rewrite registration of `TarantoolAutoConverter` but everything else looks fine

2022-04-28 09:09 UTC, merged