Added review checklist and PR template
tarantool/cartridge-java pull request #206
Opened 2022-04-15 13:24 UTC by vrogach2020

2022-04-15 13:29 UTC, wey1and approved these changes

2022-04-15 17:09 UTC, ArtDu submitted a review, later dismissed

2022-04-16 18:51 UTC, akudiyar requested changes

2022-04-16 18:51 UTC, akudiyar commented on .github/pull_request_template.md
> +- [ ] Documentation
I think that we are lacking doc update instructions (javadocs are pushed to a special branch that contains only the javadocs).

2022-04-16 18:51 UTC, akudiyar commented on docs/review-checklist.md
> +# Code review checklist for java projects
I think that we need some limits for the PR size and some recommendations for test coverage (what can be covered with unit tests, what needs to be covered with integration tests), as well as recommendations for the Javadocs, since they are very important for the driver usage.

2022-04-16 18:51 UTC, akudiyar commented on docs/review-checklist.md
> +- StringBuilder or StringBuffer is used to perform multiple concatenations on strings (instead of '+')
This recommendation is in fact outdated. Since Java 7 StringBuilders are used internally for concatenations, so use them explicitly only when a string is built dynamically with different conditions,

2022-04-16 18:51 UTC, akudiyar commented on docs/review-checklist.md
> +- For many choices `switch case` is used instead of multiple if-else conditions
I would also add a related recommendation for using enums over String constants. BTW, this and many other useful recommendations can be found in the brilliant book "Effective Java" by J. Bloch.

2022-04-16 18:51 UTC, akudiyar commented on docs/review-checklist.md
> +- Used checked exceptions for recoverable operations and runtime exceptions for programming errors
We agreed for using RuntimeExceptions most of the time to not complicate the users' code and make it more usable in the reactive programming patterns. All internally produced exceptions must be classified and be instances of a TarantoolException class.

2022-04-16 18:51 UTC, akudiyar commented on docs/review-checklist.md
> +- Code is DRY (see Do not Repeat Yourself principle)
I would relax this a bit by a rule "any simple code part shouldn't be repeated more than two times, and any complex code part should be enclosed in a corresponding method or a class". Obviously, complex code is constructed from simple code parts. You can think of a simple part like a one-liner.

2022-04-16 18:51 UTC, akudiyar commented on docs/review-checklist.md
> +- Ensure override hashCode when overriding equals
I would suggest using generated hashCode/equals by your IDE (I suggest IDEA for this purpose). Don't write any custom code here if not strictly necessary. Also, don't add these methods if the class is not supposed to be used as a hash key or to be serialized. This will help to avoid the wrong usage.

2022-04-16 18:51 UTC, akudiyar commented on docs/review-checklist.md
> +# Code review checklist for java projects
Also, most of the below recommendations and many more can be satisfied by an automatic code style fixing tool, like reformat command in IDEA or SonarLint in VStudio (https://code.visualstudio.com/docs/java/java-linting). Use reformatters and don't waste time on discussing code style changes, focus on things that matter instead.

2022-04-16 18:51 UTC, akudiyar commented on docs/review-checklist.md
> +# Code review checklist for java projects
One more thing that often irritates me -- code style changes in unrelated code parts (even in the same file) should go in separate PRs to not distract the readers from the actual changes. GH review interface is not very well in showing the in-line whitespace changes, so we'd better not mess up the PRs.

2022-04-25 10:19 UTC, vrogach2020 commented on .github/pull_request_template.md
> +- [ ] Documentation
Updating javadocs seems to be a part of release process and remain the responsibility of project maintainer.

2022-04-25 10:40 UTC, vrogach2020 commented on docs/review-checklist.md
> +# Code review checklist for java projects
> we need some limits for the PR size

Sane limit values are hard to imagine.
It's a 'hard to follow' and contradictory rule.

> recommendations for test coverage, javadocs

Not a subject of checklist. We must have simple and verifiable points here.
It can be a style guide or some coding conventions.

> below recommendations and many more can be satisfied by an automatic code style fixing tool

The developer is responsible for his code (it doesn't matter what tools he uses or not).
Automation of checking style is another problem/task. Here we just want to fix the aggreements on code style.

> code style changes in unrelated code parts 
As well as 1 - It's a 'hard to follow' and contradictory rule.

2022-04-25 10:41 UTC, vrogach2020 commented on docs/review-checklist.md
> +- StringBuilder or StringBuffer is used to perform multiple concatenations on strings (instead of '+')
removed

2022-04-25 10:45 UTC, vrogach2020 commented on docs/review-checklist.md
> +- For many choices `switch case` is used instead of multiple if-else conditions
Removed the point (it's not an ofter case). Good coding style can't be covered by this checklist

2022-04-25 10:51 UTC, vrogach2020 commented on docs/review-checklist.md
> +- Used checked exceptions for recoverable operations and runtime exceptions for programming errors
Removed a point. You're right but I don't want to metion TarantoolException here to avoid debates.

2022-04-25 12:15 UTC, vrogach2020 commented
@akudiyar please review

2022-04-28 08:26 UTC, akudiyar commented on docs/review-checklist.md
> +# Code review checklist for java projects
I think we can discuss these points later in DM

2022-04-28 08:33 UTC, merged