Set correct fieldNumber in indexMetadata
tarantool/cartridge-java pull request #209
Opened 2022-04-21 15:23 UTC by dkasimovskiy

There are two aspects of this issue:
1) Incorrect fieldNumber in the index part metadata. All fieldNumber decreased by one for all indexes.
2) When the driver try to find suitable index by field name it compares fieldNumber in the indexPartMetadata and selected fields. This can lead to a situation where the driver will select the wrong index or will not be able to find the index at all.

Closes #203

2022-04-21 16:48 UTC, vrogach2020 requested changes

2022-04-21 16:48 UTC, vrogach2020 commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +        TarantoolResult<TarantoolTuple> insertTuples = profileSpace.insert(tarantoolTuple).get();
Use replace() instead of insert(). Also please add the space 'cursor_test_space' to truncateSpace() setup block to avoid intersections.

2022-04-21 16:48 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java
> +                        return new TarantoolIndexPartMetadataImpl(fieldNumber, fieldType, fieldPath);
Please add short description of the fix to changelog

2022-04-22 09:04 UTC, dkasimovskiy commented on src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java
> +                        return new TarantoolIndexPartMetadataImpl(fieldNumber, fieldType, fieldPath);
@ArtDu Nope. This is a bug. Possitions for indexes starts from 0.
Check with `box.space._vindex:select()`

2022-04-22 09:38 UTC, vrogach2020 approved these changes

2022-04-22 09:38 UTC, merged

2022-04-22 09:46 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java
> +                        return new TarantoolIndexPartMetadataImpl(fieldNumber, fieldType, fieldPath);
@dkasimovskiy I checked ) 
```lua
tarantool> box.space._vindex:select()[1]
---
- [272, 0, 'primary', 'tree', {'unique': true}, [[0, 'string']]]
...

tarantool> box.space._vindex:select()[1][1]
---
- 272
...

tarantool>
```