WIP: Enum
tarantool/cartridge-java pull request #210
Opened 2022-04-25 15:52 UTC by ArtDu

2022-04-28 18:07 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/DefaultMultiValueResultMapper.java
> -
Weird unused code, we don't have an equivalent in `DefaultSingleValueResultMapper`

2022-04-28 18:47 UTC, vrogach2020 submitted a review, later dismissed
LGTM

2022-05-09 19:31 UTC, akudiyar requested changes
The idea is not bad, but I suggest not changing the existing API that takes Java classes and just adding new methods. See comments below.

2022-05-09 19:31 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/MessagePackMapperBuilder.java
> -    withValueConverter(Class<V> valueClass, ValueConverter<V, O> converter);
I basically don't like much the idea of **changing** the API for using the ValueType. As discussed, there may be cases when a Value class is more useful since it is a Java class and not a MessagePack type, and they don't have a  1-1 match.

I suggest adding a new interface with converters matched by ValueType and implement it, leaving the former variant as a backup. We can then `ValueType`s in the default  implementation for performance, but it will not break anything.

2022-05-09 19:31 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/DefaultMultiValueResultMapper.java
> -
The issue with this constructor is that it was intended to be used with the passed valueMapper, but it is possibly not safe.

2022-05-09 19:31 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/DefaultMultiValueResultMapper.java
> -    defaultValueConverter(ValueConverter<Value, T> valueConverter,
Why this was removed?

2022-05-12 21:45 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/MessagePackMapperBuilder.java
> -    withValueConverter(Class<V> valueClass, ValueConverter<V, O> converter);
We still use the Value classes for all operations, except for one - finding converters in the Map. And there is no problem with it:

```
ImmutableNilValueImpl        -> NIL
ImmutableBooleanValueImpl    -> BOOLEAN

ImmutableBigIntegerValueImpl -> INTEGER
ImmutableLongValueImpl       -> INTEGER

ImmutableDoubleValueImpl     -> FLOAT
ImmutableStringValueImpl     -> STRING
ImmutableBinaryValueImpl     -> BINARY
ImmutableArrayValueImpl      -> ARRAY
ImmutableMapValueImpl        -> MAP
ImmutableExtensionValueImpl  -> EXTENSION
```
We use ValueType only in search, i.e. map certain converters to our ValueType and see no problem or benefit in using the class as the map key. On the contrary, it's the same approach as you used before with reflection when using [interfaces](https://github.com/tarantool/cartridge-java/blob/2bb9de7626b3a4004264e322047027f44f794fc9/src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapperFactory.java#L31-L48)
```
ImmutableNilValueImpl        -> NilValue
ImmutableBooleanValueImpl    -> BooleanValue

ImmutableBigIntegerValueImpl -> IntegerValue
ImmutableLongValueImpl       -> IntegerValue

ImmutableDoubleValueImpl     -> FloatValue
ImmutableStringValueImpl     -> StringValue
ImmutableBinaryValueImpl     -> BinaryValue
ImmutableArrayValueImpl      -> ArrayValue
ImmutableMapValueImpl        -> MapValue
ImmutableExtensionValueImpl  -> ExtensionValue
```
This is just the same thing, but you don’t need to go to the root of the class. We just map the defined list of converters to some class whose root of that value is the ValueType. At the stage of comparison, we do not lose sight of any converter, and then you can always use the **canConvertValue** function of the converter and check exactly the class, if you somehow need it. Those, for example you have two converters for `ValueType.INTEGER`. These are BigIntegerConverter and LongConverter and inside you can already do something like this
```java
public class BigIntegerConverter implements ValueConverter<IntegerValue, BigInteger> {
    ...
    @Override
    public boolean canConvertValue(IntegerValue value) {
        return value.getClass().equals(ImmutableBigIntegerValueImpl.class);
    }
}
```

2022-05-12 21:54 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/DefaultMultiValueResultMapper.java
> -
We passed `valueMapper`, but it doesn't used
![image](https://user-images.githubusercontent.com/22258443/168174374-348c63bf-a075-440f-bc9c-596f45d31e82.png)

2022-05-12 21:57 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/DefaultMultiValueResultMapper.java
> -    defaultValueConverter(ValueConverter<Value, T> valueConverter,
This is internal code that is only used in the removed constructor of the `DefaultMultiValueResultMapper`. See above

2022-05-19 08:15 UTC, vrogach2020 commented on src/main/java/io/tarantool/driver/api/MessagePackMapperBuilder.java
> -    withValueConverter(Class<V> valueClass, ValueConverter<V, O> converter);
@akudiyar @ArtDu I don't see any more blockers here for release. Artem done a great job simlifying the code. 
If we have any strange problem cases we'll fix it in later releases.

2022-05-19 08:15 UTC, vrogach2020 approved these changes

2022-05-19 08:16 UTC, merged