Fix checkConverterByTargetType logic
tarantool/cartridge-java pull request #215
Opened 2022-05-01 12:15 UTC by ArtDu

Now the connector doesn't search converter's targetType by reflection,
the targetType is stored with the converter. Operations to convert a value with targetType are faster.

I didn't forget about

- [x] Tests (It isn't a new feature, all tests are the same)
- [ ] Changelog
- [ ] Documentation
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Closes #212

2022-05-09 19:38 UTC, akudiyar requested changes

2022-05-09 19:38 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
> -    private boolean checkConverterByTargetType(ValueConverter<? extends Value, ?> converter, Class<?> targetClass) {
Look, this logic allows to use the closest existing converter if a target converter doesn't exist in the mappers list. Don't remove this logic since it will break the SpringData internal object conversion algorithms, just make the reflection search an alternative way for the cases when the converter is not found by class directly in the list.

2022-05-09 19:38 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
> -    private boolean checkConverterByTargetType(ValueConverter<? extends Value, ?> converter, Class<?> targetClass) {
Of course, we will need tests for both cases.

2022-05-10 16:57 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
> -    private boolean checkConverterByTargetType(ValueConverter<? extends Value, ?> converter, Class<?> targetClass) {
We have two searchs here which connected with an OR condition:
1. Search of the last registered converter for targetType in the `valueConvertersByTarget` map, which is a kind of cache since if you remove it, nothing should break. Please provide an example if this is not true.
2. Search targetType in the converter, in this place _\*Converter implements ValueConverter<\*, **targetType**>_ . So I just cached this search, but forgot to write `isAssignableFrom` instead of `equals`, this is my only mistake, as it seems to me. If I add `isAssignableFrom` instead of `equals` the same deterministic results as before

2022-05-11 12:17 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
> -    private boolean checkConverterByTargetType(ValueConverter<? extends Value, ?> converter, Class<?> targetClass) {
Rewrited to 
```java
return targetClassOfConverter.isAssignableFrom(targetClass);
```
Also I've tested this snapshot with cartridge-springdata and I haven't gotten any problems with it

2022-05-11 15:17 UTC, wey1and requested changes

2022-05-11 20:08 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/ConverterWrapper.java
> +class ConverterWrapper<C extends Converter> implements Serializable {
Fixed

2022-05-12 13:28 UTC, wey1and approved these changes

2022-05-19 10:12 UTC, vrogach2020 approved these changes

2022-05-19 10:13 UTC, merged