Add uuid tests
tarantool/cartridge-java pull request #229
Opened 2022-05-25 09:56 UTC by ArtDu

What has been done? Why? What problem is being solved?

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Close #???

2022-06-02 16:20 UTC, ArtDu commented on src/test/resources/org/testcontainers/containers/server.lua
> +if _TARANTOOL > "2.4.1" then
Doesn't work with "2.10"

2022-06-03 13:21 UTC, ArtDu commented on src/test/resources/org/testcontainers/containers/server.lua
> +if _TARANTOOL > "2.4.1" then
Fixed

2022-06-06 10:39 UTC, wey1and requested changes

2022-06-06 10:39 UTC, wey1and commented on src/test/java/io/tarantool/driver/TarantoolUtils.java
> +                java.lang.System.getenv("TARANTOOL_VERSION").compareTo(version) > 0;
Possible NPE

2022-06-06 14:10 UTC, ArtDu commented on src/test/java/io/tarantool/driver/TarantoolUtils.java
> +                java.lang.System.getenv("TARANTOOL_VERSION").compareTo(version) > 0;
Where exactly?

2022-06-06 14:11 UTC, ArtDu commented on src/test/java/io/tarantool/driver/TarantoolUtils.java
> +                java.lang.System.getenv("TARANTOOL_VERSION").compareTo(version) > 0;
Where exactly? We check that` java.lang.System.getenv("TARANTOOL_VERSION")` may be null in first condition

2022-06-07 08:44 UTC, ArtDu commented on src/test/java/io/tarantool/driver/TarantoolUtils.java
> +                java.lang.System.getenv("TARANTOOL_VERSION").compareTo(version) > 0;
Updated, please check new version

2022-06-07 12:08 UTC, merged