WIP: Refactoring
tarantool/cartridge-java pull request #237
Opened 2022-07-13 04:00 UTC by wey1and

What has been done? Why? What problem is being solved?

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Close #???

2022-07-17 18:47 UTC, akudiyar requested changes

2022-07-17 18:47 UTC, akudiyar commented on src/main/java/io/tarantool/driver/handlers/TarantoolResponseHandler.java
> -                            TarantoolOkResult okResult = new TarantoolOkResult(tarantoolResponse.getSyncId(),
Don't get why it was removed. Would you mind elaborating about?

2022-07-17 18:47 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/RequestFutureManagerImpl.java
> +public class RequestFutureManagerImpl implements RequestFutureManager {
nit: This change looks too academic. Do we really suppose to have many RequestFutureManager implementations?

2022-07-17 18:47 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/TarantoolConnectionFactory.java
> +    protected final TarantoolClientConfig config;
Why is this now visible for subclasses, is there a reason?

2022-07-27 09:52 UTC, bitgorbovsky commented on src/main/java/io/tarantool/driver/core/RequestFutureManagerImpl.java
> +public class RequestFutureManagerImpl implements RequestFutureManager {
Yes, it's being used in another project, for implementation similar module for managing request, but some additional possibilities

2022-07-27 09:57 UTC, bitgorbovsky commented on src/main/java/io/tarantool/driver/core/connection/TarantoolConnectionFactory.java
> +    protected final TarantoolClientConfig config;
The reason is usage these class fields in subclasses of this factory

2022-08-05 07:57 UTC, bitgorbovsky commented
Closed in favor of https://github.com/tarantool/cartridge-java/pull/243

2022-08-05 07:57 UTC, closed without merging