Add 'fields' parameter to ProxySpace v2
tarantool/cartridge-java pull request #263
Opened 2022-09-15 18:34 UTC by ArtDu

What has been done? Why? What problem is being solved?

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Closes #???

2022-09-15 23:06 UTC, akudiyar requested changes
I liked it overall, but I believe that there's a better way. Please take a look at the comments below.

I think that `Options` should be much like the `Conditions` class, which is actually a builder and it is convenient to call a select method like `space.select(Conditions.any())`, for example. We should have something like that for `Options`. Of course, in this case, we'll have to tell the user if any actual options aren't supported by the particular client instance (in the same way as we do in Conditions). Serialization of `Options` instances will happen internally, no need to force users to use additional builder instances and call `build()`, that's ugly. But the difference will be that we can have different `Options` classes for each operation.  So for `select` it will be `SelectOptions`, for `insertMany` it will be `InsertManyOptions` etc.

An example of how the `Options` class can be used: 
```java
    space.select(
        Conditions.any(),
        SelectOptions.withTimeout(100500).withBatchSize(1000).withFields(Arrays.asList("id"))
    )
```
Here `SelectOptions` inherit some base class that provides `withTimeout` and `withFields` methods.

P.S. I think we further will replace the single `Conditions` class in the methods where it is passed with a hierarchy, like `PrimaryIndexConditions` (or just `PrimaryIndex`) for the methods that support only it and full `Conditions` (or `IndexConditions`?) for `select`.

2022-09-15 23:06 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolSpaceIT.java
> +public class ProxyTarantoolSpaceIT extends SharedCartridgeContainer {
Why do we have a new test class?

2022-09-16 12:23 UTC, ArtDu commented
> An example of how the `Options` class can be used:
> 
> ```java
>     space.select(
>         Conditions.any(),
>         SelectOptions.withTimeout(100500).withBatchSize(1000).withFields(Arrays.asList("id"))
>     )
> ```
> 
> Here `SelectOptions` inherit some base class that provides `withTimeout` and `withFields` methods.

I see only one way how to implement this, we should have all abstract classes except leaf in inheritance hierarchy. Leaf implement `self` and also we should have one entrypoint in leaf, something like `create`. 

```java
SelectOptions.create().withTimeout(100500).withBatchSize(1000).withFields(Arrays.asList("id"))
```

2022-09-19 21:31 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/proxy/CRUDBaseOptions.java
> +        public T withOptions(Options options) {
In merged PR `withTimeout` is using as default parameter(to pass config.timeout) and `withOptions -> timeout` as custom timeout

2022-09-19 21:35 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/proxy/CRUDFunctionOptions.java
> +class CRUDFunctionOptions extends CRUDBaseOptions {
In merged [PR](https://github.com/tarantool/cartridge-java/pull/267) we've discussed to name `CRUDReturnOptions`

2022-09-19 21:36 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/space/ProxyTarantoolSpace.java
> +                                                .withClient(client)
Fixed in merged [PR](https://github.com/tarantool/cartridge-java/pull/267)

2022-09-19 21:37 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/space/options/Options.java
> +public class Options {
Fixed in merged [PR](https://github.com/tarantool/cartridge-java/pull/267)

2022-09-19 21:39 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolSpaceIT.java
> +public class ProxyTarantoolSpaceIT extends SharedCartridgeContainer {
Added some classes in merged [PR](https://github.com/tarantool/cartridge-java/pull/267). I did this because the main class `ProxyAPI` is overloaded with many testcases, I wanted more precision test classes

2022-09-20 18:44 UTC, akudiyar requested changes
Almost good, the questions are mostly about the docstrings.

2022-09-20 18:44 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/OperationWithFieldsOptions.java
> +     * @return timeout, in milliseconds.
Not timeout, fields

2022-09-20 18:44 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/OperationWithFieldsOptions.java
> +     * Return list of fields.
It would be better to have a more full description (what is this list for?)

2022-09-20 18:44 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyReturnOptions.java
> +    /** TODO:
Doc TODO?

2022-09-20 18:44 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyReturnOptions.java
> +    public Optional<List> getFields() {
I think we need `List<String>` here

2022-09-20 18:44 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/proxy/CRUDBatchOptions.java
> +    <O extends CRUDBatchOptions, B extends AbstractBuilder<O, B>>
`CRUDBatchOptions` is a final class, we don't need a generic for Options here

2022-09-20 18:44 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/proxy/CRUDReturnOptions.java
> + * Represent options for cluster proxy operations which returns fields
Let's reformulate it. Something like `operations for that the set of fields returned in the result tuples can be specified`?

2022-09-20 18:44 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/proxy/CRUDSelectOptions.java
> +    private <O extends CRUDSelectOptions, B extends AbstractBuilder<O, B>>
THis class is final, the generic for `Options` is redundant.

2022-09-20 19:20 UTC, ArtDu commented
> Almost good, the questions are mostly about the docstrings.

Yeah, that is reason why I've converted PR to Draft

2022-09-20 22:02 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/proxy/CRUDBaseOptions.java
> +    CRUDBaseOptions(AbstractBuilder<O, B> builder) {
I guess this case should be excluded from checkstyle only one line, current format looks not readable

2022-09-20 22:03 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/proxy/CRUDBaseOptions.java
> +        extends CRUDAbstractOperationOptions.AbstractBuilder<O, B> {
I think. looks better
    protected abstract static class AbstractBuilder<O extends CRUDBaseOptions, B extends AbstractBuilder<O, B>> 
            extends CRUDAbstractOperationOptions.AbstractBuilder<O, B> {
        
        protected Optional<Integer> timeout = Optional.empty();

2022-09-20 22:07 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/proxy/CRUDBaseOptions.java
> -        public T withTimeout(Optional<Integer> timeout) {
Just question why? T looks more standard

2022-09-20 22:08 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/proxy/CRUDReturnOptions.java
> +
Remove space

2022-09-23 09:46 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/OperationWithFieldsOptions.java
> +     * @return timeout, in milliseconds.
Fixed

2022-09-23 09:47 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/proxy/CRUDFunctionOptions.java
> + * Represent options for cluster proxy operations which returns fields.
It has been rewritten

2022-09-23 10:54 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/TarantoolSpaceOperations.java
> +     * @param conditions specified conditions
Fixed

2022-09-23 11:03 UTC, Elishtar commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyReturnOptions.java
> +    public Optional<List> getFields() {
Why we can't? Looks like we can change method interface methods signature

2022-09-23 11:05 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/proxy/CRUDBaseOptions.java
> -        public T withTimeout(Optional<Integer> timeout) {
Okay, I agree

2022-09-23 11:06 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyReturnOptions.java
> +    public Optional<List> getFields() {
Yeah we can change method signature, but in the inner implementation we need to do a hack to cast to `List<String>.class`

2022-09-23 11:09 UTC, Elishtar submitted a review, later dismissed

2022-09-23 15:09 UTC, ArtDu commented
We have one problem with our approach we can't have multiple inheritances in java and especially in our ProxyOptions.
For example, we have InsertOptions and CountOption, both have batch_id option, but only InsertOption has fields option
<img width="635" alt="image" src="https://user-images.githubusercontent.com/22258443/191993065-83da7c01-d4a6-4bc5-b6b1-ccbffb5de8ad.png">

2022-09-26 12:28 UTC, ArtDu commented
Blocked by #272 because driver should parse metadata from crud. We can't get field by field name if we don't know position and It will frustrate users 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/22258443/192274750-a0aeb262-95b2-4af2-8c71-383ca034380c.png">

2022-12-22 09:17 UTC, merged