Add Options parameter to Space operations
tarantool/cartridge-java pull request #267
Opened 2022-09-17 22:24 UTC by ArtDu

Now we can add all options from crud to our Space API.

I didn't forget about:

- [x] Tests
- [x] Changelog
- [ ] Documentation
- [x] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Closes #266

2022-09-18 01:50 UTC, akudiyar requested changes
Cool, really like it, just two moments:
 - Let's move the Options classes (all package) to the `api` package. It is a part of the user-facing API.
 - Each `TarantoolSpaceOperations` method must have it's own derived `Options` class. So, for example, `delete` takes a `DeleteOptions` instance. Otherwise, our users will be able to put a wrong options instance into a method and become confused.

2022-09-18 01:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/space/options/package-info.java
> +package io.tarantool.driver.core.space.options;
We need to move the whole this package to `io.tarantool.driver.api.space.options` because these classes will be used by the customers and we will have to maintain the backward compatibility for them, as for all the other classes in the `api` package.

2022-09-19 09:02 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/space/options/package-info.java
> +package io.tarantool.driver.core.space.options;
Moved

2022-09-19 17:11 UTC, Elishtar commented
Looks good, optionally maybe should add a little bit logging for operations, like "Client <client name> run operation <operation type>"

2022-09-19 17:12 UTC, Elishtar approved these changes

2022-09-19 20:40 UTC, ArtDu commented
> Looks good, optionally maybe should add a little bit logging for operations, like "Client run operation "

A log slows down request and I don't see an option why I need to know that client is going to tarantool. If client wanted it, it would add an additional log before the call operation

2022-09-19 20:46 UTC, merged