Update pull_request_template.md
tarantool/cartridge-java pull request #269
Opened 2022-09-20 09:37 UTC by ArtDu

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2022-09-20 12:02 UTC, dkasimovskiy approved these changes

2022-09-20 18:46 UTC, akudiyar requested changes

2022-09-20 18:46 UTC, akudiyar commented on .github/pull_request_template.md
> +<!-- What has been done? Why? What problem is being solved? -->
Why do we have these comments? They will not render.

2022-10-04 04:16 UTC, akudiyar approved these changes

2022-10-04 07:45 UTC, merged