Add bucket id option to ProxySpace
tarantool/cartridge-java pull request #271
Opened 2022-09-23 21:57 UTC by ArtDu

What has been done? Why? What problem is being solved?

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Closes #270

2022-09-26 20:26 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * @param bucketId list of string field names
I've forgotten to change this line

2022-09-26 20:39 UTC, akudiyar requested changes
Overall LGTM, let's just fix the javadocs for the new option.

2022-09-26 20:39 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * You can use your own implementation of sharding function, but you don't forget about the number of buckets,
```suggestion
     * You can use your own implementation of the sharding function. For retrieving the number of buckets,
```

2022-09-26 20:39 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * By default, crud extracts a priority key from a tuple, processes it through strcrc32 hash function
```suggestion
     * By default, crud extracts primary key from a tuple and calculates an strcrc32 hash function value
```

`strcrc32` or `mpcrc32`? I doubt that the former one.

2022-09-26 20:39 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * and gets remainder after dividing by the number of buckets.
```suggestion
     * and gets the remainder after dividing the value by the number of buckets.
```

2022-09-26 20:39 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * that you can get by {@code vshard.router.bucket_count} method.
```suggestion
     * the {@code vshard.router.bucket_count} API method can be used.
```

2022-09-26 20:39 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * @param bucketId list of string field names
```suggestion
     * @param bucketId target operation bucket ID
```

2022-09-26 20:39 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * @see <a href="https://github.com/tarantool/vshard">vshard</a>
```suggestion
     * @see <a href="https://github.com/tarantool/vshard#sharding-architecture">vshard</a>
```

2022-09-26 20:39 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * Specifies bucket id for operation to perform it on storage with this bucket.
```suggestion
     * Specifies bucket id for an operation to perform it on storage with this bucket. It may be useful
     * if a non-default sharding function is used or in other specific cases.
```

2022-09-27 12:42 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * By default, crud extracts a priority key from a tuple, processes it through strcrc32 hash function
Still strcrc32 https://github.com/tarantool/crud/blob/d6f7666289321e7b14304d9928dad21ff687cf92/crud/common/sharding/init.lua#L45

2022-09-27 12:56 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * @param bucketId list of string field names
Fixed

2022-09-27 12:56 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * You can use your own implementation of sharding function, but you don't forget about the number of buckets,
Fixed

2022-09-27 12:56 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * By default, crud extracts a priority key from a tuple, processes it through strcrc32 hash function
Fixed

2022-09-27 12:56 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * and gets remainder after dividing by the number of buckets.
Fixed

2022-09-27 12:56 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * that you can get by {@code vshard.router.bucket_count} method.
Fixed

2022-09-27 12:56 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * @param bucketId list of string field names
Fixed

2022-09-27 12:56 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * @see <a href="https://github.com/tarantool/vshard">vshard</a>
Fixed

2022-09-27 12:57 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyBucketIdOptions.java
> +     * Specifies bucket id for operation to perform it on storage with this bucket.
Fixed

2022-09-27 21:20 UTC, akudiyar approved these changes
LGTM

2022-09-27 21:21 UTC, merged