Add tests how to calculate bucketId on client
tarantool/cartridge-java pull request #274
Opened 2022-09-29 18:07 UTC by ArtDu

What has been done? Why? What problem is being solved?

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Closes #???

2022-09-30 12:20 UTC, ArtDu commented
@akudiyar @Elishtar 

@dkasimovskiy suggests to export this implementation in source. What do you think about it?

2022-10-02 23:08 UTC, akudiyar commented
I think a good solution will be to describe how to create and use your own sharding function with the help of vshard API calls in the README. And leave the sample code in tests how they are now.

2022-10-05 19:41 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/Utils.java
> +    private static long crc32(byte[] data) {
If this function was borrowed from any public place, it is a good manner to reference the source.

2022-10-06 19:42 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/Utils.java
> +    private static long crc32(byte[] data) {
Added

2022-10-06 19:42 UTC, ArtDu commented
> I think a good solution will be to describe how to create and use your own sharding function with the help of vshard API calls in the README. And leave the sample code in the tests how it is now.

Added, please validate it

2022-10-17 09:09 UTC, akudiyar requested changes
LGTM,just two points here:
 - an example of converting a tuple to bytes will be useful
 - fixed the grammar a bit

2022-10-17 09:09 UTC, akudiyar commented on README.md
> +       return bucketCount.get();
I think we need to handle an unexpected `null` value better, like with an `orElseThrow` callback

2022-10-17 09:09 UTC, akudiyar commented on README.md
> +byte[] key = ... // can be multipart
It's not clear now what to put in the key. An example with a tuple will be better

2022-10-17 09:09 UTC, akudiyar commented on README.md
> +You can see sources of example in [tests](src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceInsertOptionsIT.java)
```suggestion
You can see the sources of this example in the [tests](src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceInsertOptionsIT.java)
```

2022-10-28 15:08 UTC, ArtDu commented on README.md
> +byte[] key = ... // can be multipart
Rewritten, please check it out

2022-10-28 15:08 UTC, ArtDu commented on README.md
> +       return bucketCount.get();
Rewritten, please check it out

2022-11-09 07:59 UTC, akudiyar approved these changes
LGTM

2022-11-09 08:10 UTC, merged

2022-11-09 16:20 UTC, akudiyar requested changes
Two small changes are needed

2022-11-09 16:20 UTC, akudiyar commented on README.md
> +       bucketCount.orElseThrow(() -> new TarantoolClientException("Failed to get bucket count"));
`return` is missing

2022-11-09 16:20 UTC, akudiyar commented on README.md
> +byte[] key = getBytesFromList(Arrays.asList(tarantoolTuple.getInteger(0), tarantoolTuple.getInteger(2)));
It may be good to place a link to this `getBytesFromList` method in the tests to the comment above, because it is not a built-in and therefore produces questions