Changes for TarantoolNullField class to singleton
tarantool/cartridge-java pull request #275
Opened 2022-10-02 09:17 UTC by devrishal

What has been done? Why? What problem is being solved?
The `TarantoolNullField `class was not singleton and its only task it to provide functionality similar to `Optional.Empty()`.
Changes done to make `TarantoolNullField `behaves same as `Optional.Empty()`.

I didn't forget about

- [ X] Tests
- [X] Changelog
- [X ] Documentation
- [X ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Closes #195

2022-10-02 19:54 UTC, akudiyar requested changes
Hi! Thanks for the patch!

I have a couple of questions:

1. I suggest using `create()` as the factory method name. With the `Optional` class we can create instances containing either null or non-null values, but with this class, there is only one possible internal value. So the name `empty()` can imply that something "non-empty" exists too, while `create()` can not.
2. Please fix the incorrect whitespace and run `mvn verify` to fix the other style warnings. 

UPD: discussed the change internally with team, I see that this change may be useful.

2022-10-03 14:32 UTC, devrishal commented
@akudiyar Modified the code as per the review comments and also changed for checkstyle.

2022-10-03 20:50 UTC, ArtDu approved these changes
LGTM

2022-10-03 20:54 UTC, ArtDu commented
@devrisha I forgot about changelog, can you write one line about changes in CHANGELOG.md?

2022-10-03 20:55 UTC, devrishal commented
> @devrisha I forgot about changelog, can you write one line about changes in CHANGELOG.md?

Yes will do now.

2022-10-03 21:03 UTC, ArtDu commented on CHANGELOG.md
> +- Changed TarantoolNullField class to singleton
But you must rebase, because we updated changelog today

2022-10-03 21:12 UTC, devrishal commented on CHANGELOG.md
> +- Changed TarantoolNullField class to singleton
Please check , did a rebase with the latest changes.

2022-10-04 09:02 UTC, dkasimovskiy requested changes

2022-10-04 09:25 UTC, Elishtar commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolNullField.java
> +    private static final TarantoolNullField EMPTY = new TarantoolNullField(null);
I suppose we need chose one from two strategy
Not lazy initialization
`public static final TarantoolNullField EMPTY = new TarantoolNullField(null);`
or
lazy initialization
```
private static TarantoolNullField empty;

public static TarantoolNullField create() {
       if (empty == null) 
        empty = new TarantoolNullField(null);;
    }
    
   return empty
}
```

2022-10-04 11:47 UTC, devrishal commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolNullField.java
> +    private static final TarantoolNullField EMPTY = new TarantoolNullField(null);
@Elishtar Its already` static final ` and will be immediately instance is assigned to it. The `TarantoolNullField ` is already a final and immutable class. Not sure if you are considering the Thread safety or in any other sense? But to answer the Thread safety the above points can be considered.

2022-10-04 11:48 UTC, devrishal commented on CHANGELOG.md
> +- Changed TarantoolNullField class to singleton ([#195](https://github.com/tarantool/cartridge-java/pull/275))
Added new line as per suggestion.

2022-10-04 12:50 UTC, Elishtar commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolNullField.java
> +    private static final TarantoolNullField EMPTY = new TarantoolNullField(null);
@devrishal if you already initialize  EMPTY, not necessarily use method create for access just change privat to public for EMPTY, if you want use method create. for access you can initialize EMPTY at the moment of first access please chose one strategy, now you use combination

2022-10-04 13:17 UTC, dkasimovskiy approved these changes

2022-10-04 14:23 UTC, devrishal commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolNullField.java
> +    private static final TarantoolNullField EMPTY = new TarantoolNullField(null);
Please let me know if this is fine for you ```
private static final TarantoolNullField EMPTY = new TarantoolNullField();
    private TarantoolNullField() {
    }

    public static TarantoolNullField create() {
        return EMPTY;
    }
```

2022-10-04 16:55 UTC, akudiyar approved these changes
LGTM.

I agree that lazy init is not needed here, it gives no advantages.

2022-10-04 17:45 UTC, akudiyar commented
@devrishal apologies for making that many comments for a simple change, but what do you think about dropping the `create()` method at all and leaving just the public constant? It looks like the method is redundant here since it always returns the constant.
Also, a classic name for such a singleton constant is usually `INSTANCE`.

2022-10-04 19:53 UTC, devrishal commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolNullField.java
> +    private static final TarantoolNullField EMPTY = new TarantoolNullField(null);
@akudiyar @Elishtar Please check and let me know if the changes looks good.

2022-10-04 20:04 UTC, devrishal commented
> @devrishal apologies for making that many comments for a simple change, but what do you think about dropping the `create()` method at all and leaving just the public constant? It looks like the method is redundant here since it always returns the constant. Also, a classic name for such a singleton constant is usually `INSTANCE`.

No Issues, It is indeed a good learning for me :) . Please let me know if the changes are fine now.

2022-10-04 20:04 UTC, devrishal commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolNullField.java
> +    private static final TarantoolNullField EMPTY = new TarantoolNullField(null);
Please check if the changes looks good?

2022-10-05 08:20 UTC, Elishtar approved these changes

2022-10-05 08:48 UTC, merged