Add parsing metadata from crud response
tarantool/cartridge-java pull request #278
Opened 2022-10-03 15:47 UTC by ArtDu

We didn't parse metadata from crud response and it's a big problem if we want to change metadata by fields(#236) parameter or custom logic.

I didn't forget about:

- [x] Tests
- [ ] Changelog
- [ ] Documentation
- [x] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Closes #272

2022-10-04 09:05 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/TarantoolResultImpl.java
> +        if (!metadata.isArrayValue()) {
Looks like potential NullPointerException, I guess will be good idea add fast fail if metadata is null

2022-10-04 09:09 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/TarantoolResultImpl.java
> +                        "Unsupported space metadata format: key '" + FORMAT_NAME_KEY + "' must have string value");
add current value to exception log

2022-10-04 09:09 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/TarantoolResultImpl.java
> +                        "Unsupported space metadata format: key '" + FORMAT_TYPE_KEY + "' must have string value");
The same

2022-10-11 20:23 UTC, ArtDu commented
The main problem is that now we have two converters used to parse incoming tuples:
The first level parses the top level - container - List of tuples or crud response.
The second level parses one tuple at a time.

The second level always needs to know the metadata, because it creates a TarantoolTuple and passes it there. Right now it only gets the metadata from the constructor.
The conclusion is the level that parses a particular tuple must know the metadata from the level above, if it is crudResponse.

So I see 3 options:
1) Create a new fromValue method, into which we can pass custom metadata, as I did in PR - minus that we add a method to the API, although the method is not giant terrible)
2) Combine the first and second levels - consider combining two converters into one - minus, that everything is in one place parsing the container and the tuples themselves
3) Create a converter for each request of the second level - minus the memory will be painfull grown

2022-10-13 19:07 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/TarantoolResultImpl.java
> +                        "Unsupported space metadata format: key '" + FORMAT_NAME_KEY + "' must have string value");
Fixed

2022-10-17 14:03 UTC, akudiyar commented
I think the new converter variant (3) is the because it doesn't allow to leak the implementation details through interfaces and leaves in place the ability to have different result mappers (e.g. for libs other than Tarantool/crud or non-tuple results).

The converter instantiation is a parallel problem and should be dealt with as a whole, not in this particular place.

2022-10-17 21:13 UTC, akudiyar requested changes
It's a better idea overall then changing the ValueConverter interface, however the changes look very rough. I'd rather not copy-paste the whole converters code in that way. Also It may be worth thinking about passing a tuple converter factory to the result converter instead of a tuple converter, that will help eliminating the fromValue method and unnecessary casts.

2022-10-17 21:13 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/MultiValueTarantoolResultMapperFactory.java
> +        return withMultiValueResultConverter((ValueConverter) new TarantoolTupleResultConverter<>(valueConverter),
Don't understand why a cast is needed here. Probably the class needs more proper generics definition or something.

2022-10-17 21:13 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/TarantoolTupleMultiResultMapperFactory.java
> +        return withTarantoolTupleResultConverter(
Isn't this change breaking the plain box client?

2022-10-17 21:13 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/TarantoolResultImpl.java
> +                .map(v -> {
nit: Please set up 4 spaces as continuation identation in Idea/whatever. These unrelated space changes distract a lot.

2022-10-27 11:12 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/TarantoolResultImpl.java
> +                    try {
I guess will be better extract try/catch to method

2022-10-27 11:17 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/TarantoolTupleResultImpl.java
> +        if (value.isArrayValue()) {
Let's try to replace multiple if/else to case for example like this
https://stackoverflow.com/questions/5579309/is-it-possible-to-use-the-instanceof-operator-in-a-switch-statement

2022-10-27 11:23 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/TarantoolTupleResultImpl.java
> +            if (!value.isMapValue()) {
Case maybe?

2022-10-27 11:24 UTC, Elishtar commented on src/main/java/io/tarantool/driver/core/TarantoolTupleResultImpl.java
> +                    try {
Maybe extract

2022-10-27 11:30 UTC, Elishtar commented on src/main/java/io/tarantool/driver/mappers/converters/value/custom/TarantoolTupleResultConverter.java
> +    private static final long serialVersionUID = 20200708L;
Auto generate?

2022-12-12 14:33 UTC, akudiyar requested changes

2022-12-12 14:33 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/parsers/CRUDResponseMetadataParser.java
> +public class CRUDResponseMetadataParser implements SpaceMetadataParser {
What's the purpose of this class? Currently it looks like doing nothing.

2022-12-12 14:33 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/parsers/DDLSpaceMetadataParser.java
> +public class DDLSpaceMetadataParser implements SpaceMetadataParser {
This class needs some unit tests and a Javadoc.

2022-12-12 14:33 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/parsers/SpaceMetadataParser.java
> +public interface SpaceMetadataParser {
This class needs some unit tests and a javadoc.

2022-12-12 14:33 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/parsers/DDLSpaceMetadataParser.java
> +    public TarantoolSpaceMetadataImpl parse(Value metadata) {
Shouldn't it take `MapValue` explicitly?

2022-12-12 14:33 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/parsers/VSpaceMetadataParser.java
> +public class VSpaceMetadataParser implements SpaceMetadataParser {
This class needs unit tests and a Javadoc.

2022-12-13 10:51 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/metadata/parsers/DDLSpaceMetadataParser.java
> +    public TarantoolSpaceMetadataImpl parse(Value metadata) {
If we want to have one interface for metadata parsing we need to use `Value`. Metadata can be stored in different structures

2022-12-13 12:25 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/metadata/parsers/CRUDResponseMetadataParser.java
> +public class CRUDResponseMetadataParser implements SpaceMetadataParser {
I changed classes. You should check

2022-12-13 12:25 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/metadata/parsers/SpaceMetadataParser.java
> +public interface SpaceMetadataParser {
Fixed

2022-12-13 12:25 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/metadata/parsers/DDLSpaceMetadataParser.java
> +    public TarantoolSpaceMetadataImpl parse(Value metadata) {
I changed it

2022-12-13 12:25 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/metadata/parsers/VSpaceMetadataParser.java
> +public class VSpaceMetadataParser implements SpaceMetadataParser {
Fixed

2022-12-13 12:36 UTC, ArtDu commented
We can split PR to "Parse metadata from crud response" 3252ba6cd60b0e09661c378263eeac65f7799109 and "Refactor metadata parsing". But I prefer to merge "Parse metadata from crud response" 3252ba6cd60b0e09661c378263eeac65f7799109 for first

2022-12-13 22:45 UTC, akudiyar requested changes
Interestingly, that looks pretty OK without all other changes, one question is left though

2022-12-13 22:45 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/TarantoolFieldMetadataImpl.java
> +public class TarantoolFieldMetadataImpl implements TarantoolFieldMetadata {
Do we really need to make it public? It's an internal implementation class.

2022-12-14 09:28 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/metadata/TarantoolFieldMetadataImpl.java
> +public class TarantoolFieldMetadataImpl implements TarantoolFieldMetadata {
There are two options here:
* We store these converters(parsers in future) in `*.core.metadata` package
* Or we open this class and store classes where they should be semantically

2022-12-14 12:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/metadata/TarantoolFieldMetadataImpl.java
> +public class TarantoolFieldMetadataImpl implements TarantoolFieldMetadata {
First option has been picked up

2022-12-14 13:00 UTC, akudiyar approved these changes
LGTM

2022-12-14 13:01 UTC, merged