Update quickstart in readme
tarantool/cartridge-java pull request #289
Opened 2022-10-19 15:33 UTC by iDneprov

Updated quickstart section im readme according to your new documentation policy

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Part of #288

2022-10-20 08:04 UTC, iDneprov commented
The links in the documentation may not work, because I made them for the master branch and it does not yet have an example for a single instance

2022-10-20 08:14 UTC, iDneprov commented on README.md
> +2. At [SingleInstanceExampleTest](https://github.com/tarantool/cartridge-java/blob/master/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java).
To make it easier to look, I will add links to this repository
https://github.com/tarantool/cartridge-java/blob/new-readme/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java

2022-10-20 08:16 UTC, iDneprov commented on README.md
> +https://github.com/tarantool/cartridge-java/blob/master/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java#L59-L67
https://github.com/tarantool/cartridge-java/blob/new-readme/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java#L59-L68

2022-10-20 08:17 UTC, iDneprov commented on README.md
> +https://github.com/tarantool/cartridge-java/blob/master/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java#L71-L87
https://github.com/tarantool/cartridge-java/blob/new-readme/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java#L71-L87

2022-10-20 08:17 UTC, iDneprov commented on README.md
> +All java code located at [SingleInstanceExampleTest](https://github.com/tarantool/cartridge-java/blob/master/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java)
https://github.com/tarantool/cartridge-java/blob/new-readme/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java

2022-10-20 09:48 UTC, ArtDu requested changes
We don't need cartridge for simplest example, we just need single tarantool node and TarantoolContainer for it without cartridge and cluster stuff

2022-10-20 09:48 UTC, ArtDu commented on src/test/resources/single-instance-example/instances.yml
> +  http_port: 8081
new line before EOF

2022-10-20 09:48 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java
> +        container.executeCommand("return require('migrator').up()").get();
We need comment for this line too, e.g. "Up migrations from directory migrations via iproto call". And probably you don't need `return` in command

2022-10-20 09:48 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java
> +            client.eval("return 1");
Delete it

2022-10-20 09:48 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java
> +            List<Object> values = Arrays.asList(77, "Moscow");
Make it inline, put it in create call below

2022-10-20 09:48 UTC, ArtDu commented on README.md
> +3. Set breakpoint at line 85.
I don't think we need words about breakpoints. For mature developer it'll be obviously. May be we'll simplify it to "Just run the test and do expirement with it". And below we can describe what's happening in that test -  testcontainer with tarantool and migrations things

2022-10-20 09:48 UTC, ArtDu commented on README.md
> +2. At [SingleInstanceExampleTest](https://github.com/tarantool/cartridge-java/blob/master/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java).
You can add branch links now and before merge replace them

2022-10-20 10:36 UTC, iDneprov commented on README.md
> +3. Set breakpoint at line 85.
I thing that we should discuss it with other reviewers. And I agree that the current description looks redundant.

2022-10-20 13:54 UTC, iDneprov commented on README.md
> +https://github.com/tarantool/cartridge-java/blob/61e300c70a44157f7ddccb7b8692f02eced99a04/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java#L72-L88
Github permalink works quite strange. They get code from of a particular commit. And sometimes not transformed into a block of code. Maybe we should use something like [this](https://github.com/marketplace/actions/markdown-embed-code-from-file)?

2022-10-20 14:15 UTC, bitgorbovsky commented on README.md
> +3. Set breakpoint at line 85.
It's better to not to mention about breakpoints especially with line numbers because they can be changed, even adding one line will break consistency between code and documentation, and it will be a quite awkward.

2022-10-20 14:26 UTC, bitgorbovsky requested changes

2022-10-20 14:26 UTC, bitgorbovsky commented on README.md
> +2. At [SingleInstanceExampleTest](https://github.com/tarantool/cartridge-java/blob/new-readme/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java).
Very strange introduction. At what?

2022-10-20 14:26 UTC, bitgorbovsky commented on README.md
> +Single instance Tarantool application from cartridge-java.
Don't mix words and concepts. `Single instance Tarantool application` is application written in lua, with or without some clustering tools and so on. Cartridge-Java - client library. And this sentence is very hard to understand - application from client library.

Please, rewrite it in more clean way.

Or remove this sentence.

2022-10-20 14:26 UTC, bitgorbovsky commented on README.md
> +5. Open "Evaluate Expression" window in your IDE. In IDEA you can do it by pressing `alt` `F8`.
It depends on configration of IDEA. Better: In typical IDEA setup

2022-10-20 14:26 UTC, bitgorbovsky commented on README.md
> +If you want to start cluster from terminal run this commands: install all needed dependencies
I thinks, it needs some restructuring: `If you want to start cluster from terminal run these commands:` and then on next lines show bash code.

2022-10-22 22:55 UTC, akudiyar commented
Hi guys, what do you think about placing this new Quickstart in a separate file, the project wiki, or even on the Tarantool site and giving a link to it in the README?
To me, it looks like the README eventually should be just a short static page about the project with all the necessary links to the user guides and function reference. I believe that the most important information in it is how to build, contribute and install the driver. The function reference and examples are better to be placed in the Javadoc, so to have them up-to-date with the code changes, and the quickstart guides need to be in a searchable place like the Tarantool site or the wiki pages.

2022-11-25 08:11 UTC, ArtDu requested changes
Why did you close old PR and created new one?

2022-11-25 08:11 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java
> +        } catch (Error e) {
If you can remove it remove, do it. AFAIK try with resources doesn't require catch

2022-11-25 08:11 UTC, ArtDu commented on src/test/resources/single-instance.lua
> +box.schema.user.grant('api_user', 'read,write,execute', 'universe')
newline

2022-11-25 08:11 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java
> +            TarantoolTupleFactory tupleFactory = new DefaultTarantoolTupleFactory(mapperFactory.defaultComplexTypesMapper());
I think it could be more easily, but I'm not sure

2022-11-25 09:37 UTC, iDneprov commented on src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java
> +            TarantoolTupleFactory tupleFactory = new DefaultTarantoolTupleFactory(mapperFactory.defaultComplexTypesMapper());
Didn't find easier solution. If you have one, I'll be happy to use it there

2022-11-25 14:30 UTC, ArtDu requested changes

2022-11-25 14:30 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java
> +            TarantoolTupleFactory tupleFactory = new DefaultTarantoolTupleFactory(mapperFactory.defaultComplexTypesMapper());
Yeah, it's true we don't have easy and cool tupleFactory ((

2022-11-25 14:30 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java
> +            assertEquals(insertTuples.get(0).getObject(0), selectTuples.get(0).getObject(0));
Maybe we'll do something like that?
```suggestion
            TarantoolTuple insertTuple = insertTuples.get(0);
            TarantoolTuple selectTuple =  selectTuples.get(0);
            assertEquals(insertTuple.getInteger("id"), selectTuple.getInteger("id"));
```

2022-11-25 14:30 UTC, ArtDu commented on README.md
> +Warning: `TarantoolClientFactory.createClient()` does not work properly in IDEA "Evaluate Expression" window.
I think it's reduntant

2022-11-25 14:30 UTC, ArtDu commented on README.md
> +TODO change new-readme branch to master
I don't get it

2022-11-28 07:15 UTC, iDneprov commented on README.md
> +TODO change new-readme branch to master
I mean in peramalinks I'v added before merge I should change new-readme branch to master

2022-11-28 07:17 UTC, iDneprov commented on README.md
> +Warning: `TarantoolClientFactory.createClient()` does not work properly in IDEA "Evaluate Expression" window.
Just trying to save our users time

2022-11-28 08:00 UTC, ArtDu commented on README.md
> +TODO change new-readme branch to master
Oh, I see

2022-11-28 08:02 UTC, ArtDu commented on README.md
> +Warning: `TarantoolClientFactory.createClient()` does not work properly in IDEA "Evaluate Expression" window.
Maybe it'll work with their software

2022-11-28 08:03 UTC, ArtDu commented
Plz check CI before send review invites 
```log
[INFO] --- maven-checkstyle-plugin:3.1.1:check (check-style) @ cartridge-driver ---
[INFO] Starting audit...
Error:  /home/runner/work/cartridge-java/cartridge-java/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java:51: Line is longer than 1[20](https://github.com/tarantool/cartridge-java/actions/runs/3562552118/jobs/5984386231#step:6:21) characters (found 123). [LineLength]
Error:  /home/runner/work/cartridge-java/cartridge-java/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java:63: Line is longer than 120 characters (found 125). [LineLength]
Error:  /home/runner/work/cartridge-java/cartridge-java/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java:64: Line is longer than 120 characters (found 1[23](https://github.com/tarantool/cartridge-java/actions/runs/3562552118/jobs/5984386231#step:6:24)). [LineLength]

```

2022-11-28 08:04 UTC, ArtDu requested changes
Plz check CI before send review invites 
```log
[INFO] --- maven-checkstyle-plugin:3.1.1:check (check-style) @ cartridge-driver ---
[INFO] Starting audit...
Error:  /home/runner/work/cartridge-java/cartridge-java/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java:51: Line is longer than 1[20](https://github.com/tarantool/cartridge-java/actions/runs/3562552118/jobs/5984386231#step:6:21) characters (found 123). [LineLength]
Error:  /home/runner/work/cartridge-java/cartridge-java/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java:63: Line is longer than 120 characters (found 125). [LineLength]
Error:  /home/runner/work/cartridge-java/cartridge-java/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java:64: Line is longer than 120 characters (found 1[23](https://github.com/tarantool/cartridge-java/actions/runs/3562552118/jobs/5984386231#step:6:24)). [LineLength]

```

2022-11-28 08:48 UTC, iDneprov commented
> Plz check CI before send review invites
> 
> ```
> [INFO] --- maven-checkstyle-plugin:3.1.1:check (check-style) @ cartridge-driver ---
> [INFO] Starting audit...
> Error:  /home/runner/work/cartridge-java/cartridge-java/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java:51: Line is longer than 1[20](https://github.com/tarantool/cartridge-java/actions/runs/3562552118/jobs/5984386231#step:6:21) characters (found 123). [LineLength]
> Error:  /home/runner/work/cartridge-java/cartridge-java/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java:63: Line is longer than 120 characters (found 125). [LineLength]
> Error:  /home/runner/work/cartridge-java/cartridge-java/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java:64: Line is longer than 120 characters (found 1[23](https://github.com/tarantool/cartridge-java/actions/runs/3562552118/jobs/5984386231#step:6:24)). [LineLength]
> ```

Fixed, thanks

2022-11-28 10:16 UTC, ArtDu requested changes

2022-11-28 10:16 UTC, ArtDu commented on README.md
> +in debug mode and set breakpoint.
In my opinion this looks better

```suggestion
The easiest way to start experimenting with cartridge-java and single instance tarantool app is to use
[single instance test](/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java). You can set breakpoints and run it in debug mode.
```

2022-11-28 10:23 UTC, iDneprov commented on README.md
> +in debug mode and set breakpoint.
Tank you for suggestion

2022-11-28 10:35 UTC, ArtDu approved these changes
I think we need at least two approves to merge PR

2022-11-28 10:41 UTC, ArtDu commented on README.md
> +https://github.com/tarantool/cartridge-java/blob/eb9aa772018690efa9b282fb000d8f8340bb06bb/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java#L62-L74
You can add link based on branch name instead of commit hash, like this
```
https://github.com/tarantool/cartridge-java/blob/new-readme/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java#L61-L78
```

2022-11-28 11:17 UTC, iDneprov commented on README.md
> +https://github.com/tarantool/cartridge-java/blob/eb9aa772018690efa9b282fb000d8f8340bb06bb/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java#L62-L74
I'll update peramalinks before merge

2022-11-28 12:57 UTC, ArtDu commented on README.md
> +https://github.com/tarantool/cartridge-java/blob/eb9aa772018690efa9b282fb000d8f8340bb06bb/src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java#L62-L74
It's about now, we see old hash commit changes where we can see try-catch-resources, but you've deleted catch part

2022-11-28 15:00 UTC, merged