long array mapper
tarantool/cartridge-java pull request #290
Opened 2022-10-22 11:26 UTC by anatennis

WorkInProgress

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2022-10-22 22:38 UTC, akudiyar requested changes
Hi, thanks for the patch! Please add test and addresss the comments below.

2022-10-22 22:38 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapperFactory.java
> +                //TODO: add this when will it be resolved https://github.com/tarantool/cartridge-java/issues/118
Please rebase on the fresh master branch or remove these changes, this has been already changed.

2022-10-22 22:38 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapperFactory.java
> +import org.msgpack.value.*;
Please do not use the "star" import. In Intellij IDEA you can tick this option in the code autoformat settings.

2022-10-22 22:38 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/object/DefaultLongArrayToArrayValueConverter.java
> +        return ValueFactory.newArray(toNumberValue(object), true);
I think `toNumberValue` will not work like this. Since it is a method for a single value, not array.

2022-10-22 22:38 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/value/DefaultArrayValueToLongArrayConverter.java
> +        return value.list().stream().allMatch(Value::isNumberValue);
q: I believe `toLongValue` can be better here... But for saving time we may check only the first value (assuming that we have only the "correct" arrays on the Tarantool side). @ArtDu @Elishtar do you have any arguments for checking all array elements here?

2022-10-24 10:47 UTC, anatennis commented on src/main/java/io/tarantool/driver/mappers/converters/object/DefaultLongArrayToArrayValueConverter.java
> +        return ValueFactory.newArray(toNumberValue(object), true);
It's my method, so I've changed its name to toNumberValueArray

2022-10-24 10:56 UTC, anatennis commented on src/main/java/io/tarantool/driver/mappers/converters/value/DefaultArrayValueToLongArrayConverter.java
> +        return value.list().stream().allMatch(Value::isNumberValue);
Actually any number can be converted to long (int, short, double) - so my thoughts were like `asNumberValue` does the same check and it will suit for this case. Or not?
And also I have doubts about only one element checking. Because this array is also valid `arrayValue = ValueFactory.newArray(new ImmutableLongValueImpl(2L), new ImmutableStringValueImpl("string"), new ImmutableLongValueImpl(3L));` and if we'll check only 1st element - then `canConvertValue()` returns true but later `fromValue()` will throw `MessageTypeCastException`

2022-10-24 22:05 UTC, akudiyar requested changes
Looks better now, please add some test cases to the https://github.com/tarantool/cartridge-java/blob/master/src/test/java/io/tarantool/driver/mappers/DefaultMessagePackMapperTest.java test suite too. We need to check the correctness of convertation if a result tuple or a map contains different `ArrayValue` elements.

2022-10-24 22:05 UTC, akudiyar commented on src/test/java/io/tarantool/driver/mappers/DefaultLongArrayConverterTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Please fix the star import

2022-10-24 22:05 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/value/DefaultArrayValueToLongArrayConverter.java
> +            return value.list().stream().allMatch(Value::isNumberValue);
I suggest adding a test case for wrong value as well

2022-10-25 08:21 UTC, anatennis commented on src/main/java/io/tarantool/driver/mappers/converters/value/DefaultArrayValueToLongArrayConverter.java
> +            return value.list().stream().allMatch(Value::isNumberValue);
Ok, no problem, now it checks only 1st value. Test was already added but now it checks that `canConvertValue` returns true and `fromValue` throws Exception

2022-10-25 08:22 UTC, anatennis commented
Added also tests to DefaultMessagePackMapperTest

2022-10-25 22:17 UTC, akudiyar requested changes
Please run `mvn verify` and fix the linter warnings.

2022-10-25 22:17 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/object/DefaultLongArrayToArrayValueConverter.java
> +public class DefaultLongArrayToArrayValueConverter implements ObjectConverter<long[], ArrayValue> {
Looks like the `serialVersionUID` variable is missing here.

Please set its value to the current date.

2022-10-25 22:17 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/value/DefaultArrayValueToLongArrayConverter.java
> +public class DefaultArrayValueToLongArrayConverter implements ValueConverter<ArrayValue, long[]> {
Please add the `serialVersionUID` value here too

2022-10-25 22:20 UTC, akudiyar reviewed
Don't forget to add this change to CHANGELOG

2022-10-26 08:18 UTC, anatennis commented
fix 

> Please run `mvn verify` and fix the linter warnings.

done

2022-10-26 17:33 UTC, akudiyar approved these changes
LGTM, let's fix that one line in CHANGELOG if you have time.

2022-10-26 17:33 UTC, akudiyar commented on CHANGELOG.md
> +## [0.9.1] - 2022-10-26
nit: an extra line

2022-10-26 17:44 UTC, akudiyar approved these changes
LGTM

2022-10-26 17:53 UTC, merged