WIP-instant converter
tarantool/cartridge-java pull request #293
Opened 2022-10-25 12:33 UTC by anatennis

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2022-10-25 22:06 UTC, akudiyar requested changes
Thanks for the patch! LGTM, but there are a few more things not to forget about:

- Additional tests are needed with a version switch for `ConvertersWithClusterClientIT.java` and  `ConvertersWithProxyClientIT.java` test suites
- We need to add a CI pipeline for Tarantool 2.10 for these tests

2022-10-25 22:18 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/value/DefaultExtensionValueToInstantConverter.java
> +public class DefaultExtensionValueToInstantConverter implements ValueConverter<ExtensionValue, Instant> {
Please add `serialVersionUID` value here too

2022-10-26 09:42 UTC, anatennis commented
> Thanks for the patch! LGTM, but there are a few more things not to forget about:
> 
> * Additional tests are needed with a version switch for `ConvertersWithClusterClientIT.java` and  `ConvertersWithProxyClientIT.java` test suites
> * We need to add a CI pipeline with Tarantool 2.10 for these tests

added

2022-10-26 09:43 UTC, anatennis commented on src/main/java/io/tarantool/driver/mappers/converters/object/DefaultInstantToExtensionValueConverter.java
> +        ByteBuffer buffer = ByteBuffer.wrap(new byte[16]);
yes, 8 will be better

2022-10-26 17:41 UTC, akudiyar requested changes

2022-10-26 17:41 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ConvertersWithClusterClientIT.java
> +        client.space("space_with_instant")
Hmm, I don't see any changes in the Lua backend with this new space and also a CI pipeline with 2.10 for testing this. Would you mind adding them?

2023-04-02 17:41 UTC, ArtDu commented
Will be done in https://github.com/tarantool/cartridge-java/pull/376

2023-04-02 17:41 UTC, closed without merging