Refactor mappers and split TarantoolResultConverter
tarantool/cartridge-java pull request #300
Opened 2022-11-14 16:25 UTC by ArtDu

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2022-11-17 19:10 UTC, ArtDu commented
@akudiyar I need you to see concepts. I haven't finished with javadocs and refactoring, but you can give your opinion about structure and hierarchy

2022-11-18 23:41 UTC, akudiyar requested changes
@ArtDu Thanks for such detailed changes description, very much appreciated!
The PR is in a good shape, so let's remove some roughness and it's good to go.

General comments/questions:
- Please avoid mixing meaningful changes with re-indentation and renaming files next time. It makes things hard to review. Such changes need to be applied in atomic commits and better in separate PRs.
- I didn't like much the idea of renaming the container mappers and adding "s" to "tuple". See one of the comments below for more details.
- Would you mind elaborating a bit more about "converter without target type"? I understand the raw idea, but using an untyped generic interface tricks the compiler, so we need at least to use some workarounds or unspecified `Object` type generics like `ValueConverter<?, ?>` if we don't care about the result type.
- We need to put more documentation about the converters in the DefaultMapper and other classes. Especially we need to describe the workflow where each result mapper class is used in. This will ease understanding of this code if we will have to fix bugs here.

2022-11-18 23:41 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/MultiValueResultMapperFactory.java
> +        MessagePackValueMapper firstLayerValueMapper) {
Isn't this a container (== result) value mapper? "First layer" doesn't give any insight into the mapper's purpose.
However, we need to put a Javadoc to each new method here as well with an explanation of how they are supposed to be used. It wasn't done earlier and this class is hard to understand now.

2022-11-18 23:41 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * You can obtain data from list of tuples and/or tarantool/crud responses.
I believe that the previous description explained the target purpose of that function netter. Can we still include something on that matter?

2022-11-24 14:51 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolMultiTuplesResult.java
> + * @see TarantoolTuplesResult
Fixed

2022-11-24 15:04 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolSingleTuplesResult.java
> +public interface TarantoolSingleTuplesResult extends SingleValueCallResult<TarantoolResult<TarantoolTuple>> {
My logic was that we have TarantoolTupleResult stuff and we add on this stack SingleConverter. And we add some words, so we should have this SingleTarantoolTupleResult like we have a stack from the top to bottom, but from the lef to the right. I don't know why I added Tarantool to begin of name

In general, I propose this name `SingleTarantoolTupleResult`

2022-11-24 15:31 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/MultiValueCallResultImpl.java
> +    public MultiValueCallResultImpl(Value result, MessagePackValueMapper valueMapper) {
We need it when we pass only one converter to parsing. We parse callForMultiResult with one converter on the top of stack

2022-11-24 15:32 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java
> +    public SingleValueCallResultImpl(ArrayValue result, MessagePackValueMapper valueMapper) {
We need it when we pass only one converter to parsing. For example, we parse callForSingleiResult with one converter on the top of stack

2022-11-24 15:55 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/converters/value/custom/DefaultArrayValueToTarantoolResultConverter.java
> +    private static final long serialVersionUID = -1348387430063097175L;
There is a problem we can change the file, but forget to change VersionUID

2022-11-24 16:25 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/converters/value/custom/SimpleSingleValueCallResultConverter.java
> +    public SimpleSingleValueCallResultConverter(ValueConverter<Value, T> valueConverter) {
We can't use `? extends Value`
<img width="437" alt="image" src="https://user-images.githubusercontent.com/22258443/203830549-6b43bc8a-21c4-42ce-a561-c8adec8bb6df.png">

2022-11-25 14:39 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolSingleTuplesResult.java
> +public interface TarantoolSingleTuplesResult extends SingleValueCallResult<TarantoolResult<TarantoolTuple>> {
> My logic was that we have TarantoolTupleResult stuff and we add on this stack SingleConverter. And we add some words, so we should have this SingleTarantoolTupleResult like we have a stack from the top to bottom, but from the lef to the right. I don't know why I added Tarantool to begin of name
> 
> In general, I propose this name `SingleTarantoolTupleResult`

I changed my mind, SingleTarantoolTupleResult looks like we have single tuple and it's more confusing

2022-11-25 16:06 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/TarantoolResult.java
> + * It can be multiple return results from lua, tuple from box or other things
But to be true it's not about the list, it's about storage of fields. But fields from Tarantool can be encoded in Map, like we have in crud response

2022-11-28 08:11 UTC, ArtDu commented
@akudiyar Maybe we should add new interface with simple use of mappers above the factories in another PR. Cause it's so hard to use them now
```java
List<?> result = client.call("f",
            client.getResultMapperFactoryFactory().customStructureResultMapperFactory().withArrayValueToTarantoolResultConverter(
                (list) -> {
                    return list.get(0).asStringValue();
                }
            )).join();
```

2022-11-28 14:47 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * You can obtain data from list of tuples and/or tarantool/crud responses.
Yes, I will rewrite the documents when we agree on the structures of the mappers

2022-11-28 14:49 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/MultiValueResultMapperFactory.java
> +        MessagePackValueMapper firstLayerValueMapper) {
Renamed to `structureValueMapper`

2022-11-28 21:59 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/value/custom/SimpleSingleValueCallResultConverter.java
> +    public SimpleSingleValueCallResultConverter(ValueConverter<Value, T> valueConverter) {
If we leave `Value` here, it will prevent us from passing a `ValueConverter<ArrayValue, List<String>>` for example. That can cause some trouble in the derived libraries because that's how the compiler works. The users will have to create a converter with a generic "Value" generic type, which means an "in-line" converter from a lambda function may not work sometimes or will require some dirty casts and excessive code. 

Let's look together at the code if you change this to a supertype generic. Maybe I will see some hints there.

2022-11-28 22:04 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolSingleTuplesResult.java
> +public interface TarantoolSingleTuplesResult extends SingleValueCallResult<TarantoolResult<TarantoolTuple>> {
The latter variants look more meaningful but still are too long. The nasty part with Java long names is that they greatly reduce readability when being re-idented with newlines.

2022-11-28 23:20 UTC, akudiyar requested changes
I generally still don't have any objections against this approach. Let's rebase to eliminate the visual noise and not forget to add the documentation. Also the code duplication in the mapper constructors is something that needs to be addresssed.

I've checked the changes with Spark connector and they seem to work, but there is no extensive usage of the mappers in there. The SpringData library has some tricky usage and must be checked before merging.

2022-11-28 23:27 UTC, akudiyar commented
> Maybe we should add new interface with simple use of mappers above the factories in another PR. Cause it's so hard to use them now

I like this idea, but that will not be as simple as you imagined it. I think a PoC in a new PR is worth trying to find a better interface form. I think it may be a kind of builder or a builder factory.

2022-12-02 10:26 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/converters/value/custom/SimpleSingleValueCallResultConverter.java
> +    public SimpleSingleValueCallResultConverter(ValueConverter<Value, T> valueConverter) {
This converter is used only in one place in `SingleValueCallResultImpl`. Because we expect any value in there we should use Value like it was before https://github.com/tarantool/cartridge-java/blob/master/src/main/java/io/tarantool/driver/mappers/converters/value/custom/SingleValueCallResultConverter.java . 

https://github.com/tarantool/cartridge-java/blob/339b5de2e9e0cba84a96560b5ad855dc15c3f307/src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java#L32 

https://github.com/tarantool/cartridge-java/blob/339b5de2e9e0cba84a96560b5ad855dc15c3f307/src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java#L16-L34

It'd work if we had generic method. But we have determined type and method require only this captured ? extends Value type

2022-12-02 10:40 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * You can obtain data from list of tuples and/or tarantool/crud responses.
I added description with abstract input/output

https://github.com/tarantool/cartridge-java/blob/cd10452cf8ac1d992ab3ad2f7a754e2db599ae72/src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java#L17-L148

2022-12-03 23:32 UTC, akudiyar reviewed
I fixed a bit the javadocs for ResultMapperFactoryFactory methods. Some other new files are 
 still lacking javadoc headers, so we need to check this carefully again.
 
 I have two concerns at the moment:
1. I'm strongly against using "custom" words in the names of the classes. Especially if such a class is fundamental for a subtree of classes actually used in the driver code. "Custom" should only be left for the examples and users' code, otherwise it will embarrass the readers as it implies that there are some "core" classes and these classes are "supplemental" to them.
2. We need to check every place where we are passing a mapper instance as an inner mapper so that it is an isolated shallow copy and we are not affecting the outer mapper (and more importantly, the default mapper from the settings) when building a mapper stack. I strongly advise writing some tests on this matter, since it is hard enough to check these relationships just with the eyes.

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * mapper result: converted {@code TarantoolResult<T>} from [x, y, z]
```suggestion
     * mapper result: {@code TarantoolResult<T>} converted from <code>[x, y, z, ...]</code>
```

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * Mapper result and its inner depends on the parameters or converters you passed.
```suggestion
     * Mapper result and its inner contents depend on the parameters or the passed converters.
```

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * @param <T> target inner result type
```suggestion
     * @param <T> target inner tuple type
```

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * Create a factory for mapping stored function call results to {@link MultiValueCallResult}
```suggestion
     * Create a factory for mapping stored Lua function multi-return call result to {@link MultiValueCallResult} with the custom result and tuple types. 
```

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * input: [x, y, z], messagepack array(can be lua multi return response)
```suggestion
     * input: [x, y, z, ...], MessagePack array from a Lua function multi-return response that is converted to the target result type
```

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x, y, z are some MessagePack Values
```suggestion
     * where <code>x, y, z</code> are some MessagePack values, each one representing a custom tuple
```

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * mapper result: converted {@code List<T>} from [x, y, z]
```suggestion
     * mapper result: a custom Java type inheriting {@code List<T>} that is converted from <code>[x, y, z, ...]</code>
```

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * Mapper result and its inner depends on the parameters or converters you passed.
```suggestion
     * Mapper result and its inner contents depend on the parameters or the passed converters.
```

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * @param <T> target result content type
```suggestion
     * @param <T> target result type
```

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * @param <R> target result type
```suggestion
     * @param <R> target result inner contents item type
```

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +    <T> CustomStructureToTarantoolResultMapperFactory<T> customStructureResultMapperFactory();
This method description is identical to one of the methods above. Is this method really needed? If yes, we need to change the description accordingly.

2022-12-03 23:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/TarantoolResultMapper.java
> + * Mapper from array of MessagePack to {@link TarantoolResult} with specified inner structure
```suggestion
 * Mapper from array of MessagePack values to {@link TarantoolResult} with specified inner structure
```

2022-12-04 15:40 UTC, ArtDu commented
> The SpringData library has some tricky usage and must be checked before merging.

We have AutoConverter there. The converter has same functionality like we have here except canConvertValue. I tried to add this method and it's working. I suggest to add this method in next PR

2022-12-04 15:44 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * input: storing structure with tuples inside(e.g. array of tuples [t1, t2, ...])
What is MessagePack tuples? It may confuse someone

2022-12-04 15:55 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x is some storing structure with tuples inside(e.g. array of tuples [t1, t2, ...])
> and <code>y</code> is interpreted as an error structure

It can be interpreted as an error structure, not for every cases 

https://github.com/tarantool/cartridge-java/blob/b1d8ed58ca995ae2876a3869b601ba71a41031d7/src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java#L27-L28

```suggestion
     * where <code>x</code> is a data structure with an array of tuples inside ([t1, t2, ...]) and <code>y</code> can be interpreted as an error structure
```

2022-12-04 16:10 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * @param <T> target inner result type
TarantoolResult inner type doesn't have to be a tuple. For example it's using in call method

2022-12-04 16:10 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x, y, z are some MessagePack Values
The same as above

```suggestion
     * where <code>x, y</code> are some MessagePack values. <code>x</code> is interpreted as a stored Lua function result and <code>y</code> may be interpreted as a stored Lua function error.
```

2022-12-04 16:10 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x, y, z are some MessagePack Values
Not everyone have to be custom tuple

2022-12-04 16:10 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * @param <T> target inner result type
TarantoolResult inner type doesn't have to be a tuple

2022-12-04 16:10 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x, y, z are some MessagePack Values
Each one doesn't have to be a tuple

2022-12-04 16:27 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +    <T> CustomStructureToTarantoolResultMapperFactory<T> customStructureResultMapperFactory();
It has similar functionality with `multiValueTarantoolResultMapperFactory`.  But `MultiValueCallResultConverter` checks that the result shouldn't be null and it also checks second item return error. Besides `multiValueTarantoolResultMapperFactory` uses `customStructureResultMapperFactory ` for further parsing

Also we have example how to use this mapper 

https://github.com/tarantool/cartridge-java/blob/60d30c38fa45ddcf561b4b61cd9771d4e195b2a1/src/test/java/io/tarantool/driver/mappers/TarantoolResultMapperTest.java#L53-L61

2022-12-04 20:37 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * input: storing structure with tuples inside(e.g. array of tuples [t1, t2, ...])
Values*

2022-12-04 20:40 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x is some storing structure with tuples inside(e.g. array of tuples [t1, t2, ...])
You may add that it is interpreted "if it is not empty". Really we need to underline that the second return value may be only a error structure.

2022-12-04 20:41 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * @param <T> target inner result type
OK, change it to "content type".

2022-12-04 20:41 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x is some storing structure(e.g. array [...])
You may add "if not empty"

2022-12-04 20:41 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x, y, z are some MessagePack Values
You may add "if not empty"

2022-12-04 20:43 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +    <T> CustomStructureToTarantoolResultMapperFactory<T> customStructureResultMapperFactory();
We need to describe the difference clearly. It is not obvious even for me

2022-12-04 20:57 UTC, akudiyar requested changes
We need to rename "*Custom*" to something else. I suggest anything neutral like "default" (in fact we are instantiating "Default*" and "Simple*" classes there). That also applies to the directory name.

Also look at my replies in the comments.

2022-12-05 09:04 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * input: storing structure with tuples inside(e.g. array of tuples [t1, t2, ...])
```suggestion
     * input: data structure with MessagePack values inside (e.g. array of tuples [t1, t2, ...])
```

2022-12-05 09:11 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * @param <T> target inner result type
```suggestion
     * @param <T> target inner content type
```

2022-12-05 09:14 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x, y, z are some MessagePack Values
```suggestion
     * where <code>x, y</code> are some MessagePack values. <code>x</code> is interpreted as a stored Lua function result and <code>y</code> may be interpreted as a stored Lua function error if it is not empty and there are no more arguments after <code>y</code>.
```

2022-12-05 09:15 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * @param <T> target inner result type
```suggestion
     * @param <T> target inner content type
```

2022-12-05 13:58 UTC, ArtDu commented
> We need to rename "_Custom_" to something else. I suggest anything neutral like "default" (in fact we are instantiating "Default*" and "Simple*" classes there). That also applies to the directory name.
> 
> Also look at my replies in the comments.

I did it. We can discuss if you don't like it.


<img width="446" alt="image" src="https://user-images.githubusercontent.com/22258443/205654680-cf91fece-f21b-411a-98f5-a9124d45bb3e.png">

2022-12-05 14:09 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x, y, z are some MessagePack Values
```suggestion
     * where <code>x, y, z</code> are some MessagePack values, each one representing a custom value
```

2022-12-05 14:09 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * where x, y, z are some MessagePack Values
```suggestion
     * where <code>x, y, z</code> are some MessagePack values, each one representing a custom value
```

2022-12-05 14:25 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * Mapper result and its inner depends on the parameters or converters you passed.
```suggestion
     * Mapper result and its inner depends on the parameters or converters you passed
     * For example, you can parse any MessagePack array to TarantoolResult even if it's empty array.
```

2022-12-06 21:53 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * Mapper result and its inner depends on the parameters or converters you passed.
inner contents*

2022-12-06 21:54 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * Mapper result and its inner contents depend on the parameters or the passed converters.
Mapper result and its contents depend*
You may take the phrase from the other comments

2022-12-06 22:08 UTC, akudiyar requested changes
Almost there, we need to just give a better name to one class and a method.

2022-12-07 09:08 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +     * Mapper result and its inner contents depend on the parameters or the passed converters.
```suggestion
     * Mapper result and its inner contents depend on the parameters or the passed converters.
     * Mapper checks errors and that result is not empty and uses
     * {@link StoringStructureToTarantoolResultMapperFactory} for further parsing
```

2022-12-07 10:26 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +    <T> StoringStructureToTarantoolResultMapperFactory<T> customStructureResultMapperFactory();
Renamed and squashed into 3 atomic commits

2022-12-07 11:50 UTC, akudiyar requested changes

2022-12-07 11:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/value/MapValueToTarantoolTupleResultConverter.java
> +public class MapValueToTarantoolTupleResultConverter
I suggest renaming this also to "RowsMetadataStructureToTupleResultConverter"

2022-12-09 08:58 UTC, akudiyar approved these changes
LGTM

Thanks for the work!

2022-12-09 08:59 UTC, merged