Split the readme into multiple files
tarantool/cartridge-java pull request #313
Opened 2022-11-28 16:55 UTC by iDneprov

The information for more advanced users should be extracted from the README and broken down into files

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Closes #312

2022-11-28 21:44 UTC, akudiyar requested changes

2022-11-28 21:44 UTC, akudiyar commented on README.md
> +[Cluster Tarantool client](doc/ClusterTarantoolClient.md)
I suggest adding a short description in a single paragraph for each page with some keywords that the user will be looking for, like "transient cluster failures" for the "retrying client" section. Also, I suggest renaming these documents to better reflect the use cases, having in mind that the users shouldn't use the TarantoolClient classes directly.

2022-11-29 10:12 UTC, bitgorbovsky submitted a review, later dismissed

2022-11-29 10:47 UTC, iDneprov commented on README.md
> +[Cluster Tarantool client](doc/ClusterTarantoolClient.md)
If you have any ideas for a different name for the cluster and proxy clent I would be happy to see your suggestions

2022-11-29 11:21 UTC, ArtDu requested changes

2022-11-29 11:21 UTC, ArtDu commented on doc/ClusterTarantoolClient.md
> +[Main page](../README.md)
Move it to `docs` directory. It's strange to have two similar directories
![image](https://user-images.githubusercontent.com/22258443/204512608-0c94db63-ac55-4aa5-b3ba-8bf970be6d4a.png)

2022-11-29 11:21 UTC, ArtDu commented on README.md
> +Specifying custom numbers of netty work threads
I want to suggest something like that
```suggestion
* [Cluster client](doc/ClusterTarantoolClient.md)  
Connecting to Tarantool nodes.  
The client can connect to storages and obtain data from spaces directly by space interface via native iproto binary protocol.  
It may call lua storing procedures or eval lua code on nodes.  
* [Proxy methods](doc/ProxyTarantoolClient.md)  
Connecting to routes with crud library. It proxies space interface's methods to crud methods.  
* [Retrying](doc/RetryingTarantoolClient.md)  
Retry transient cluster failures.  
* [TarantoolTuple usage](doc/TarantoolTupleUsage.md)  
Creating and operating with TarantoolTuple entity.  
* [Custom sharding function](doc/CustomShardingFunction.md)  
Determining bucket id on java side.  
* [Thread control](doc/ThreadControl.md)  
Specifying custom numbers of netty work threads.  
```

2022-11-29 11:23 UTC, iDneprov commented on doc/ClusterTarantoolClient.md
> +[Main page](../README.md)
Didn't notice it, will be fixed

2022-11-29 13:14 UTC, bitgorbovsky approved these changes

2022-11-29 13:15 UTC, ArtDu requested changes

2022-11-29 13:15 UTC, ArtDu commented on README.md
> +You can read more about Cartridge applications in its [documentation](https://www.tarantool.io/ru/docs/latest/how-to/getting_started_cartridge/).
404

2022-11-29 13:43 UTC, ArtDu approved these changes

2022-11-29 13:44 UTC, bitgorbovsky approved these changes

2022-11-30 06:42 UTC, merged