Add TarantoolTupleResultMapper factory
tarantool/cartridge-java pull request #322
Opened 2022-12-12 16:57 UTC by ArtDu

We need it to create universal mapper that can parse crud and box responses

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Closes #321

2022-12-13 22:42 UTC, akudiyar requested changes
Looks OK, but Javadocs are missing

2022-12-13 22:42 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/TarantoolTupleResultMapperFactory.java
> +public interface TarantoolTupleResultMapperFactory {
Javadocs are missing. The docs are needed both for the class (with example usage) and for the individual methods (with a purpose description)

2022-12-13 22:42 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/TarantoolTupleResultMapperFactoryImpl.java
> +public class TarantoolTupleResultMapperFactoryImpl implements TarantoolTupleResultMapperFactory {
This class can implement a Singleton pattern (like the DefaultMessagePackMapperFactory)

2022-12-13 22:42 UTC, akudiyar commented on src/test/java/io/tarantool/driver/benchmark/TarantoolSetup.java
>          ResultMapperFactoryFactoryImpl factory = new ResultMapperFactoryFactoryImpl();
This variable doesn't seem to be used further

2022-12-15 15:57 UTC, ArtDu commented on src/test/java/io/tarantool/driver/benchmark/TarantoolSetup.java
>          ResultMapperFactoryFactoryImpl factory = new ResultMapperFactoryFactoryImpl();
Fixed

2022-12-15 22:24 UTC, akudiyar requested changes
One important test kind that is missing - we need to test that several consequent and concurrent invocations of `TarantoolTupleResultMapperFactory` methods do not cause any problems with wrong mapper stacks. That means (until we haven't implemented any smart caching) a new isolated mapping stack should be created for each request. Otherwise, we immediately will have serious problems that are hard to debug

2022-12-15 22:24 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
> +        this.resultMapperFactory = TarantoolTupleResultMapperFactoryImpl.getInstance();
It does not look right to put a concrete tuple factory implementation in the abstract client, given that the Tarantool tuple class is a generic parameter. I believe it should be instantiated in the corresponding final class or some intermediate one. In the root abstract class, we may put an abstract method for it with a generic type.

2022-12-15 22:24 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    TarantoolTupleResultMapperFactory getTarantoolTupleResultMapperFactory();
Javadoc is missing

2022-12-18 18:53 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    TarantoolTupleResultMapperFactory getTarantoolTupleResultMapperFactory();
Looking at this again, I strongly believe that we need to have this factory method in the ResultMapperFactoryFactory. Otherwise it looks like an orphan

2022-12-19 07:53 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    TarantoolTupleResultMapperFactory getTarantoolTupleResultMapperFactory();
> Looking at this again, I strongly believe that we need to have this factory method in the ResultMapperFactoryFactory. Otherwise it looks like an orphan

I don't want to see this, it's awful 
```java
client.getResultMapperFactoryFactory().getTarantoolTupleResultMapperFactory()
            .withSingleValueRowsMetadataToTarantoolTupleResultMapper
```

2022-12-19 15:16 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    TarantoolTupleResultMapperFactory getTarantoolTupleResultMapperFactory();
C'est la vie \_o_/

It's not used everyday, so an orphan method in API will confuse the users more. It's a classical leaking abstraction.

2022-12-19 16:48 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    TarantoolTupleResultMapperFactory getTarantoolTupleResultMapperFactory();
> It's not used everyday, so an orphan method in API will confuse the users more

It's just a shortcut for main mappers. But I'll move if you don't change your mind about using it here where is it now. I need it to futher autoTupleConverter

In my opinion, it's hard to use from `client.getResultMapperFactoryFactory().*` cause there are so many methods. It's so difficult for people that I suggeseted to use these methods. Every time I started to think how does these ugly structures. And the sum thing that these structure don't give a perfomance in comparing to http because we have a lot of problems with those.

@Elishtar What do you think about it? I think we need third opinion

2022-12-21 22:05 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    TarantoolTupleResultMapperFactory getTarantoolTupleResultMapperFactory();
You are leaking a concrete `TarantoolTuple` implementation to the `TarantoolClient` interface which has this type as a generic type. We should not do this by any chance. It harms more than the "economy" of symbols in one place or the "ugliness" of this factory name, That's the complexity of the source object that we are modeling and we need to get it away from the users by providing non-confusing and clear structures to them.

2022-12-21 22:14 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    TarantoolTupleResultMapperFactory getTarantoolTupleResultMapperFactory();
It's better to remove the method `getTarantoolTupleResultMapperFactory()` itself and use this factory as a singleton than to add a new method that is necessary only for internal purposes. So I'd vote for removing `getTarantoolTupleResultMapperFactory()` from the `TarantoolClient` interface instead

2022-12-22 11:18 UTC, Elishtar commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    TarantoolTupleResultMapperFactory getTarantoolTupleResultMapperFactory();
@akudiyar for me `ResultMapperFactoryFactory` looks very strange and over complexity, maybe better use few different factories?

2022-12-22 17:06 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    TarantoolTupleResultMapperFactory getTarantoolTupleResultMapperFactory();
@Elishtar the initial goal of this factory was to provide helper factory methods for the common cases like this one (a concrete tuple implementation + a concrete result type). Eventually these factory methods were intended to return singleton references. Changing this to individual factory/singleton variable instantiations may work, but to me looks like less readable and harder to track and alter the places of factories usages.

2022-12-23 10:45 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
> +        this.resultMapperFactory = TarantoolTupleResultMapperFactoryImpl.getInstance();
Moved factory to ResultMapperFactoryFactory

2022-12-23 10:46 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    TarantoolTupleResultMapperFactory getTarantoolTupleResultMapperFactory();
We discussed that we move this factory to ResultMapperFactoryFactory now and that we should discuss API in more detailed later

2022-12-23 10:50 UTC, akudiyar approved these changes
LGTM

2022-12-23 11:35 UTC, merged