Add separate metadata parsers
tarantool/cartridge-java pull request #324
Opened 2022-12-13 14:44 UTC by ArtDu

Changes reduced code duplication and helped to use it easily 

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2022-12-13 22:33 UTC, akudiyar requested changes
We need unit tests for all three `parsingSpaceFormat` methods. Relying only on the integration tests is not productive since we cannot and shouldn't cover all the cases with them.

2022-12-13 22:33 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/parsers/DDLSpaceMetadataParser.java
> +public final class DDLSpaceMetadataParser extends BaseMetadataParser {
I don't get the meaning of having an inheritance between classes only with static methods. I believe it will be better to have a normal class taking an `ArrayValue` in the constructor and with different `parseSpaceFormat` methods

2022-12-13 22:33 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/parsers/VSpaceMetadataParser.java
> +public final class VSpaceMetadataParser extends BaseMetadataParser {
The same comment applies here as for DDLSpaceMetadataParser

2022-12-15 09:55 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/metadata/TarantoolSpaceMetadata.java
> +    static TarantoolSpaceMetadata parseDDLSpace(Map.Entry<Value, Value> space) {
Why do we need a factory? It's more difficult then we have static factory methods here

2022-12-15 09:56 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/metadata/TarantoolSpaceMetadata.java
> +    static TarantoolSpaceMetadata parseDDLSpace(Map.Entry<Value, Value> space) {
> I don't get why should it be in the TarantoolSpaceMetadata interface as a static method? It's not a part of API, it's something internal.

We can move it to TarantoolSpaceMetadataImpl

2022-12-15 10:04 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/metadata/parsers/DDLSpaceMetadataParser.java
> +public final class DDLSpaceMetadataParser extends BaseMetadataParser {
These classes don't store anything. They're only needed for creating a different classes like factories. I don't mind creating reusable *Parser like a normal class. We can store them in TarantoolSpaceMetadataImpl. The one problem we have with this approach that we have 
unnecessary new call(creation) every time when we create TarantoolSpaceMetadata.

2022-12-15 11:47 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/metadata/TarantoolFieldMetadataImpl.java
> +    public TarantoolFieldMetadataImpl(String fieldName, String fieldType, int fieldPosition, boolean isNullable) {
Fixed

2022-12-15 14:58 UTC, ArtDu commented
@akudiyar I've added unit tests

2022-12-15 21:53 UTC, akudiyar requested changes
The tests look OK (although a bit minimalistic), but I still don't see much sense in having separate stateless parser classes with both inheritance and static methods instead of encapsulating the parsing logic in the inherited special converters.  

Let's discuss this in PM

2022-12-18 18:48 UTC, akudiyar approved these changes
LGTM

2022-12-18 18:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/parsers/DDLSpaceMetadataParser.java
> +public final class DDLSpaceMetadataParser extends BaseMetadataParser {
We discussed this and decided to use our converters concept for the metadata parsing.

2022-12-18 18:51 UTC, merged