Add tests for mTLS
tarantool/cartridge-java pull request #329
Opened 2022-12-15 20:00 UTC by iDneprov

Add mTLS integration tests and resources

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

Closes #328

2022-12-15 22:03 UTC, akudiyar requested changes

2022-12-19 12:23 UTC, ArtDu requested changes

2022-12-19 12:23 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ssl/SslClientMTlsITEnterprise.java
> +    public void test_should_clientConnectWithMtls() throws Exception {
Rename test names according to testing conventions https://github.com/tarantool/cartridge-java/blob/master/docs/test-convention.md

2022-12-19 13:26 UTC, ArtDu requested changes

2022-12-19 13:26 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ssl/SslClientITEnterprise.java
> +    public void test_clientConnectWithSsl_should_connects_ifServerIsNonSSL() throws SSLException {
```suggestion
    public void test_clientWithSsl_shouldWork_ifServerWithoutSSL() throws SSLException {
```

2022-12-19 13:26 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ssl/SslClientITEnterprise.java
> +    public void test_clientConnectWithSsl_should_connects() throws SSLException {
```suggestion
    public void test_clientWithSsl_shouldWork() throws SSLException {
```

2022-12-19 13:26 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ssl/SslClientMTlsITEnterprise.java
> +    public void test_clientConnectWithMtls_should_connects() throws Exception {
```suggestion
    public void test_clientConnectWithMtls_shouldWorkFine() throws Exception {
```

2022-12-19 13:26 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ssl/SslClientMTlsITEnterprise.java
> +    public void test_clientConnectToMTLSServerWithoutCA_should_throwException() throws Exception {
```suggestion
    public void test_clientWithoutCA_shouldThrowException_ifServerWithMTLS() throws Exception {
```

2022-12-19 13:28 UTC, ArtDu submitted a review, later dismissed

2022-12-19 15:00 UTC, akudiyar approved these changes
LGTM

2022-12-19 15:01 UTC, merged