Use options like mixins in proxy operations
tarantool/cartridge-java pull request #330
Opened 2022-12-19 11:18 UTC by ArtDu

We need it to avoid duplication of code when we need have something like below:
<img width="862" alt="image" src="https://user-images.githubusercontent.com/22258443/208414334-9774b225-a7a1-4db8-9ad3-650445a02c8a.png">
In this picture we need to use multiply inheritance, but it doesn't work with java

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2022-12-21 14:24 UTC, ArtDu commented
@akudiyar @Elishtar Also you can see how it looks with another option. Spoiler - it looks awful
https://github.com/tarantool/cartridge-java/pull/263

2022-12-21 21:37 UTC, akudiyar requested changes
I remember why we went with the code duplication option instead of this way, although it seems appealing. The problem is that this implementation is OK for the proxy (CRUD) operations, and is not correct for the box (single instance) operations, because they support neither bucket ID nor timeout. In this case the user will see "withBucketId" option in the options builder, for example, and will be confused because it doesn't have any sense for the box operation. In that case, we need to fire an exception when the user calls an unsupported "add" method for making the user aware that that particular client type does not support it.

The best place for such an exception is when a call request is being built and we are passing the options to it. We need to have the corresponding unit tests as well.

2022-12-21 21:58 UTC, akudiyar approved these changes

2022-12-21 21:58 UTC, merged

2022-12-22 09:58 UTC, ArtDu commented
> UPD: nvm. THe old approach had the same problem with bucket ID available for the single instance client.

Yeah, we can fix it by splitting `SelectOption` to `SelectOption` and `ProxySelectOption` interfaces