Batch operation errors parsing
tarantool/cartridge-java pull request #335
Opened 2022-12-28 17:31 UTC by akudiyar

I decided to not make a separate `SingleValueCallResult` parser for batch operations specifically because I believe that the return format must be fixed in tarantool/crud and it will change in the future. So I added a new case to the common parser and refactored it a bit.

I haven't forgotten about:
- [x] Tests
- [x] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Fixes #334

2022-12-28 18:18 UTC, ArtDu requested changes

2022-12-28 18:18 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java
> +        } else if (callResultSize == 2 && errorsValue.isArrayValue()) {
nit: You don't need else for every conditional branch here because you return or throw in them

2022-12-28 18:18 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java
> +        Value errorsValue = result.getOrNilValue(1);
Does it change anything? Below you use the same `isNilValue()`

2022-12-28 18:18 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java
> +            // [result, nil] or [result, errors]
You checked that second argument is not nil
```suggestion
            // [result, []] or [result, errors]
```

2022-12-28 23:10 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java
> +            // [result, nil] or [result, errors]
Fixed the comment, thanks

2022-12-28 23:11 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java
> +        Value errorsValue = result.getOrNilValue(1);
It doesn't change the logic, although saves a few CPU cycles

2022-12-28 23:12 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java
> +        } else if (callResultSize == 2 && errorsValue.isArrayValue()) {
Let's leave it as is for verbosity and logic visibility

2022-12-28 23:13 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java
> +        Value errorsValue = result.getOrNilValue(1);
getOrNilValue() returns NilValue in case if the index is out of range.

2022-12-29 08:27 UTC, ArtDu approved these changes

2022-12-29 11:21 UTC, merged