Access Changed from public to protected for TarantoolResultImpl and TarantoolTupleResultImpl #326
tarantool/cartridge-java pull request #338
Opened 2022-12-30 11:13 UTC by devrishal

For `TarantoolResultImpl`, `TarantoolTupleResultImpl`
Changing the access to protected because of its internal functionality. They are used in converters.

I haven't forgotten about:
- [ ] Tests
- [X] Changelog
- [ ] Documentation
- [X] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [X] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Closes #326

2022-12-30 18:39 UTC, akudiyar requested changes
Hi, thanks for the patch! Please look at the comments below.

2022-12-30 18:39 UTC, akudiyar commented on CHANGELOG.md
> +- Close public access to TarantoolResult*Impl ([#326](https://github.com/tarantool/cartridge-java/issues/326))
These lines are under an already released version. Please add this new line under the "Unreleased" header above.

2022-12-30 18:39 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/RowsMetadataToTarantoolTupleResultConverter.java
> +    extends TarantoolTupleResultImpl
These two classes cannot share a common hierarchy. I suggest looking into creating a new factory for producing `TarantoolTupleResultImpl` instances.

2022-12-30 18:39 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/value/ArrayValueToTarantoolResultConverter.java
> +    extends TarantoolResultImpl
These two classes cannot share a common hierarchy. I suggest looking into creating a new factory for producing TarantoolResultImpl instances.

2022-12-30 18:39 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/value/ArrayValueToTarantoolTupleResultConverter.java
> +    extends TarantoolResultImpl
These two classes cannot share a common hierarchy. I suggest looking into creating a new factory for producing TarantoolResultImpl instances.

2022-12-30 20:09 UTC, devrishal commented on CHANGELOG.md
> +- Close public access to TarantoolResult*Impl ([#326](https://github.com/tarantool/cartridge-java/issues/326))
Done as per suggestions.

2023-01-02 12:45 UTC, devrishal commented on src/main/java/io/tarantool/driver/core/metadata/RowsMetadataToTarantoolTupleResultConverter.java
> +    extends TarantoolTupleResultImpl
Thanks for suggestions, I am working on it. If you can provide some reference or some example from the existing codebase or other places is also fine, it would be great help for me.

2023-01-02 21:08 UTC, devrishal commented on src/main/java/io/tarantool/driver/mappers/converters/value/ArrayValueToTarantoolResultConverter.java
> +    extends TarantoolResultImpl
Introduced new class to create objects, Let me know if its fine? or if there is any suggestions.

2023-01-03 13:33 UTC, devrishal commented
@akudiyar I have modified and tried to implement as per suggestions, Please look into the new changes and let me know if any further changes are required.

2023-01-09 16:47 UTC, devrishal commented on src/main/java/io/tarantool/driver/mappers/converters/value/ArrayValueToTarantoolTupleResultConverter.java
> +    extends TarantoolResultImpl
Added new Factory class to create the object

2023-01-22 18:42 UTC, akudiyar requested changes
Hi @devrishal, would you mind rebasing your PR?
Also, I suggest using TarantolResultImplFactory as a singleton. And try to run `mvn verify` and `mvn test` before pushing, to eliminate any missing test changes and linter warnings.

2023-01-22 18:42 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/metadata/RowsMetadataToTarantoolTupleResultConverter.java
> +        this.tarantoolResultFactory = new TarantoolResultFactory<>();
It's better to use the Singleton pattern for this factory

2023-01-23 18:10 UTC, devrishal commented on src/main/java/io/tarantool/driver/core/metadata/RowsMetadataToTarantoolTupleResultConverter.java
> +        this.tarantoolResultFactory = new TarantoolResultFactory<>();
Tried implementing the same, Please check and let me know if any suggestions.

2023-01-31 20:37 UTC, akudiyar requested changes
Two more places to introduce the singleton usage + one small fix with typing and the Javadocs are missing for the new class.

Please run also `mvn clean javadoc:javadoc` to fix all the new linter warnings.

2023-01-31 20:37 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/converters/value/ArrayValueToTarantoolResultConverter.java
> +        this.tarantoolResultFactory = new TarantoolResultFactory<>();
Why aren't we using the singleton instance here?

2023-01-31 20:37 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/TarantoolResultFactory.java
> +public class TarantoolResultFactory<T> {
I believe that the type variable `<T>` is not needed here because it is necessary for one method only where the type variable is included in the parameter. Therefore you need to specify the variable only on that method.

2023-01-31 20:37 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/TarantoolResultFactory.java
> +
Javadoc is missing

2023-02-01 15:56 UTC, devrishal commented on src/main/java/io/tarantool/driver/mappers/converters/value/ArrayValueToTarantoolResultConverter.java
> +        this.tarantoolResultFactory = new TarantoolResultFactory<>();
Corrected it. Changed to `this.tarantoolResultFactory = TarantoolResultFactory.getInstance();`

2023-02-01 15:57 UTC, devrishal commented on src/main/java/io/tarantool/driver/core/TarantoolResultFactory.java
> +public class TarantoolResultFactory<T> {
Removed the Class Level Type `<T>`.

2023-02-01 15:57 UTC, devrishal commented on src/main/java/io/tarantool/driver/core/TarantoolResultFactory.java
> +
Added JavaDoc.

2023-02-01 19:52 UTC, akudiyar approved these changes
Looks good now. Thanks for your work Rishal!

2023-02-02 08:45 UTC, devrishal commented
> Although it shows me some conflicts, so I cannot merge the PR. Would you mind rebasing it again? @devrishal

Did the rebase and Thanks for providing your guidance and suggestions.

2023-02-02 18:16 UTC, akudiyar commented
@devrishal you did a "merge" but what is needed is **rebasing** your branch on the master branch. We have a policy that enforces only fast-forward pushes. Would you mind removing the last merge commit and rebasing again?

2023-02-03 15:01 UTC, devrishal commented
> @devrishal you did a "merge" but what is needed is **rebasing** your branch on the master branch. We have a policy that enforces only fast-forward pushes. Would you mind removing the last merge commit and rebasing again?

I have tried the approach, Please let me know if the things looks good now?

2023-02-09 16:02 UTC, devrishal commented
@akudiyar Can you please check and let me know if there is any further changes needed in my PR

2023-02-09 20:51 UTC, merged