WIP: Retrying runnable
tarantool/cartridge-java pull request #340
Opened 2023-01-10 12:33 UTC by ArtDu

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2023-01-22 21:51 UTC, akudiyar requested changes
Overall looks better than the current state, let's comb it out a bit

2023-01-22 21:51 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperationWithAttempts.java
> +                if (policy.getAttempts() == 0) {
Except this statement, the other lines in this function are the same that in the RetryingAsyncOperation. I suggest making the above class a base class and the current class an inherited class, with these lines moved to a function ( in the other class it will be a default empty function)

2023-01-22 21:51 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +                    retryingAsyncOperation.run();
Wouldn't it be better here to organize the code as
`.runAsync(retryingAsyncOperation, executor).acceptEither(... global timeout future..., ...dummy callback...)` ?

2023-01-22 21:51 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +                    retryingAsyncOperation.run();
The current variant does not schedule the global timeout future correctly, because the "run()" method is executed synchronously in the current thread

2023-01-22 21:51 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +        public <R> CompletableFuture<R> wrapOperation(Supplier<CompletableFuture<R>> operation, Executor executor) {
It seems that this function can now be combined with the one in the base class and does not need a separate implementation

2023-01-31 12:28 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
> +        // it never completes correctly only exceptionally
We are canceling only the delayed future that should trigger this timeout

2023-01-31 12:34 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
> +            .exceptionally(ex -> { // if requestTimeout has been raised or operation return exception
But with whenComplete we would have if condition with `ex != null` check

2023-01-31 12:41 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
> +                    // optimization: stop delayed future if resultFuture has already done from outside
Why is it necessary?

2023-01-31 15:51 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RequestTimeoutOperation.java
> + * @author Artyom Dubinin
Fixed

2023-01-31 15:51 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
> + * @author Artyom Dubinin
Added some

2023-01-31 15:51 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
> +                if (resultFuture.isDone()) {
Added

2023-01-31 15:51 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
> +                    ScheduledFuture<?> delayFuture = TarantoolRequestRetryPolicies.getTimeoutScheduler()
Added it above 
```java
// to be able to track trace of all errors
log.debug(ex.getMessage());

```

2023-01-31 15:51 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +                    retryingAsyncOperation.run();
And we need to start operation asynchronously because we need to start timer after starting of the task

2023-01-31 15:53 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RequestRetryPolicy.java
> +        CompletableFuture.runAsync(retryingAsyncOperation::run, executor) // run operation in specified executor
Fixed

2023-01-31 15:53 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperationWithAttempts.java
> + * @author Artyom Dubinin
Removed this file and change logic cause it was a huge crutch

2023-01-31 21:03 UTC, akudiyar requested changes
Answered some of the comments

2023-01-31 21:03 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
> +                    // optimization: stop delayed future if resultFuture has already done from outside
Ok let's leave it as is.

2023-01-31 21:03 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +                    retryingAsyncOperation.run();
But you are first finishing the task here and then scheduling a timer. You need to run the main task asynchronously.

2023-03-01 11:41 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +                    retryingAsyncOperation.run();
> But you are first finishing the task here and then scheduling a timer. You need to run the main task asynchronously.

I don't finish the task here, I just start it. Using acceptEither could give us the probability of completing the timeout task before the operation was started

2023-03-01 11:52 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
> +        // it never completes correctly only exceptionally
Added `the timeout task can only be completed with an exception or canceled`

2023-03-01 11:53 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
> +            .exceptionally(ex -> { // if requestTimeout has been raised or operation return exception
Fixed

2023-03-01 11:53 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
> +            }).exceptionally(ex -> { // if error has been happened in previous exceptionally section
Added `try catch`

2023-03-01 11:58 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperationWithAttempts.java
> +                if (policy.getAttempts() == 0) {
The file was deleted in previous changes

2023-03-01 11:59 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +        public <R> CompletableFuture<R> wrapOperation(Supplier<CompletableFuture<R>> operation, Executor executor) {
It was combined if I remember it correcty

2023-03-01 22:44 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +                    retryingAsyncOperation.run();
It should never happen really. Both tasks are scheduled with acceptEither.

2023-03-02 08:03 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +                    retryingAsyncOperation.run();
Yeah, it will wait for them until they both finish. But `retryingAsyncOperation.run();` is not running of the operation, it's just starting of operation. Then the scheduler can start timeout before operation

2023-03-03 22:59 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +                    retryingAsyncOperation.run();
`runAsync` is not running the operation too, it just schedules it in the executor. We schedule both tasks and wait on both, which one finishes first:
https://www.concretepage.com/java/java-8/java-completablefuture-accepteither
Note, we may need to use `supplyAsync` instead of `runAsync`, depending on the callback.

2023-03-10 07:47 UTC, dkasimovskiy commented
@akudiyar please take a look on the PR.

2023-03-13 22:18 UTC, akudiyar approved these changes
It seems that some changes that I was reviewing disappeared completely. so I think we need to merge this already. Nvm these comments, but let them be

2023-03-13 22:19 UTC, merged