Add more tests and remove ununsed code in retrying
tarantool/cartridge-java pull request #344
Opened 2023-01-13 09:49 UTC by ArtDu

Coverage:
![image](https://user-images.githubusercontent.com/22258443/212290024-d7b3176a-b625-444c-bddf-4e59ca4d0aac.png)

I haven't forgotten about:
- [x] Tests
- [ ] Changelog
- [ ] Documentation
- [x] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [x] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2023-01-16 12:47 UTC, Elishtar commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +                                    .completeExceptionally(
May by better resultFuture.completeExceptionally(

2023-01-16 12:48 UTC, Elishtar commented on src/test/java/io/tarantool/driver/api/retry/RequestRetryPolicyTest.java
> +        } catch (ExecutionException e) {
May be `assertThrows`?

2023-01-16 12:49 UTC, Elishtar commented on src/test/java/io/tarantool/driver/api/retry/RequestRetryPolicyTest.java
> +        } catch (ExecutionException e) {
May be assertThrows?

2023-01-16 12:52 UTC, Elishtar commented on src/test/java/io/tarantool/driver/api/retry/RequestRetryPolicyTest.java
> +    private CompletableFuture<Boolean> neverCompletedFuture() {
Let's try to use @Mock

2023-01-22 18:32 UTC, akudiyar requested changes
Overall LGTM, but I agree with the comments from Andrey.

2023-01-30 11:35 UTC, ArtDu commented on src/test/java/io/tarantool/driver/api/retry/RequestRetryPolicyTest.java
> +    private CompletableFuture<Boolean> neverCompletedFuture() {
I don't see an easy way to use Mock here. Cause we need to mock get method for sleeping and it looks more complicated

2023-01-30 11:35 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> +                                    .completeExceptionally(
Fixed

2023-01-30 11:36 UTC, ArtDu commented on src/test/java/io/tarantool/driver/api/retry/RequestRetryPolicyTest.java
> +        } catch (ExecutionException e) {
Replaced all try catch assert on it

2023-01-31 20:30 UTC, akudiyar approved these changes
LGTM

2023-01-31 20:30 UTC, merged