Add Proxy Tarantool client example with multiple routers
tarantool/cartridge-java pull request #351
Opened 2023-02-01 12:42 UTC by iDneprov

Add Proxy Tarantool client example with multiple routers

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

Closes #348

2023-02-01 19:44 UTC, akudiyar requested changes
I see that this is still a work in progress, but I hope my comments will be useful anyway,

2023-02-01 19:44 UTC, akudiyar commented on README.md
> +* [Crud methods](docs/ProxyTarantoolClient.md)
"CRUD" is an abbreviation. We need to either use it capitalized (and preferably with a link somewhere to a wiki-like article, because it is not a standard term) or make a link to the `tarantool/crud` library here.

2023-02-01 19:44 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +This section shows examples how to connect to multiple crud routers.
```suggestion
This section shows examples of how to connect to multiple [Cartridge](https://github.com/tarantool/cartridge) routers.  
```

2023-02-01 19:44 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +# Connecting to multiple instances
```suggestion
# Connecting to multiple Tarantool instances
```

2023-02-01 19:44 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +https://github.com/tarantool/cartridge-java/blob/46aa956388099c06813e5b5cca5433c2df6bc1b1/src/test/java/io/tarantool/driver/integration/ReconnectIT.java#L291-L300
I suggest wrapping these links into named ones. And as a user, I want to see an extract of the key code lines here because following a long sequence of links each time distracts me from the initial goal.

2023-02-01 19:44 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +                // Amount of connections per instance
```suggestion
                // Number of connections per Tarantool instance
```

2023-02-01 19:44 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +You don't have to set the routers addresses yourself address provider can do it for you
We have an example of writing user's own address provider, but not a complete solution. So I'd rather reformulate this sentence to something more accurate.

2023-02-01 19:44 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +https://github.com/tarantool/cartridge-java/blob/c4ff2cad113c0b1594e5133e4239c5213055dd95/src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientWithAddressProviderExampleIT.java#L76-L83
Again, having code fragments will churn the readers less than pushing them to read some code not related to their tasks. We may leave the links for those who want additional details.

2023-02-01 20:07 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +https://github.com/tarantool/cartridge-java/blob/46aa956388099c06813e5b5cca5433c2df6bc1b1/src/test/java/io/tarantool/driver/integration/ReconnectIT.java#L291-L300
I see that GitHub is now converting such links to code previews. That's much better than I expected, so you may ignore my comment if the result will look like an embedded code fragment.

2023-02-01 20:08 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +https://github.com/tarantool/cartridge-java/blob/c4ff2cad113c0b1594e5133e4239c5213055dd95/src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientWithAddressProviderExampleIT.java#L76-L83
I see that GitHub is now converting such links to code previews. That's much better than I expected, so you may ignore my comment if the result will look like an embedded code fragment.

2023-02-02 09:42 UTC, ArtDu requested changes

2023-02-02 09:42 UTC, ArtDu commented on docs/MultiInstanceConnecting.md
> +https://github.com/tarantool/cartridge-java/blob/484190b9642a87213c1cc5ab66511949396a3899/src/test/resources/cartridge/app/roles/custom.lua#L51
You can just use here `function get_routers()` without `local` and then you don't need to show `rawset`. It would be easily to undestand

2023-02-02 09:42 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientWithAddressProviderExampleIT.java
> +        return new TestWrappedClusterAddressProvider(
Can we get rid of from this test thing `TestWrappedClusterAddressProvider`?

2023-02-02 09:42 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientWithAddressProviderExampleIT.java
> +            .withClientConfig(config)
Don't we have `withCredentials`? It will be awful if we don't have

2023-02-02 09:42 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientWithAddressProviderExampleIT.java
> +            container.getPassword());
First of all, you've already have USER_NAME, PASSWORD. In general I suggest to have one TarantoolCredentials for connection and for endpoint provider to reduce duplications

2023-02-02 09:45 UTC, iDneprov commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientWithAddressProviderExampleIT.java
> +            .withClientConfig(config)
we don't have it

2023-02-02 10:41 UTC, iDneprov commented on docs/MultiInstanceConnecting.md
> +https://github.com/tarantool/cartridge-java/blob/484190b9642a87213c1cc5ab66511949396a3899/src/test/resources/cartridge/app/roles/custom.lua#L51
Yes it is match better

2023-02-02 11:55 UTC, ArtDu approved these changes

2023-02-02 11:55 UTC, ArtDu commented on docs/MultiInstanceConnecting.md
> +https://github.com/tarantool/cartridge-java/blob/484190b9642a87213c1cc5ab66511949396a3899/src/test/resources/cartridge/app/roles/custom.lua#L3-L30
And don't forget to change commit hash here

2023-02-02 16:46 UTC, ArtDu submitted a review, later dismissed

2023-02-02 18:24 UTC, akudiyar reviewed
Looks good, I have small nitpicks though

2023-02-02 18:24 UTC, akudiyar commented on docs/ProxyTarantoolClient.md
> +# Using CRUD methods
```suggestion
# Using CRUD stored procedures
```

2023-02-02 18:24 UTC, akudiyar commented on README.md
> +* [Using CRUD methods](docs/ProxyTarantoolClient.md)
```suggestion
* [Using CRUD stored procedures](docs/ProxyTarantoolClient.md)  
```

2023-02-02 18:24 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +Example of TarantoolClient set up with address provider
I'd rather add a note like `you may use the provided code as a reference for your own implementation`.

2023-02-03 07:47 UTC, iDneprov commented on docs/MultiInstanceConnecting.md
> +Example of TarantoolClient set up with address provider
Added

2023-02-06 10:29 UTC, ArtDu submitted a review, later dismissed

2023-02-07 08:29 UTC, ArtDu approved these changes

2023-02-07 08:29 UTC, merged