WIP: Update retrying client documentation
tarantool/cartridge-java pull request #352
Opened 2023-02-06 19:08 UTC by iDneprov

Update retrying client documentation

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

Closes #309

2023-02-07 08:56 UTC, ArtDu commented on docs/RetryingTarantoolClient.md
> +https://github.com/tarantool/cartridge-java/blob/8a880423da1ce2bc0e82557d70ab46c9e7eba618/src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientExampleIT.java#L64-L107
You can have a more visual example and complex example for it cause it's more complex API:
```
...
.withProxyMethodMapping(builder -> builder.withDeleteFunctionName("delete_with_error_if_not_found"))
.withRetryingByNumberOfAttempts(5, 
             // You can use default predicates from TarantoolRequestRetryPolicies for checking errors 
             retryNetworkErrors() 
                 // Also you can use your own predicates and combine them with each other 
                 .or(e -> e.getMessage().contains("Unsuccessful attempt")) 
                 // Or with defaults 
                 .or(retryTarantoolNoSuchProcedureErrors())
                 .or(retryDeleteError()), 
             // Also you can set delay in millisecond between attempts 
             factory -> factory.withDelay(300) 
         ) 
...


space(...).delete(); // retrying 
space(...).insert();
```

2023-02-07 14:02 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ReconnectIT.java
> +        }).start();
You dont' have to use Thread API, you can't guarantee that your insert method will be called after deletion. It'd better to use CompletableFuture API, for e.g.
```java
AtomicInteger retryingCounter = new...
...
.or(e -> {
    retryingCounter.addAndGet();
    return e.getMessage().contains("Records not found"); 
})
...
CompletableFuture deleteFuture = retryingClient.space(SPACE_NAME).delete(conditions);
retry(() -> assertEquals(1, retryingCounter.get()))
space.insert(tupleFactory.create(1, null, "FIO", 50, 100)).get();
deleteFuture.get();
```

But for this you need it in TarantoolUtils.java
```java
public static Integer DEFAULT_RETRYING_ATTEMPTS = 5;
    public static Integer DEFAULT_RETRYING_DELAY = 100;

    public static void retry(Runnable fn) throws InterruptedException {
        retry(DEFAULT_RETRYING_ATTEMPTS, DEFAULT_RETRYING_DELAY, fn);
    }

    public static void retry(Integer attempts, Integer delay, Runnable fn) throws InterruptedException {
        while (attempts > 0) {
            try {
                fn.run();
                return;
            } catch (AssertionError ignored) {
            }

            --attempts;
            Thread.sleep(delay);
        }
        fn.run();
    }
```

2023-02-08 13:43 UTC, ArtDu approved these changes
I still don't believe that it works from the first attempt, but good for you :)

2023-02-08 23:20 UTC, akudiyar requested changes

2023-02-08 23:20 UTC, akudiyar commented on docs/RetryingTarantoolClient.md
> +In this example I use custom delete function.
"I use" -> "we use" looks better I believe

2023-02-08 23:20 UTC, akudiyar commented on docs/RetryingTarantoolClient.md
> +In this example I use custom delete function.
Or "let's consider a custom delete function"

2023-02-09 07:25 UTC, iDneprov commented on docs/RetryingTarantoolClient.md
> +In this example I use custom delete function.
> "I use" -> "we use" looks better I believe

I don't think so

2023-02-09 07:30 UTC, merged

2023-02-09 07:39 UTC, iDneprov commented on docs/RetryingTarantoolClient.md
> +In this example I use custom delete function.
> Or "let's consider a custom delete function"

This looks better. I'll increase the formality of language in documentation soon #356