Upadate TarantoolTupleUsage
tarantool/cartridge-java pull request #355
Opened 2023-02-08 14:42 UTC by iDneprov

Update documentation with examples of TarantoolTuple usage

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

Closes #354

2023-02-08 23:22 UTC, akudiyar requested changes

2023-02-08 23:22 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientExampleIT.java
> +        assertEquals(1, object.orElse(null));
`orElse(null)` is generally considered a bad pattern. `orElseThrow` is better since it explicitly indicates an invariant failure.

2023-02-10 12:27 UTC, ArtDu requested changes

2023-02-10 12:27 UTC, ArtDu commented on docs/TarantoolTupleUsage.md
> +or can be returned from default [tarantool/crud](https://github.com/tarantool/crud) functions.
It's not only about crud, it also covers box responses

2023-02-10 12:27 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientExampleIT.java
> +        accounts.insert(tuple).join();
More verbosity?
```suggestion
        TarantoolTuple inputTuple = tupleFactory.create(1, null, "credit card", 99.99);

        // Insert it in the database
        accounts.insert(inputTuple).join();
```

2023-02-10 12:27 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientExampleIT.java
> +    }
More verbosity?

```suggestion
        TarantoolTuple selectTuple = selectResult.get(0);

        // You can get value from TarantoolTuple by its filedPosition
        // If you do not set objectClass default converter will be used for this value
        Optional<?> object = selectTuple.getObject(0);
        assertEquals(1, object.orElseThrow(NullPointerException::new));

        // For example any non-integer number will be converted to Double by default
        Optional<?> doubleValue = selectTuple.getObject(3);
        assertEquals(99.99, doubleValue.orElseThrow(NullPointerException::new));
        assertEquals(Double.class, doubleValue.orElseThrow(NullPointerException::new).getClass());

        // But if you need to get Float, you can set objectClass
        Optional<?> floatValue = selectTuple.getObject(3, Float.class);
        assertEquals(99.99f, floatValue.orElseThrow(NullPointerException::new));
        assertEquals(Float.class, floatValue.orElseThrow(NullPointerException::new).getClass());

        // You do not have to work with Optional
        // Getters for all basic types are available
        float floatNumber = selectTuple.getFloat(3);
        assertEquals(99.99f, floatNumber);

        // Also you can get values by field name
        Optional<?> balance = selectTuple.getObject("balance");
        assertEquals(99.99, balance.orElseThrow(NullPointerException::new));

        String stringValue = selectTuple.getString("name");
        assertEquals("credit card", stringValue);
    }
```

2023-02-10 12:27 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientExampleIT.java
> +        TarantoolTuple tarantoolTuple = selectResult.get(0);
Should check the size before get(0) to avoid exceptions for people who will use it

2023-02-10 12:27 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientExampleIT.java
> +        Optional<?> object = tarantoolTuple.getObject(0);
also check size

2023-02-10 13:32 UTC, ArtDu approved these changes

2023-02-10 15:13 UTC, merged