WIP Use different converters besides via factory
tarantool/cartridge-java pull request #359
Opened 2023-02-17 11:12 UTC by ArtDu

IT'S CONCEPT WITH UNUSED TRASH AND HASN'T WORKET YET

To use mappers for custom behavior

```java
MessagePackMapper valueMapper = client.getConfig().getMessagePackMapper();

ResultMapperFactoryFactory factory =
    client.getResultMapperFactoryFactory();
CallResultMapper returnMapper = factory.createMapper()
    .withSingleValueConverter(
        factory.createMapper()
            .withArrayValueToTarantoolTupleResultConverter(valueMapper, null)
            .withRowsMetadataToTarantoolTupleResultMapper(valueMapper, null)
            .buildMessagePackMapper(DefaultMessagePackMapperFactory.getInstance().emptyMapper())
    )
    .buildCallResultMapper(DefaultMessagePackMapperFactory.getInstance().emptyMapper());

Object crudResult =
    client.call("crud.select", Collections.singletonList("test_space"), returnMapper).join();
assertTrue(crudResult instanceof TarantoolTupleResultImpl);
Object boxResult =
    client.call("select_request_counters", new ArrayList<>(), returnMapper).join();
assertTrue(boxResult instanceof TarantoolTupleResultImpl);
```

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2023-02-21 23:48 UTC, akudiyar requested changes
I like the idea in general. Let's correct the API a bit and add some short examples in the Javadocs for the people to be able to use it and read this code.
We will need to explain what that hierarchy of mappers

2023-02-21 23:48 UTC, akudiyar commented on CHANGELOG.md
> +- Add factory builder to be able making mapper hierarchy
```suggestion
- Add a factory builder for constructing mapper hierarchies
```

2023-02-21 23:48 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +    Builder createMapper();
Javadoc is missing. I suggest putting short builder usage example in the Javadoc

2023-02-21 23:48 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +    interface Builder {
Javadocs for the methods are necessary

2023-02-21 23:48 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactoryImpl.java
> +            return new CallResultMapper(valueMapper, mappers);
Looks like a copy-paste, should it be a DefaultMessagePackMapper?

2023-02-21 23:48 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +                factory.createMapper()
In this example, we have `valueMapper` passed 3 times and one time with a necessary `copy()` call. We will never have a chance to explain how to use this to the customers, and we will make mistakes ourselves.

But let's pass the `valueMapper` once to the builder:
```
CallResultMapper callReturnMapper = factory.createMapper(valueMapper)
            .withSingleValueConverter(
                factory.createMapper(valueMapper)
                    .withArrayValueToTarantoolTupleResultConverter()
                    .withRowsMetadataToTarantoolTupleResultMapper()
                    .buildMessagePackMapper()
            )
            .buildCallResultMapper();
```
The `copy()` method will be called internally where it is needed.

We can make a second `createMapper()` method accepting also space metadata. Passing `null` several times is also not comfortable.

What do you think?

2023-02-28 14:06 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +    Builder createMapper();
Added something

2023-02-28 14:06 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +    interface Builder {
Added something

2023-02-28 14:07 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactoryImpl.java
> +            return new CallResultMapper(valueMapper, mappers);
I fixed something

2023-02-28 14:08 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +                factory.createMapper()
Yeah, your're right. It should be more easier

2023-03-01 22:50 UTC, akudiyar approved these changes

2023-03-01 22:52 UTC, merged