Add deep copy instead of shallow copy in mappers
tarantool/cartridge-java pull request #360
Opened 2023-02-17 12:54 UTC by ArtDu

I haven't forgotten about:
- [x] Tests
- [x] Changelog
- [ ] Documentation
- [x] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [x] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Closes #166

2023-02-19 20:15 UTC, akudiyar requested changes

2023-02-19 20:15 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
> +        this.valueConverters = mapper.valueConverters.entrySet().stream()
Although it's a good idea on its own, it will lead to large memory consumption growth. Remember that we are currently creating a mapper stack on each request.

Did this change come out of a recently encountered bug? I was worried about that after we made the last mappers refactoring, see my comment https://github.com/tarantool/cartridge-java/pull/300#pullrequestreview-1203576211. Maybe let's think about proper mapper caching this time?

Raw idea:  we should define a "tagging" API for mappers (e.g. a hashcode for the whole stack) that we can use for caching the other mappers. Using such tag (hashcode) can allow caching mappers without space schema involved, but it will require each converter and mapper to provide a unique tag (hashcode).

2023-02-20 08:25 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
> +        this.valueConverters = mapper.valueConverters.entrySet().stream()
> Did this change come out of a recently encountered bug?

It's problem in springdata, because there we use registerValueConverter per request there. We should also think about how to separate custom mappers from default ones besides caching

2023-02-20 09:56 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
> +        this.valueConverters = mapper.valueConverters.entrySet().stream()
I added your thoughts in https://github.com/tarantool/cartridge-java/issues/117

And also created a ticket about my separation idea https://github.com/tarantool/cartridge-java/issues/361

2023-02-20 10:40 UTC, Elishtar approved these changes

2023-02-20 10:49 UTC, merged