Add default client request timeout
tarantool/cartridge-java pull request #362
Opened 2023-02-27 19:39 UTC by ArtDu

I haven't forgotten about:
- [x] Tests
- [x] Changelog
- [ ] Documentation
- [x] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [x] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Closes #87

2023-02-27 21:16 UTC, akudiyar requested changes

2023-02-27 21:16 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceDeleteOptionsIT.java
> +        assertEquals(requestConfigTimeout, ((HashMap) crudDeleteOpts.get(0)).get("timeout"));
Seems that setting the request timeout is missing here

2023-02-27 21:16 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceDeleteOptionsIT.java
> +        assertEquals(requestConfigTimeout, ((HashMap) crudDeleteOpts.get(0)).get("timeout"));
That also applies to all the other tests

2023-02-27 21:16 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/proxy/DeleteProxyOperation.java
> +                .withTimeout(optionsTimeout.isPresent() ? optionsTimeout : requestTimeout)
I'm not sure that we need two ways of setting the timeout. For what the other timeout (in options) then stands for? In the previous variant, the request timeout was passed to the response handler. I believe that we need to make them distinct timeouts and pass both of them in the options.

2023-02-27 21:16 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/proxy/DeleteProxyOperation.java
> +                .withTimeout(optionsTimeout.isPresent() ? optionsTimeout : requestTimeout)
Passing in the options is optional, but passing to the handler is mandatory I think

2023-02-28 10:38 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/proxy/DeleteProxyOperation.java
> +                .withTimeout(optionsTimeout.isPresent() ? optionsTimeout : requestTimeout)
But the main think about the changes that we have passing config.requestTimeout https://github.com/tarantool/cartridge-java/blob/97f2a19a4e90b90a7ffa515d4175a5daec10fa2c/src/main/java/io/tarantool/driver/core/space/ProxyTarantoolSpace.java#L251-L256

For example if we used fields options we wouldn't have this feature and it might frustrate. This is the thing that @vlalykin complained:

> добрый день.
по поводу возможности задания списка полей в options: https://github.com/tarantool/cartridge-java/issues/236

>если я задаю новый параметр для уточнения списка полей, то не передается дефолтный таймаут (который раньше задавался один раз на уровне клиента). теперь его надо каждый раз руками задавать, или я что то неправильно делаю ?

>client.getSpace(SPACE).select(condition, ProxySelectOptions.create().withFields(fields))

2023-03-01 22:56 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/proxy/DeleteProxyOperation.java
> +                .withTimeout(optionsTimeout.isPresent() ? optionsTimeout : requestTimeout)
The timeout that is passed currently to the options is different. We need to not pass the `requestTimeout` instead of that timeout, but rather pass this `requestTimeout` to the request handler as it was done previously (that's what the users want).

2023-03-01 22:57 UTC, akudiyar requested changes
We need to return back the previous behavior, it is currently broken. The actual changes are doing something other.

2023-03-02 08:21 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/proxy/DeleteProxyOperation.java
> +                .withTimeout(optionsTimeout.isPresent() ? optionsTimeout : requestTimeout)
We always pass requestTimeout in crud option. See [0.8.0](https://github.com/tarantool/cartridge-java/blob/fd90d07117fadbdf591af65404d3c793e306dbfb/src/main/java/io/tarantool/driver/core/space/ProxyTarantoolSpace.java#L139) version(it's before my options changes). Do you want to change this behavior?

2023-03-03 22:49 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/proxy/DeleteProxyOperation.java
> +                .withTimeout(optionsTimeout.isPresent() ? optionsTimeout : requestTimeout)
Ah, it was broken even then. Yes, I think that we need to pass the `requestTimeout` to Netty, and only the timeout in the options to tarantool/crud.

2023-03-03 22:50 UTC, akudiyar requested changes
We need to pass `requestTimeout` to the handlers and `timeout` in options to crud

2023-03-06 14:29 UTC, Elishtar approved these changes

2023-03-16 22:00 UTC, akudiyar approved these changes
LGTM, as it at least removes the ambiguity.

I've created a new issue https://github.com/tarantool/cartridge-java/issues/367 for implementing the `requestTimeout` option correctly.

2023-03-16 22:01 UTC, merged