WIP add migrations (ddl problem)
tarantool/cartridge-java pull request #363
Opened 2023-03-01 18:40 UTC by iDneprov

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2023-03-02 09:53 UTC, ArtDu requested changes

2023-03-02 09:53 UTC, ArtDu commented on src/test/resources/cartridge/replicasets.yml
> -    - s1-master
It's better to still master, because how would you specify a replica if it was. Better `s1-master`, `s1-replica'. And the name of the replicaset can simply be s1. The letter s already symbolizes storage

2023-03-02 09:53 UTC, ArtDu commented on src/test/resources/cartridge/migrations/11_accounts.lua
> +return {
Add more digits to the name of the file. `011_accounts.lua`

2023-03-02 09:53 UTC, ArtDu commented on src/test/resources/cartridge/init.lua
> +require('migrator')
why do you need it ?

2023-03-02 09:53 UTC, ArtDu commented on src/test/resources/cartridge/app/roles/api_storage.lua
> -        init_space()
delete inner of init_space

2023-03-02 09:53 UTC, ArtDu commented on docs/SpaceNotFound.md
> +router. You will receive an error message like space not found.
The interesting thing that I got right now. We don't need to use ddl since we parse metadata from response. But we need to change this behaviour in code not to parse ddl

2023-03-02 09:53 UTC, ArtDu commented on docs/SpaceNotFound.md
> +Also you can proxy ddl.get_schema from storage to routers this should also fix your problem. But migrations are preferred.
Need example of proxy. Words don't get a way of using

2023-03-02 09:53 UTC, ArtDu commented on README.md
> +    Specifying custom numbers of netty work threads.
```suggestion
    The problem of getting metadata.
```

2023-03-02 11:10 UTC, iDneprov commented on src/test/resources/cartridge/replicasets.yml
> -    - s1-master
Renamed according topology.lua and instances.yml

2023-03-02 13:08 UTC, iDneprov commented on src/test/resources/cartridge/migrations/11_accounts.lua
> +return {
done

2023-03-03 10:54 UTC, iDneprov commented on src/test/resources/cartridge/app/roles/api_storage.lua
> -        init_space()
done

2023-03-03 10:54 UTC, iDneprov commented on src/test/resources/cartridge/init.lua
> +require('migrator')
removed

2023-03-30 11:05 UTC, closed without merging