Add metadataFormatIsEmpty in TarantoolTuple
tarantool/cartridge-java pull request #372
Opened 2023-03-22 12:07 UTC by ArtDu

It's needed when we expected crud and box responses by one mapper(AUTO mapper in cartridge-springdata). In case when we obtain box response and we didn't have prepared metadata from ddl/_vspace, we can't map these values to Entity without metadata and we can't check whether we have it or not. And we can't raise an exception that we don't have metadata before because we can take it from crud response. Springdata doesn't see a difference between crud and box responses, it only got TarantoolTupleResult

I haven't forgotten about:
- [x] Tests
- [x] Changelog
- [ ] Documentation
- [x] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [x] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Needed for https://github.com/tarantool/cartridge-springdata/issues/123

2023-03-27 10:15 UTC, akudiyar requested changes
This change is OK by itself, just some wording and naming needs to be fixed.

But there is a greater question, do we need this change at all. It seems it is not comfortable to work with a tuple that represents in fact two different entities.

Can it be better if derive a `TarantoolTupleWithMetadata` interface from the original `TarantoolTuple` one, move to the second one all methods that access fields by names, add the corresponding `*Impl` class, and then use that interface distinction in SpringData via `instanceof`? That will allow us to finally avoid all the checks for metadata presence that we have to use in current implementation, and the user confusion when they try to get a field by name and see a strange "metadata does not exist" error.
With that implementation, we can change the `*Proxy*` API classes to return `TarantoolTupleWithMetadata` tuples instead of `TarantoolTuple` ones. That may also probably require changing the `TarantoolTuple` interface somewhere either to `Packable` or to `? extends TarantoolTuple`.

2023-03-27 10:15 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java
> +     * Check whether tuple have information about space format
```suggestion
     * Check whether this tuple includes information about space format
```

2023-03-27 10:15 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java
> +     * @return true if we obtain fields by names
```suggestion
     * @return true if we can obtain the tuple fields by names
```

2023-03-27 10:15 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java
> +    boolean metadataFormatIsEmpty();
I suggest using a simpler naming like `hasMetadata` or `isMetadataEmpty`

2023-03-28 16:36 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java
> +    boolean metadataFormatIsEmpty();
Renamed to `hasMetadata `

2023-03-29 21:50 UTC, akudiyar requested changes
I still have the same question, see below

2023-03-29 21:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java
> +    boolean hasMetadata();
If we are going to use different types (`TarantoolTuple` and `TarantoolTupleWithMetadata`). do we really need this method then? It is a public API, we need to carefully think before changing it

2023-03-29 21:50 UTC, akudiyar commented on CHANGELOG.md
> +- Add metadataFormatIsEmpty in TarantoolTuple
We need to change this entry too

2023-03-31 09:22 UTC, ArtDu commented on CHANGELOG.md
> +- Add metadataFormatIsEmpty in TarantoolTuple
```suggestion
- Add hasMetadata in TarantoolTuple
```

2023-03-31 10:56 UTC, akudiyar commented
OK. Let's amend this change in the nearest updates then.

2023-03-31 10:56 UTC, akudiyar approved these changes

2023-03-31 10:57 UTC, merged