Add mappers doc
tarantool/cartridge-java pull request #384
Opened 2023-04-17 17:23 UTC by iDneprov

Add page about converters, mappers and mapper factories

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

Closes #142

2023-04-19 22:55 UTC, akudiyar requested changes
Added a bit more info

2023-04-19 22:55 UTC, akudiyar commented on docs/MappersAndConverters.md
> +If you need converter witch will convert `MessagePack` type to Java basic type (`int`, `double`, `String` and etc.) you can implement `ObjectConverter` interface and
```suggestion
If you need converter which will convert `MessagePack` type to Java basic type (`int`, `double`, `String` and etc.) you can implement `ObjectConverter` interface and
```

2023-04-19 22:55 UTC, akudiyar commented on docs/MappersAndConverters.md
> +The mapper contains a list of converters.
```suggestion
The mapper contains a stack of converters.
```

2023-04-19 22:55 UTC, akudiyar commented on docs/MappersAndConverters.md
> +1) The mapper chooses the first matching converter from the end of the list.
```suggestion
1) The mapper chooses the first matching converter from the top of the stack (the one that was added last).
```

2023-04-19 22:55 UTC, akudiyar commented on docs/MappersAndConverters.md
> +
```suggestion
3) If this converter is not applicable, the mapper checks the next topmost converter after it.

```

2023-04-19 22:55 UTC, akudiyar commented on docs/MappersAndConverters.md
> +## Using default mappers
```suggestion
## Using built-in mappers
```

2023-04-19 22:55 UTC, akudiyar commented on docs/MappersAndConverters.md
> +If you want to manually choose target type by getting values from tarantool's tuple, use `get{targetTypeName}` methods
```suggestion
If you want to manually choose the target type for a particular field in a tuple, use `get{targetTypeName}` methods
```

2023-04-19 22:55 UTC, akudiyar commented on docs/MappersAndConverters.md
> +like `getInteger`, `getString` and others see entire list in [TarantoolTuple interface](https://github.com/tarantool/cartridge-java/blob/master/src/main/java/io/tarantool/driver/api/tuple/TarantoolTu
```suggestion
like `getInteger`, `getString` and others.  See the entire list in [TarantoolTuple interface](https://github.com/tarantool/cartridge-java/blob/master/src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java)
```

2023-04-19 22:55 UTC, akudiyar commented on docs/MappersAndConverters.md
> +because it will be added to the end of the mapper list.
```suggestion
because it will be added to the top of the mapper stack.
```

2023-04-19 22:55 UTC, akudiyar commented on docs/MappersAndConverters.md
> +If you need to set the structure of the received tuple, use mapper factory:
```suggestion
If you need to work with a custom structure of the received MessagePack objects, e.g. from a custom Lua method,  use the mapper factory:  
```

2023-04-19 22:55 UTC, akudiyar commented on docs/MappersAndConverters.md
> +
```suggestion
Converters for container types (like lists and maps) can use mappers inside too, such converters (and mappers holding them) will be in fact recursive.

```

2023-04-21 11:39 UTC, iDneprov commented
@akudiyar @ArtDu @vasilevichra 
I'm waiting for your feedback, guys.

2023-04-22 17:52 UTC, akudiyar approved these changes

2023-04-24 09:09 UTC, vasilevichra approved these changes

2023-04-24 09:29 UTC, ArtDu requested changes

2023-04-24 09:29 UTC, ArtDu commented on docs/MappersAndConverters.md
> +In order to convert data from MessagePack types to basic Java types (`int`, `double`, `String` and etc.) and back, you need mappers.
```suggestion
In order to convert data from MessagePack types to basic Java types (`Integer`, `Double`, `String` and etc.) and back, you need mappers.
```

Small correction, we don't use primitive types for integer, double for parsing

2023-04-24 09:29 UTC, ArtDu commented on docs/MappersAndConverters.md
> +(depends on converter type see [creating your own converter](#creating-your-own-converter)) method returns `true` for that value.
I would divide this point into two points and make it simpler.

```suggestion
2) Check that converter is suitable
    * The source type equals the input type of converter
    * `canConvertValue` or `canConvertObject`((depends on converter type see [creating your own converter](#creating-your-own-converter))) should return true
```

2023-04-24 09:29 UTC, ArtDu commented on docs/MappersAndConverters.md
> +Also, you can get required mappers from `TarantoolClient`:
What does `required` means in current context?

```suggestion
Also, you can get the default mapper stack from `TarantoolClient`, change it, or use it:   
```

2023-04-24 09:29 UTC, ArtDu commented on docs/MappersAndConverters.md
> +
```suggestion
Note: be careful changing the client mapper, it's used as the default mapper for API(`call`, `space(spaceName).select`, ...)

```

2023-04-24 12:23 UTC, ArtDu approved these changes

2023-04-25 13:55 UTC, vasilevichra submitted a review, later dismissed

2023-04-25 14:14 UTC, ArtDu approved these changes

2023-04-25 15:04 UTC, iDneprov commented
@akudiyar @ArtDu @vasilevichra
I want to merge this PR tomorrow morning.
Please leave your feedback today if you want to change something.

2023-04-25 15:05 UTC, vasilevichra approved these changes

2023-04-25 15:05 UTC, ArtDu approved these changes

2023-04-26 10:17 UTC, merged