WIP
tarantool/cartridge-java pull request #391
Opened 2023-05-02 15:22 UTC by ArtDu

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2023-05-08 20:34 UTC, akudiyar requested changes
Changing the `call` method signature seems reasonable, but that's a breaking change and we must notify the customers appropriately. Changing `MessagePackMapper` parameter types to `MessagePackValueMapper` also seems reasonable.

But we shouldn't have any raw  `Object`s in the API (`List<?>` in `call` and `eval` is the only exception here because of the compatibility with `tarantool-java` and also it's a better variant than just `Object`). ALso I don't get why we change `CallResultMapper` result types to something else.

2023-05-08 20:34 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    <T> CompletableFuture<T> call(
We will have to change the other `call()` functions that return `TarantoolResult` too - see lines 79, 91, 109

2023-05-08 20:34 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +        CallResultMapper<Object, SingleValueCallResult<Object>>
Here we should have generics (`T` and a parameter of type `Class<T>`) and not `Object`, that will be a very bad API otherwise

2023-05-08 20:34 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +        CallResultMapper<Object, SingleValueCallResult<Object>>
Here we should have generics (`T` and a parameter of type `Class<T>`) and not `Object`, that will be a very bad API otherwise

2023-05-08 20:34 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +        CallResultMapper<Object, SingleValueCallResult<Object>>
Here we should have generics (`T` and a parameter of type `Class<T>`) and not `Object`, that will be a very bad API otherwise

2023-05-08 20:34 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +        MessagePackValueMapper buildCallResultMapper();
Why do we need to change this?

2023-05-23 14:54 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +        CallResultMapper<Object, SingleValueCallResult<Object>>
T doesn't fit for us. Because generic require us to detail type and it would be only one type. But I want to have mapper that can be fit for all possible responses. I had to use wildcard(?) for it like in generic call method, but there were problems as I remember. I trying to get off easy

2023-05-25 17:13 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
> +    <T> CompletableFuture<T> call(
Changed

2023-05-25 17:15 UTC, ArtDu commented
> But we shouldn't have any raw `Object`s in the API (`List<?>` in `call` and `eval` is the only exception here because of the compatibility with `tarantool-java` and also it's a better variant than just `Object`). ALso I don't get why we change `CallResultMapper` result types to something else.

I added two ways of using with generics and without. We need object for universal mapping when return type is uncertain

2023-05-29 15:30 UTC, akudiyar commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +        MessagePackValueMapper buildCallResultMapper();
That contradicts with the method name then, and that means you need either a new method or you want some other change in behavior.

2023-05-31 22:22 UTC, ArtDu commented on src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
> +        MessagePackValueMapper buildCallResultMapper();
Fixed

2023-05-31 22:27 UTC, ArtDu commented
@akudiyar I probably did all what we discussed. And also I updated PR in springdata(https://github.com/tarantool/cartridge-springdata/pull/124). Please check both PR and give your opinion

2023-06-01 22:25 UTC, akudiyar approved these changes
That's in the much better shape now. I have just three small nitpicks

2023-06-01 22:25 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +        CallResultMapper<TarantoolTupleResultImpl, SingleValueCallResult<TarantoolTupleResultImpl>> callReturnMapper =
We shouldn't have `Impl` classes normally in the generic type spec. Is it intentional or a mistype?

2023-06-01 22:25 UTC, akudiyar commented on CHANGELOG.md
> +- **[breaking change]** Split call API for calls with tarantool result as return and call with generic return ([#123](https://github.com/tarantool/cartridge-springdata/issues/123))
```suggestion
- **[breaking change]** Split call API into calls with tuple result as return type and calls with generic Object return type ([#123](https://github.com/tarantool/cartridge-springdata/issues/123))
```

2023-06-01 22:25 UTC, akudiyar commented on CHANGELOG.md
> +- Add buildSingleValueResultMapper in mapper builder
```suggestion
- Add buildSingleValueResultMapper() in mapper builder for generic call result mappers. That will simplify the support for auto object converter in SpringData.
```

2023-06-01 22:43 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +        CallResultMapper<TarantoolTupleResultImpl, SingleValueCallResult<TarantoolTupleResultImpl>> callReturnMapper =
We have to pass class as argument of method. And I didn't want to use ugly casts (class<TarantoolResult<TarantoolTuple>>) (class<?>) anyClass

2023-06-02 10:38 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +        CallResultMapper<TarantoolTupleResultImpl, SingleValueCallResult<TarantoolTupleResultImpl>> callReturnMapper =
Oh, I got what you meant. I'll fix it now

2023-06-02 22:14 UTC, akudiyar approved these changes
LGTM

2023-06-02 22:15 UTC, merged