Update MultiInstanceConnecting
tarantool/cartridge-java pull request #398
Opened 2023-06-07 15:31 UTC by iDneprov

Added an explanation of when addresses need to be shuffled

I haven't forgotten about:
- [x] Tests
- [ ] Changelog
- [x] Documentation
- [x] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [x] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

Closes #394

2023-06-07 16:09 UTC, dkasimovskiy requested changes

2023-06-07 16:09 UTC, dkasimovskiy commented on docs/MultiInstanceConnecting.md
> +the first request of each of your clients will be sent to the same instance.
```suggestion
Without addresses **shuffle** the first request of each of your clients will be sent to the same instance.

2023-06-07 16:14 UTC, ArtDu commented on docs/MultiInstanceConnecting.md
> +TarantoolClient uses [round-robin](https://en.wikipedia.org/wiki/Round-robin_scheduling) so without URIs shuffle
```suggestion
By default TarantoolClient uses [round-robin](https://en.wikipedia.org/wiki/Round-robin_scheduling) approach to separate load between Tarantool instances.

```

2023-06-07 16:24 UTC, ArtDu commented on docs/MultiInstanceConnecting.md
> +the first request of each of your clients will be sent to the same instance.
```suggestion
> **Warning**
> Without addresses **shuffle** you may have a situation when clients will send something to the same instances. 
> Especially when you start your clients in parallel at the same time.
```

2023-06-07 21:46 UTC, akudiyar requested changes
Some adjustments for the text

2023-06-07 21:46 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +In case of using **multiple instances of TarantoolClient** we strongly recommend to **shuffle** list of addresses before providing them to clients.
```suggestion
In the case of using **multiple instances** of `TarantoolClient` we strongly recommend to apply a **shuffle** function to the list of addresses.
```

2023-06-07 21:46 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +By default TarantoolClient uses [round-robin](https://en.wikipedia.org/wiki/Round-robin_scheduling) approache to separate load between Tarantool instances.
```suggestion
By default, `TarantoolClient` uses the [round-robin](https://en.wikipedia.org/wiki/Round-robin_scheduling) approach for selecting the next available connection to distribute the load between Tarantool instances.
```

2023-06-07 21:46 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +Without addresses **shuffle** the first request of each of your clients will be sent to the same instance.
```suggestion
When several instances of `TarantoolClient` are used simultaneously, with the default connection selection strategy and without **shuffling** of the server addresses the first request from every instance will be sent to the same server.
```

2023-06-07 21:46 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +You do not have to worry about shuffling addresses if you are using single TarantoolClient connected to multiple instances.
```suggestion
You do not have to worry about shuffling addresses if you are using a single `TarantoolClient` connected to multiple instances, or if you are using a custom connection selection strategy that takes into account the problem of simultaneous requests.
```

2023-06-07 21:46 UTC, akudiyar commented on docs/MultiInstanceConnecting.md
> +Without addresses **shuffle** the first request of each of your clients will be sent to the same instance.
What problem do the simultaneous requests cause? We need to add a line about that, currently the readers will be confused

2023-06-08 07:25 UTC, iDneprov commented
@dkasimovskiy Ready for review. Fixed by @akudiyar comments.

2023-06-08 07:46 UTC, dkasimovskiy approved these changes

2023-06-08 07:46 UTC, merged