Fix losing connection if restart happened faster than discovery task
tarantool/cartridge-java pull request #405
Opened 2023-07-25 16:10 UTC by ArtDu

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2023-07-25 20:54 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +        if (areConnectionsAlive()) {
I think that is not useful - we may want to trigger restart even if (all or some of) the connections are dead (like, the Tarantool server is restarting while the application with driver is still online).

2023-07-25 20:54 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +        return connectionRegistry.keySet().equals(new HashSet<>(addresses));
What is the meaning of this check?

2023-07-25 20:58 UTC, akudiyar requested changes

2023-07-25 20:58 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +import org.testcontainers.shaded.org.apache.commons.lang3.reflect.FieldUtils;
That's a bad import, do we really need it?

2023-07-26 08:44 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +import org.testcontainers.shaded.org.apache.commons.lang3.reflect.FieldUtils;
I think it's OK for testing purposes

2023-07-26 08:54 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +        if (areConnectionsAlive()) {
You comment is reasonable. I'll think about it. I guess we have to check connections outside refresh. Without it discovery is broken. 

Or we can always run refresh in every discovery task. I haven't followed this approach because in each refresh we use mutex(phaser). And it probably follows problem with less perfomance

2023-07-26 08:59 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +        return connectionRegistry.keySet().equals(new HashSet<>(addresses));
If addreses have changed we need to drop the old ones. I moved this logic from discovery tssk code

2023-07-26 09:30 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +import org.testcontainers.shaded.org.apache.commons.lang3.reflect.FieldUtils;
I'd rather avoid such import even in the tests, that pollutes the library classpath. Import the commons library (or even a better one), but don't use an internal dependency of a dependency

2023-07-26 09:32 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +        if (areConnectionsAlive()) {
The refresh trigger was designed to be used in the discovery task explicitly. So if it is called independently somewhere before the discovery returns any addresses, that is incorrect.

2023-07-26 09:33 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +        if (areConnectionsAlive()) {
Looks like we introduced a `refresh` call somewhere and forgot about its purpose

2023-07-26 09:35 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +                innerClient = (ClusterTarantoolTupleClient) FieldUtils.readField(
If we need to test this field (do we need really?), let's provide an (internal) interface to retrieve it. Using reflection is unnecessary.

2023-07-26 11:28 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +import org.testcontainers.shaded.org.apache.commons.lang3.reflect.FieldUtils;
Aa, you are about import string. I'll change it

2023-07-26 11:30 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +        if (areConnectionsAlive()) {
> The refresh trigger was designed to be used in the discovery task explicitly. So if it is called independently somewhere before the discovery returns any addresses, that is incorrect.

Yeap, I changed it. Now refresh is like it was before. Discovery calls different function that checks conditions and calls refresh

2023-07-26 15:24 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
> +                innerClient = (ClusterTarantoolTupleClient) FieldUtils.readField(
In this commit, I've shown what we have to add to check real connections via the client 5534b16a8aee3a129bae8c0c6d44a76ae3dda730

2023-07-26 16:01 UTC, iDneprov commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +    protected boolean areConditionsChanged() {
Update method logics

2023-07-26 16:13 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +    protected boolean areConditionsChanged() {
Fixed

2023-07-26 21:50 UTC, akudiyar requested changes
I have a few questions, otherwise looks good

2023-07-26 21:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +    public Map<TarantoolServerAddress, List<TarantoolConnection>> getConnectionRegistry() {
Should it be public really? Or package-private is enough?

2023-07-26 21:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +    protected boolean areConditionsChanged() {
Let's rename that method to something more specific. Like `haveAddressesChanged`

2023-07-26 21:50 UTC, akudiyar commented on src/main/java/io/tarantool/driver/core/RetryingTarantoolClient.java
> +    public TarantoolConnectionManager getConnectionManager() {
Should it be public? Make it package-private if possible

2023-07-27 10:12 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +    public Map<TarantoolServerAddress, List<TarantoolConnection>> getConnectionRegistry() {
Public because we call this method in test

2023-07-27 10:14 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/RetryingTarantoolClient.java
> +    public TarantoolConnectionManager getConnectionManager() {
It should be because we hold TarantoolClient interface in Proxy/Retrying clients as inner client

2023-07-27 10:19 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +    protected boolean areConditionsChanged() {
I split the method on two

```
areAddressesChanged
```

```
areConnectionsAlive
```

2023-07-27 10:52 UTC, ArtDu commented on src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
> +    public Map<TarantoolServerAddress, List<TarantoolConnection>> getConnectionRegistry() {
I realized that we have connection listeners and we don't need to expose connections itself

2023-07-27 21:55 UTC, akudiyar approved these changes

2023-07-27 21:56 UTC, merged