Improve reusing Docker images between tests
tarantool/cartridge-java pull request #410
Opened 2023-07-29 18:57 UTC by akudiyar

Re-building images between test suites is unnecessary, and this can be mitigated by using image names.
This patch does the following:

- Improves reusing Docker images by assigning image names and using layers in the Dockerfile
- Improves logging for docker-java client

2023-08-02 15:07 UTC, ArtDu requested changes
Thanks for the patch. I have only one question

2023-08-02 15:07 UTC, ArtDu commented on src/test/resources/Dockerfile
> +    --log-dir=$TARANTOOL_LOGDIR --cfg=$TARANTOOL_INSTANCES_FILE
May we change it in testcontainer library itself? https://github.com/tarantool/testcontainers-java-tarantool/blob/master/src/main/resources/Dockerfile

2023-08-03 14:27 UTC, iDneprov commented on src/test/resources/Dockerfile
> +    --log-dir=$TARANTOOL_LOGDIR --cfg=$TARANTOOL_INSTANCES_FILE
@akudiyar 
Alexey, hi!
we want to release a new version of the connector tomorrow.Please fix your PM so that it will be included in the release.

2023-08-04 20:37 UTC, akudiyar commented on src/test/resources/Dockerfile
> +    --log-dir=$TARANTOOL_LOGDIR --cfg=$TARANTOOL_INSTANCES_FILE
Ah, sorry, I was AFK for two days. Let it be included in the next release then

2023-08-04 21:17 UTC, akudiyar commented
Now this PR needs https://github.com/tarantool/testcontainers-java-tarantool/pull/83 to be merged and a new testontainers version to be published. Then we can use the default Dockerfile and remove it from this patch.

2023-10-03 16:34 UTC, akudiyar commented
testcontainers-java-tarantool is updated to 1.0.1. Now this PR is ready for merging

2023-10-04 09:15 UTC, ArtDu approved these changes
Looks good

2023-10-04 16:06 UTC, merged