Added "mode" option for crud select operation
tarantool/cartridge-java pull request #416
Opened 2023-09-05 13:16 UTC by nickkkccc

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Needed for #107

2023-09-05 13:57 UTC, ArtDu reviewed
Thanks for the PR. Great job, I left only two small comments

2023-09-05 13:57 UTC, ArtDu commented on CHANGELOG.md
> +### API changes
It's better to squash all these commits to one

2023-09-05 13:57 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/OperationWithModeOptions.java
> +        if (!mode.equals("read") && !mode.equals("write")) {
nit: You can use enum because modes are determined values. It's up to you

2023-09-05 20:33 UTC, akudiyar requested changes
Looks good, I have two suggestions BTW

2023-09-05 20:33 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/OperationWithModeOptions.java
> +        if (!mode.equals("read") && !mode.equals("write")) {
I suggest using enums. This check will look better then. Also, the users will benefit from using the enum values that are better supported by autocompletion in editors.

2023-09-05 20:33 UTC, akudiyar commented on src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java
> +    public void withMode() throws ExecutionException, InterruptedException {
```suggestion
    public void withModeTest() throws ExecutionException, InterruptedException {
```

2023-09-05 20:33 UTC, akudiyar commented on src/main/java/io/tarantool/driver/api/space/options/OperationWithModeOptions.java
> +        if (!mode.equals("read") && !mode.equals("write")) {
Also I kinda not like the initial naming, it's rather strange. We may think about using something more widely used in the industry, like `leader`/`replica`, otherwise the meaning is very obscure (my first thought was "is `select` writing anything?!")

2023-09-06 07:14 UTC, ArtDu commented on src/main/java/io/tarantool/driver/api/space/options/OperationWithModeOptions.java
> +        if (!mode.equals("read") && !mode.equals("write")) {
> Also I do not like the initial naming, it's rather strange. We may think about using something more widely used in the industry, like `leader`/`replica`, otherwise the meaning is very obscure (my first thought was "is `select` writing anything?!")

It should have been renamed in crud/vshard. If we changed it in connector it would be confusuing thing for users who wants to understand how tarantool and ecosystem works. Let it be unified

2023-09-06 09:19 UTC, nickkkccc commented on src/main/java/io/tarantool/driver/api/space/options/OperationWithModeOptions.java
> +        if (!mode.equals("read") && !mode.equals("write")) {
Thanks. Done.

2023-09-06 09:19 UTC, nickkkccc commented on src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java
> +    public void withMode() throws ExecutionException, InterruptedException {
Fix in commit.

2023-09-06 10:01 UTC, ArtDu approved these changes

2023-09-06 10:02 UTC, merged