Bump testcontainers-java-tarantool to 1.0.2
tarantool/cartridge-java pull request #444
Opened 2023-11-16 12:21 UTC by nickkkccc

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Closes #442

2023-12-12 12:52 UTC, dkasimovskiy requested changes

2023-12-12 12:52 UTC, dkasimovskiy commented on pom.xml
> +            <version>1.0.2</version>
```suggestion
            <version>1.1.0</version>
```

2023-12-20 10:59 UTC, dkasimovskiy approved these changes

2023-12-20 15:45 UTC, ArtDu requested changes

2023-12-20 15:45 UTC, ArtDu commented on src/test/resources/cartridge/init.lua
> +    cluster_cookie = 'secret-cluster-cookie',
it is default value and you can just remove this whole line

2023-12-20 15:45 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/ssl/SslClientITEnterprise.java
> -            .withDirectoryBinding(RESOURCE_PATH + "ssl")
you won't get files that are placed in `org/testcontainers/containers/enterprise/ssl` that needed for testing

2023-12-20 18:19 UTC, nickkkccc commented on src/test/java/io/tarantool/driver/integration/ssl/SslClientITEnterprise.java
> -            .withDirectoryBinding(RESOURCE_PATH + "ssl")
Fixed it for enterprise tests

2023-12-20 18:19 UTC, nickkkccc commented on src/test/resources/cartridge/init.lua
> +    cluster_cookie = 'secret-cluster-cookie',
Removed

2023-12-20 19:40 UTC, bitgorbovsky approved these changes

2023-12-21 03:16 UTC, ArtDu reviewed
LGTM, but I have a question about container behavior

2023-12-21 03:16 UTC, ArtDu commented on src/test/java/io/tarantool/driver/integration/CartridgeMixedInstancesContainer.java
> -                        .withDirectoryBinding("cartridge")
I don't get how this works. Please explain how does a container get needed files?

2023-12-21 07:31 UTC, nickkkccc commented on src/test/java/io/tarantool/driver/integration/CartridgeMixedInstancesContainer.java
> -                        .withDirectoryBinding("cartridge")
***Previous version of the test containers (e.g., 1.0.1):***
1. Dependencies are downloaded on the system inside the container (gcc and others).
2. The cartridge folder is a mapping of the `/app` directory.
3. The cartridge folder is copied into the image as the `/app` working directory. This step is where the image is built.
4. Start the container and run the `cartridge build` command (dependency rocks are downloaded into the working directory at this point).
5. `Key point:` the dependency rocks are downloaded into the `/app` directory related to the container. But docker looks at the cartridge folder that was mapped earlier in the build phase.

***New version of testcontainers:***

Copying the `/cartridge` directory and executing cartridge build happens during the image build phase. `Key point:` when using the `.withDirectoryBinding` method at the container startup stage, docker will look at the `/cartridge` directory that doesn't have the built rocks dependencies in it

2023-12-21 09:51 UTC, ArtDu approved these changes

2023-12-21 09:53 UTC, merged